/datum/component/personal_crafting/Initialize()
/datum/component/personal_crafting/proc/create_mob_button(mob/user, client/CL)
/datum/component/personal_crafting
/datum/component/personal_crafting/proc/check_contents(atom/a, datum/crafting_recipe/R, list/contents)
/datum/component/personal_crafting/proc/get_environment(atom/a, list/blacklist = null, radius_range = 1)
/datum/component/personal_crafting/proc/get_surroundings(atom/a, list/blacklist=null)
/datum/component/personal_crafting/proc/check_tools(atom/source, datum/crafting_recipe/recipe, list/surroundings)
/datum/component/personal_crafting/proc/construct_item(atom/a, datum/crafting_recipe/R)
/datum/component/personal_crafting/proc/del_reqs(datum/crafting_recipe/R, atom/a)
/datum/component/personal_crafting/proc/component_ui_interact(atom/movable/screen/craft/image, location, control, params, user)
/datum/component/personal_crafting/ui_state(mob/user)
/datum/component/personal_crafting/ui_interact(mob/user, datum/tgui/ui)
/datum/component/personal_crafting/ui_data(mob/user)
/datum/component/personal_crafting/ui_static_data(mob/user)
/datum/component/personal_crafting/ui_act(action, params)
/datum/component/personal_crafting/proc/build_recipe_data(datum/crafting_recipe/R)
/datum/mind/proc/teach_crafting_recipe(R)
