/obj/machinery/biogenerator
	name = "biogenerator"
	desc = "Converts plants into biomass, which can be used to construct useful items."
/obj/machinery/biogenerator/Initialize(mapload)
/obj/machinery/biogenerator/Destroy()
/obj/machinery/biogenerator/contents_explosion(severity, target)
/obj/machinery/biogenerator/handle_atom_del(atom/A)
/obj/machinery/biogenerator/RefreshParts()
/obj/machinery/biogenerator/examine(mob/user)
/obj/machinery/biogenerator/update_icon_state()
/obj/machinery/biogenerator/attackby(obj/item/O, mob/living/user, params)
/obj/machinery/biogenerator/AltClick(mob/living/user)
/obj/machinery/biogenerator/proc/activate(mob/user)
/obj/machinery/biogenerator/proc/check_cost(list/materials, multiplier = 1, remove_points = TRUE)
/obj/machinery/biogenerator/proc/check_container_volume(list/reagents, multiplier = 1)
/obj/machinery/biogenerator/proc/create_product(datum/design/D, amount)
/obj/machinery/biogenerator/proc/insert_beaker(mob/living/user, obj/item/reagent_containers/glass/inserted_beaker)
/obj/machinery/biogenerator/proc/eject_beaker(mob/living/user, silent = FALSE)
/obj/machinery/biogenerator/ui_status(mob/user)
/obj/machinery/biogenerator/ui_assets(mob/user)
/obj/machinery/biogenerator/ui_interact(mob/user, datum/tgui/ui)
/obj/machinery/biogenerator/ui_data(mob/user)
/obj/machinery/biogenerator/ui_static_data(mob/user)
/obj/machinery/biogenerator/ui_act(action, list/params)
