/obj/item/seeds
/obj/item/seeds/Initialize(mapload, nogenes = FALSE)
/obj/item/seeds/Destroy()
/obj/item/seeds/examine(mob/user)
/obj/item/seeds/proc/Copy()
/obj/item/seeds/proc/get_gene(typepath)
/obj/item/seeds/proc/reagents_from_genes()
/obj/item/seeds/proc/mutate(lifemut = 2, endmut = 5, productmut = 1, yieldmut = 2, potmut = 25, wrmut = 2, wcmut = 5, traitmut = 0, stabmut = 3)
/obj/item/seeds/bullet_act(obj/projectile/Proj) //Works with the Somatoray to modify plant variables.
/obj/item/seeds/proc/getYield()
/obj/item/seeds/proc/harvest(mob/user)
/obj/item/seeds/proc/prepare_result(obj/item/T)
/obj/item/seeds/proc/adjust_yield(adjustamt)
/obj/item/seeds/proc/adjust_lifespan(adjustamt)
/obj/item/seeds/proc/adjust_endurance(adjustamt)
/obj/item/seeds/proc/adjust_production(adjustamt)
/obj/item/seeds/proc/adjust_potency(adjustamt)
/obj/item/seeds/proc/adjust_instability(adjustamt)
/obj/item/seeds/proc/adjust_weed_rate(adjustamt)
/obj/item/seeds/proc/adjust_weed_chance(adjustamt)
/obj/item/seeds/proc/set_yield(adjustamt)
/obj/item/seeds/proc/set_lifespan(adjustamt)
/obj/item/seeds/proc/set_endurance(adjustamt)
/obj/item/seeds/proc/set_production(adjustamt)
/obj/item/seeds/proc/set_potency(adjustamt)
/obj/item/seeds/proc/set_instability(adjustamt)
/obj/item/seeds/proc/set_weed_rate(adjustamt)
/obj/item/seeds/proc/set_weed_chance(adjustamt)
/obj/item/seeds/proc/get_unique_analyzer_text()
/obj/item/seeds/proc/on_chem_reaction(datum/reagents/reagents)
/obj/item/seeds/attackby(obj/item/O, mob/user, params)
	name = "[lowertext(newplantname)]"
	desc = newdesc
/obj/item/seeds/proc/randomize_stats()
/obj/item/seeds/proc/add_random_reagents(lower = 0, upper = 2)
/obj/item/seeds/proc/add_random_traits(lower = 0, upper = 2)
/obj/item/seeds/proc/add_random_plant_type(normal_plant_chance = 75)
/obj/item/seeds/proc/remove_random_reagents(lower = 0, upper = 2)
/obj/item/seeds/proc/create_graft()
/obj/item/seeds/proc/apply_graft(obj/item/graft/snip)
/obj/item/proc/get_plant_seed()
/obj/item/food/grown/get_plant_seed()
/obj/item/grown/get_plant_seed()
