/datum/antagonist
/datum/antagonist/New()
/datum/antagonist/Destroy()
/datum/antagonist/proc/can_be_owned(datum/mind/new_owner)
/datum/antagonist/proc/specialization(datum/mind/new_owner)
/datum/antagonist/proc/on_body_transfer(mob/living/old_body, mob/living/new_body)
/datum/antagonist/proc/apply_innate_effects(mob/living/mob_override)
/datum/antagonist/proc/remove_innate_effects(mob/living/mob_override)
/datum/antagonist/proc/pre_mindshield(mob/implanter, mob/living/mob_override)
/datum/antagonist/proc/on_mindshield(mob/implanter, mob/living/mob_override)
/datum/antagonist/proc/handle_clown_mutation(mob/living/mob_override, message, removing = TRUE)
/datum/antagonist/proc/create_team(datum/team/team)
/datum/antagonist/proc/on_gain()
/datum/antagonist/proc/is_banned(mob/M)
/datum/antagonist/proc/replace_banned_player()
/datum/antagonist/proc/on_removal()
/datum/antagonist/proc/greet()
/datum/antagonist/proc/farewell()
/datum/antagonist/proc/give_antag_moodies()
/datum/antagonist/proc/clear_antag_moodies()
/datum/antagonist/proc/get_team()
/datum/antagonist/proc/roundend_report()
/datum/antagonist/proc/roundend_report_header()
/datum/antagonist/proc/roundend_report_footer()
/datum/antagonist/proc/admin_add(datum/mind/new_owner,mob/admin)
/datum/antagonist/proc/admin_remove(mob/user)
/datum/antagonist/proc/antag_panel_data()
/datum/antagonist/proc/enabled_in_preferences(datum/mind/M)
/datum/antagonist/proc/get_admin_commands()
/datum/antagonist/proc/render_preview_outfit(datum/outfit/outfit, mob/living/carbon/human/dummy)
/datum/antagonist/proc/finish_preview_icon(icon/icon)
/datum/antagonist/proc/get_preview_icon()
/datum/antagonist/Topic(href,href_list)
/datum/antagonist/proc/edit_memory(mob/user)
/datum/antagonist/proc/hijack_speed()
/datum/antagonist/proc/add_team_hud(mob/target, antag_to_check)
/datum/atom_hud/alternate_appearance/basic/has_antagonist,
/datum/antagonist/custom
/datum/antagonist/custom/create_team(datum/team/team)
/datum/antagonist/custom/get_team()
/datum/antagonist/custom/admin_add(datum/mind/new_owner,mob/admin)
	name = custom_name
/datum/antagonist/ui_interact(mob/user, datum/tgui/ui)
/datum/antagonist/ui_state(mob/user)
/datum/antagonist/proc/get_objectives()
/datum/antagonist/ui_static_data(mob/user)
/datum/action/antag_info
	name = "Open Antag Information:"
/datum/action/antag_info/New(Target, datum/antagonist/antag_datum)
	name = " [antag_datum.name]"
/datum/action/antag_info/Trigger()
/datum/action/antag_info/IsAvailable()
