/obj/effect
/obj/effect/attackby(obj/item/weapon, mob/user, params)
/obj/effect/take_damage(damage_amount, damage_type = BRUTE, damage_flag = 0, sound_effect = 1, attack_dir)
/obj/effect/fire_act(exposed_temperature, exposed_volume)
/obj/effect/acid_act()
/obj/effect/blob_act(obj/structure/blob/B)
/obj/effect/attack_hulk(mob/living/carbon/human/user)
/obj/effect/experience_pressure_difference()
/obj/effect/ex_act(severity, target)
/obj/effect/singularity_act()
/obj/effect/abstract/singularity_pull()
/obj/effect/abstract/singularity_act()
/obj/effect/abstract/has_gravity(turf/T)
/obj/effect/dummy/singularity_pull()
/obj/effect/dummy/singularity_act()
