/obj/effect/step_trigger
/obj/effect/step_trigger/Initialize(mapload)
/obj/effect/step_trigger/proc/Trigger(atom/movable/A)
/obj/effect/step_trigger/proc/on_entered(datum/source, H as mob|obj)
/obj/effect/step_trigger/singularity_act()
/obj/effect/step_trigger/singularity_pull()
/obj/effect/step_trigger/message
/obj/effect/step_trigger/message/Trigger(mob/M)
/obj/effect/step_trigger/thrower
/obj/effect/step_trigger/thrower/Trigger(atom/A)
/obj/effect/step_trigger/stopper
/obj/effect/step_trigger/teleporter
/obj/effect/step_trigger/teleporter/Trigger(atom/movable/A)
/obj/effect/step_trigger/teleporter/random
/obj/effect/step_trigger/teleporter/random/Trigger(atom/movable/A)
/obj/effect/step_trigger/teleport_fancy
/obj/effect/step_trigger/teleport_fancy/Trigger(mob/M)
/obj/effect/step_trigger/sound_effect
/obj/effect/step_trigger/sound_effect/Trigger(atom/movable/A)
