/mob/living/silicon/pai/blob_act(obj/structure/blob/B)
/mob/living/silicon/pai/emp_act(severity)
/mob/living/silicon/pai/ex_act(severity, target)
/mob/living/silicon/pai/attack_hand(mob/living/carbon/human/user, list/modifiers)
/mob/living/silicon/pai/bullet_act(obj/projectile/Proj)
/mob/living/silicon/pai/IgniteMob(mob/living/silicon/pai/P)
/mob/living/silicon/pai/proc/take_holo_damage(amount)
/mob/living/silicon/pai/adjustBruteLoss(amount, updating_health = TRUE, forced = FALSE)
/mob/living/silicon/pai/adjustFireLoss(amount, updating_health = TRUE, forced = FALSE)
/mob/living/silicon/pai/adjustStaminaLoss(amount, updating_health, forced = FALSE)
/mob/living/silicon/pai/getBruteLoss()
/mob/living/silicon/pai/getFireLoss()
