/mob/living/silicon/pai/proc/fold_out(force = FALSE)
/mob/living/silicon/pai/proc/emittercool()
/mob/living/silicon/pai/proc/fold_in(force = FALSE)
/mob/living/silicon/pai/proc/choose_chassis()
/mob/living/silicon/pai/proc/set_holochassis(choice)
/mob/living/silicon/pai/wabbajack()
/mob/living/silicon/pai/proc/check_menu(atom/anchor)
/mob/living/silicon/pai/update_resting()
/mob/living/silicon/pai/start_pulling(atom/movable/AM, state, force = move_force, supress_message = FALSE)
/mob/living/silicon/pai/proc/toggle_integrated_light()
/mob/living/silicon/pai/mob_try_pickup(mob/living/user, instant=FALSE)
