/proc/message_admins(msg)
/proc/relay_msg_admins(msg)
/datum/admins/proc/Game()
/datum/admins/proc/spawn_atom(object as text)
/datum/admins/proc/podspawn_atom(object as text)
/datum/admins/proc/spawn_cargo(object as text)
/datum/admins/proc/toggletintedweldhelmets()
/datum/admins/proc/output_ai_laws()
/datum/admins/proc/dynamic_mode_options(mob/user)
/datum/admins/proc/create_or_modify_area()
/proc/kick_clients_in_lobby(message, kick_only_afk = 0)
/datum/admins/proc/cmd_ghost_drag(mob/dead/observer/frommob, mob/tomob)
/client/proc/adminGreet(logout)
