/datum/antagonist/proc/antag_listing_name()
/datum/antagonist/proc/antag_listing_status()
/datum/antagonist/proc/antag_listing_commands()
/datum/antagonist/proc/antag_listing_entry()
/datum/team/proc/get_team_antags(antag_type,specific = FALSE)
/datum/team/proc/antag_listing_entry()
/datum/team/proc/antag_listing_name()
/datum/team/proc/antag_listing_footer()
/datum/admins/proc/build_antag_listing()
/datum/admins/proc/check_antagonists()
