/datum/greyscale_modify_menu
/datum/greyscale_modify_menu/New(atom/target, client/user, list/allowed_configs, datum/callback/apply_callback, starting_icon_state="", starting_config, starting_colors)
/datum/greyscale_modify_menu/Destroy()
/datum/greyscale_modify_menu/ui_state(mob/user)
/datum/greyscale_modify_menu/ui_close()
/datum/greyscale_modify_menu/ui_interact(mob/user, datum/tgui/ui)
/datum/greyscale_modify_menu/ui_data(mob/user)
/datum/greyscale_modify_menu/ui_act(action, params)
/datum/greyscale_modify_menu/proc/ReadColorsFromString(colorString)
/datum/greyscale_modify_menu/proc/randomize_color(color_index)
/datum/greyscale_modify_menu/proc/change_config(datum/greyscale_config/new_config)
/datum/greyscale_modify_menu/proc/queue_refresh()
/datum/greyscale_modify_menu/proc/refresh_preview()
/datum/greyscale_modify_menu/proc/Unlock()
/datum/greyscale_modify_menu/proc/DefaultApply()
/datum/greyscale_modify_menu/proc/SetupConfigOwner()
