/obj/machinery/light
	name = "light fixture"
	desc = "A lighting fixture."
/obj/machinery/light/Move()
/obj/machinery/light/Initialize(mapload)
/obj/machinery/light/LateInitialize()
/obj/machinery/light/Destroy()
/obj/machinery/light/update_icon_state()
/obj/machinery/light/update_overlays()
/obj/machinery/light/proc/update(trigger = TRUE, instant = FALSE, play_sound = TRUE) //SKYRAT EDIT CHANGE
/obj/machinery/light/update_atom_colour()
/obj/machinery/light/proc/broken_sparks(start_only=FALSE)
/obj/machinery/light/process()
/obj/machinery/light/proc/burn_out()
/obj/machinery/light/proc/set_on(turn_on)
/obj/machinery/light/get_cell()
/obj/machinery/light/examine(mob/user)
/obj/machinery/light/attackby(obj/item/tool, mob/living/user, params)
/obj/machinery/light/deconstruct(disassembled = TRUE)
/obj/machinery/light/attacked_by(obj/item/attacking_object, mob/living/user)
/obj/machinery/light/take_damage(damage_amount, damage_type = BRUTE, damage_flag = 0, sound_effect = 1)
/obj/machinery/light/play_attack_sound(damage_amount, damage_type = BRUTE, damage_flag = 0)
/obj/machinery/light/proc/turned_off()
/obj/machinery/light/proc/has_power()
/obj/machinery/light/proc/has_emergency_power(power_usage_amount)
/obj/machinery/light/proc/use_emergency_power(power_usage_amount = LIGHT_EMERGENCY_POWER_USE)
/obj/machinery/light/proc/flicker(amount = rand(10, 20))
/obj/machinery/light/attack_ai(mob/user)
/obj/machinery/light/attack_hand(mob/living/carbon/human/user, list/modifiers)
/obj/machinery/light/proc/drop_light_tube(mob/user)
/obj/machinery/light/attack_tk(mob/user)
/obj/machinery/light/proc/break_light_tube(skip_sound_and_sparks = FALSE)
/obj/machinery/light/proc/fix()
/obj/machinery/light/zap_act(power, zap_flags)
/obj/machinery/light/power_change()
/obj/machinery/light/should_atmos_process(datum/gas_mixture/air, exposed_temperature)
/obj/machinery/light/atmos_expose(datum/gas_mixture/air, exposed_temperature)
/obj/machinery/light/proc/explode()
/obj/machinery/light/proc/on_light_eater(obj/machinery/light/source, datum/light_eater)
/obj/machinery/light/floor
	name = "floor light"
