/mob/living/simple_animal/attack_hand(mob/living/carbon/human/user, list/modifiers)
/mob/living/simple_animal/attack_hulk(mob/living/carbon/human/user)
/mob/living/simple_animal/attack_paw(mob/living/carbon/human/user, list/modifiers)
/mob/living/simple_animal/attack_alien(mob/living/carbon/alien/humanoid/user, list/modifiers)
/mob/living/simple_animal/attack_larva(mob/living/carbon/alien/larva/L)
/mob/living/simple_animal/attack_basic_mob(mob/living/basic/user, list/modifiers)
/mob/living/simple_animal/attack_animal(mob/living/simple_animal/user, list/modifiers)
/mob/living/simple_animal/attack_slime(mob/living/simple_animal/slime/M)
/mob/living/simple_animal/attack_drone(mob/living/simple_animal/drone/M)
/mob/living/simple_animal/proc/attack_threshold_check(damage, damagetype = BRUTE, armorcheck = MELEE, actuallydamage = TRUE)
/mob/living/simple_animal/bullet_act(obj/projectile/Proj, def_zone, piercing_hit = FALSE)
/mob/living/simple_animal/ex_act(severity, target, origin)
/mob/living/simple_animal/proc/ex_act_devastate()
/mob/living/simple_animal/proc/ex_act_heavy()
/mob/living/simple_animal/proc/ex_act_light()
/mob/living/simple_animal/blob_act(obj/structure/blob/B)
/mob/living/simple_animal/do_attack_animation(atom/A, visual_effect_icon, used_item, no_effect)
