/mob/living/simple_animal/blind_eyes()
/mob/living/simple_animal/adjust_blindness()
/mob/living/simple_animal/set_blindness()
/mob/living/simple_animal/blur_eyes()
/mob/living/simple_animal/adjust_blurriness()
/mob/living/simple_animal/set_blurriness()
/mob/living/simple_animal/become_blind()
