/mob/dead/observer
	name = "ghost"
	desc = "It's a g-g-g-g-ghooooost!" //jinkies!
/mob/dead/observer/Initialize(mapload)
/mob/dead/observer/proc/dead_tele,
/mob/dead/observer/proc/open_spawners_menu,
/mob/dead/observer/proc/tray_view,
/mob/dead/observer/proc/open_minigames_menu))
	name = body.mind.ghostname
	name = body.mind.name
	name = body.real_name
	name = random_unique_name(gender)
	name = random_unique_name(gender)
/mob/dead/observer/get_photo_description(obj/item/camera/camera)
/mob/dead/observer/narsie_act()
/mob/dead/observer/Destroy()
/mob/dead/observer/update_icon(updates=ALL, new_form)
/mob/proc/brighten_color(input_color)
/mob/proc/ghostize(can_reenter_corpse = TRUE)
/mob/living/ghostize(can_reenter_corpse = TRUE)
/mob/living/verb/ghost()
/mob/camera/verb/ghost()
/mob/dead/observer/Move(NewLoc, direct, glide_size_override = 32)
/mob/dead/observer/forceMove(atom/destination)
/mob/dead/observer/verb/reenter_corpse()
/mob/dead/observer/verb/stay_dead()
/mob/dead/observer/proc/notify_cloning(message, sound, atom/source, flashwindow = TRUE)
/mob/dead/observer/proc/dead_tele()
/mob/dead/observer/verb/follow()
/mob/dead/observer/proc/ManualFollow(atom/movable/target)
/mob/dead/observer/orbit()
/mob/dead/observer/stop_orbit(datum/component/orbiter/orbits)
/mob/dead/observer/verb/jumptomob() //Moves the ghost instead of just changing the ghosts's eye -Nodrak
/mob/dead/observer/verb/change_view_range()
/mob/dead/observer/verb/add_view_range(input as num)
/mob/dead/observer/verb/boo()
/mob/dead/observer/verb/toggle_ghostsee()
/mob/dead/observer/verb/toggle_darkness()
/mob/dead/observer/update_sight()
/proc/updateallghostimages()
/mob/dead/observer/proc/updateghostimages()
/mob/dead/observer/verb/possess()
/mob/dead/observer/pointed(atom/A as mob|obj|turf in view(client.view, src))
/mob/dead/observer/verb/view_manifest()
/mob/dead/observer/MouseDrop(atom/over)
/mob/dead/observer/Topic(href, href_list)
/mob/dead/observer/mind_initialize()
/mob/dead/observer/proc/show_data_huds()
/mob/dead/observer/proc/remove_data_huds()
/mob/dead/observer/verb/toggle_data_huds()
/mob/dead/observer/verb/toggle_health_scan()
/mob/dead/observer/verb/toggle_chem_scan()
/mob/dead/observer/verb/toggle_gas_scan()
/mob/dead/observer/verb/restore_ghost_appearance()
	name = real_name
/mob/dead/observer/proc/set_ghost_appearance()
/mob/dead/observer/canUseTopic(atom/movable/M, be_close=FALSE, no_dexterity=FALSE, no_tk=FALSE, need_hands = FALSE, floor_okay=FALSE)
/mob/dead/observer/is_literate()
/mob/dead/observer/vv_edit_var(var_name, var_value)
/mob/dead/observer/reset_perspective(atom/A)
/mob/dead/observer/proc/cleanup_observe()
/mob/dead/observer/verb/observe()
/mob/dead/observer/proc/do_observe(mob/mob_eye)
/mob/dead/observer/proc/on_observing_z_changed(datum/source, turf/old_turf, turf/new_turf)
/mob/dead/observer/verb/register_pai_candidate()
/mob/dead/observer/proc/register_pai()
/mob/dead/observer/verb/mafia_game_signup()
/mob/dead/observer/proc/mafia_signup()
/mob/dead/observer/CtrlShiftClick(mob/user)
/mob/dead/observer/examine(mob/user)
/mob/dead/observer/examine_more(mob/user)
/mob/dead/observer/proc/set_invisibility(value)
/mob/dead/observer/Process_Spacemove(movement_dir)
/mob/dead/observer/vv_edit_var(var_name, var_value)
/proc/set_observer_default_invisibility(amount, message=null)
/mob/dead/observer/proc/open_spawners_menu()
/mob/dead/observer/proc/open_minigames_menu()
/mob/dead/observer/proc/tray_view()
