/datum/id_trim/centcom
/datum/id_trim/centcom/vip
/datum/id_trim/centcom/custodian
/datum/id_trim/centcom/thunderdome_overseer
/datum/id_trim/centcom/official
/datum/id_trim/centcom/intern
/datum/id_trim/centcom/intern/head
/datum/id_trim/centcom/intern/head/New()
/datum/id_trim/centcom/bartender
/datum/id_trim/centcom/medical_officer
/datum/id_trim/centcom/research_officer
/datum/id_trim/centcom/specops_officer
/datum/id_trim/centcom/specops_officer/New()
/datum/id_trim/centcom/admiral
/datum/id_trim/centcom/admiral/New()
/datum/id_trim/centcom/commander
/datum/id_trim/centcom/commander/New()
/datum/id_trim/centcom/deathsquad
/datum/id_trim/centcom/deathsquad/New()
/datum/id_trim/centcom/ert
/datum/id_trim/centcom/ert/New()
/datum/id_trim/centcom/ert/commander
/datum/id_trim/centcom/ert/commander/New()
/datum/id_trim/centcom/ert/security
/datum/id_trim/centcom/ert/security/New()
/datum/id_trim/centcom/ert/engineer
/datum/id_trim/centcom/ert/engineer/New()
/datum/id_trim/centcom/ert/medical
/datum/id_trim/centcom/ert/medical/New()
/datum/id_trim/centcom/ert/chaplain
/datum/id_trim/centcom/ert/chaplain/New()
/datum/id_trim/centcom/ert/janitor
/datum/id_trim/centcom/ert/janitor/New()
/datum/id_trim/centcom/ert/clown
/datum/id_trim/centcom/ert/clown/New()
