/datum/id_trim/away
/datum/id_trim/away/hotel
/datum/id_trim/away/hotel/security
/datum/id_trim/away/old/sec
/datum/id_trim/away/old/sci
/datum/id_trim/away/old/eng
/datum/id_trim/away/old/apc
/datum/id_trim/away/cat_surgeon
/datum/id_trim/away/hilbert
/datum/id_trim/lifeguard
/datum/id_trim/space_bartender
/datum/id_trim/centcom/corpse/bridge_officer
/datum/id_trim/centcom/corpse/commander
/datum/id_trim/centcom/corpse/private_security
/datum/id_trim/centcom/corpse/private_security/tradepost_officer
/datum/id_trim/centcom/corpse/assault
/datum/id_trim/engioutpost
/datum/id_trim/job/station_engineer/gunner
/datum/id_trim/pirate
/datum/id_trim/pirate/silverscale
/datum/id_trim/pirate/captain
/datum/id_trim/pirate/captain/silverscale
