/datum/id_trim/syndicom
/datum/id_trim/syndicom/crew
/datum/id_trim/syndicom/captain
/datum/id_trim/battlecruiser
/datum/id_trim/battlecruiser/captain
/datum/id_trim/chameleon
/datum/id_trim/chameleon/operative
/datum/id_trim/chameleon/operative/clown
/datum/id_trim/chameleon/operative/clown_leader
/datum/id_trim/chameleon/operative/nuke_leader
