/mob/proc/get_active_held_item()
/mob/proc/get_inactive_held_item()
/mob/proc/get_inactive_hand_index()
/mob/proc/get_item_for_held_index(i)
/mob/proc/held_index_to_dir(i)
/mob/proc/has_hand_for_held_index(i)
/mob/proc/has_active_hand()
/mob/proc/get_empty_held_index_for_side(side = LEFT_HANDS, all = FALSE)
/mob/proc/get_held_items_for_side(side = LEFT_HANDS, all = FALSE)
/mob/proc/get_empty_held_indexes()
/mob/proc/get_held_index_of_item(obj/item/I)
/mob/proc/get_num_held_items()
/mob/proc/is_holding(obj/item/I)
/mob/proc/is_holding_item_of_type(typepath)
/mob/proc/is_holding_tool_quality(quality)
/mob/proc/get_held_index_name(i)
/mob/proc/can_equip(obj/item/I, slot, disable_warning = FALSE, bypass_equip_delay_self = FALSE)
/mob/proc/can_put_in_hand(I, hand_index)
/mob/proc/put_in_hand(obj/item/I, hand_index, forced = FALSE, ignore_anim = TRUE)
/mob/proc/put_in_l_hand(obj/item/I)
/mob/proc/put_in_r_hand(obj/item/I)
/mob/proc/put_in_hand_check(obj/item/I)
/mob/living/put_in_hand_check(obj/item/I)
/mob/proc/put_in_active_hand(obj/item/I, forced = FALSE, ignore_animation = TRUE)
/mob/proc/put_in_inactive_hand(obj/item/I, forced = FALSE)
/mob/proc/put_in_hands(obj/item/I, del_on_fail = FALSE, merge_stacks = TRUE, forced = FALSE)
/mob/proc/drop_all_held_items()
/mob/proc/canUnEquip(obj/item/I, force)
/mob/proc/putItemFromInventoryInHandIfPossible(obj/item/I, hand_index, force_removal = FALSE)
/mob/proc/dropItemToGround(obj/item/I, force = FALSE, silent = FALSE, invdrop = TRUE)
/mob/proc/transferItemToLoc(obj/item/I, newloc = null, force = FALSE, silent = TRUE)
/mob/proc/temporarilyRemoveItemFromInventory(obj/item/I, force = FALSE, idrop = TRUE)
/mob/proc/doUnEquip(obj/item/I, force, newloc, no_move, invdrop = TRUE, silent = FALSE) //Force overrides TRAIT_NODROP for things like wizarditis and admin undress.
/mob/living/proc/get_equipped_items(include_pockets = FALSE)
/mob/living/carbon/human/get_equipped_items(include_pockets = FALSE)
/mob/living/proc/unequip_everything()
/mob/living/carbon/proc/check_obscured_slots(transparent_protection)
/obj/item/proc/equip_to_best_slot(mob/M)
/mob/verb/quick_equip()
/mob/proc/getBackSlot()
/mob/proc/getBeltSlot()
/mob/proc/change_number_of_hands(amt)
/mob/living/carbon/human/change_number_of_hands(amt)
/mob/living/carbon/proc/get_all_gear()
