/mob/living/carbon/proc/monkeyize()
/mob/living/carbon/proc/finish_monkeyize()
/mob/living/carbon/proc/humanize(species = /datum/species/human)
/mob/living/carbon/proc/finish_humanize(species = /datum/species/human)
/mob/proc/AIize(transfer_after = TRUE, client/preference_source, move = TRUE)
/mob/living/carbon/AIize(transfer_after = TRUE, client/preference_source)
/mob/living/carbon/human/AIize(transfer_after = TRUE, client/preference_source)
/mob/proc/Robotize(delete_items = 0, transfer_after = TRUE)
/mob/living/Robotize(delete_items = 0, transfer_after = TRUE)
/mob/living/silicon/robot/proc/replace_banned_cyborg()
/mob/living/carbon/human/proc/Alienize()
/mob/living/carbon/human/proc/slimeize(reproduce as num)
/mob/proc/become_overmind(starting_points = OVERMIND_STARTING_POINTS)
/mob/living/carbon/human/proc/corgize()
/mob/living/carbon/proc/gorillize()
/mob/living/carbon/human/Animalize()
/mob/proc/Animalize()
/mob/proc/safe_animal(MP)
