/obj/item/pda//SKYRAT EDIT - ICON OVERRIDEN BY AESTHETICS - SEE MODULE
	name = "\improper standard PDA"
	desc = "A portable microcomputer by Thinktronic Systems, LTD. Functionality determined by a preprogrammed ROM cartridge."
/obj/item/pda/suicide_act(mob/living/carbon/user)
/obj/item/pda/examine(mob/user)
/obj/item/pda/Initialize(mapload)
/obj/item/pda/Destroy()
/obj/item/pda/equipped(mob/user, slot)
/obj/item/pda/Exited(atom/movable/gone, direction)
/obj/item/pda/proc/update_label()
	name = "PDA-[owner] ([ownjob])" //Name generalisation
/obj/item/pda/GetAccess()
/obj/item/pda/get_id_examine_strings(mob/user)
/obj/item/pda/GetID()
/obj/item/pda/RemoveID()
/obj/item/pda/InsertID(obj/item/inserting_item)
/obj/item/pda/update_overlays()
/obj/item/pda/MouseDrop(mob/over, src_location, over_location)
/obj/item/pda/attack_self_tk(mob/user)
/obj/item/pda/interact(mob/user)
/obj/item/pda/Topic(href, href_list)
/obj/item/pda/proc/remove_id(mob/user)
/obj/item/pda/proc/do_remove_id(mob/user)
/obj/item/pda/proc/msg_input(mob/living/U = usr, rigged = FALSE)
/obj/item/pda/proc/send_message(mob/living/user, list/obj/item/pda/targets, everyone = FALSE, rigged = FALSE, fakename, fakejob)
/obj/item/pda/proc/receive_message(datum/signal/subspace/messaging/pda/signal)
/obj/item/pda/proc/send_to_all(mob/living/U)
/obj/item/pda/proc/create_message(mob/living/U, obj/item/pda/P)
/obj/item/pda/AltClick(mob/user)
/obj/item/pda/CtrlClick(mob/user)
/obj/item/pda/CtrlShiftClick(mob/user)
/obj/item/pda/verb/verb_toggle_light()
/obj/item/pda/verb/verb_remove_id()
/obj/item/pda/verb/verb_remove_pen()
/obj/item/pda/verb/verb_eject_cart()
/obj/item/pda/proc/toggle_light(mob/user)
/obj/item/pda/proc/on_light_eater(obj/item/pda/source, datum/light_eater)
/obj/item/pda/proc/remove_pen(mob/user)
/obj/item/pda/proc/eject_cart(mob/user)
/obj/item/pda/proc/id_check(mob/user, obj/item/card/id/I)
/obj/item/pda/proc/insert_id(obj/item/card/id/inserting_id, mob/user)
/obj/item/pda/pre_attack(obj/target, mob/living/user, params)
/obj/item/pda/attackby(obj/item/C, mob/user, params)
/obj/item/pda/attack(mob/living/carbon/C, mob/living/user)
/obj/item/pda/afterattack(atom/A as mob|obj|turf|area, mob/user, proximity)
/obj/item/pda/proc/explode(mob/target, mob/bomber, from_message_menu = FALSE)
/obj/item/pda/ai/verb/cmd_toggle_pda_receiver()
/obj/item/pda/ai/verb/cmd_toggle_pda_silent()
/mob/living/silicon/proc/cmd_send_pdamesg(mob/user)
/mob/living/silicon/proc/cmd_show_message_log(mob/user)
/obj/item/pda/emp_act(severity)
/obj/item/pda/proc/emp_end()
/proc/get_viewable_pdas(sort_by_job = FALSE)
/obj/item/pda/proc/pda_no_detonate()
/obj/item/pda/proc/get_types_to_preload()
/obj/item/pda/proc/display_pda()
/obj/item/pda/proc/cloak_pda()
