/mob/dead/new_player
/mob/dead/new_player/Initialize(mapload)
/mob/dead/new_player/Destroy()
/mob/dead/new_player/prepare_huds()
/mob/dead/new_player/Topic(href, href_list[])
/mob/dead/new_player/proc/make_me_an_observer()
/proc/get_job_unavailable_error_message(retval, jobtitle)
/mob/dead/new_player/proc/IsJobUnavailable(rank, latejoin = FALSE)
/mob/dead/new_player/proc/AttemptLateSpawn(rank)
/mob/dead/new_player/proc/AddEmploymentContract(mob/living/carbon/human/employee)
/mob/dead/new_player/proc/LateChoices()
/mob/dead/new_player/proc/create_character(atom/destination)
/mob/dead/new_player/proc/transfer_character()
/mob/dead/new_player/proc/ViewManifest()
/mob/dead/new_player/Move()
/mob/dead/new_player/proc/check_preferences()
/mob/dead/new_player/proc/register_for_interview()
