/mob/dead/new_player/proc/handle_player_polling()
/mob/dead/new_player/proc/poll_player(datum/poll_question/poll)
/mob/dead/new_player/proc/poll_player_option(datum/poll_question/poll)
/mob/dead/new_player/proc/poll_player_text(datum/poll_question/poll)
/mob/dead/new_player/proc/poll_player_rating(datum/poll_question/poll)
/mob/dead/new_player/proc/poll_player_multi(datum/poll_question/poll)
/mob/dead/new_player/proc/poll_player_irv(datum/poll_question/poll)
/mob/dead/new_player/proc/vote_on_poll_handler(datum/poll_question/poll, href_list)
/mob/dead/new_player/proc/vote_on_poll_option(datum/poll_question/poll, href_list, admin_rank, sql_poll_id, vote_id)
/mob/dead/new_player/proc/vote_on_poll_text(href_list, admin_rank, sql_poll_id, vote_id)
/mob/dead/new_player/proc/vote_on_poll_rating(datum/poll_question/poll, list/href_list, admin_rank, sql_poll_id)
/mob/dead/new_player/proc/vote_on_poll_multi(datum/poll_question/poll, list/href_list, admin_rank, sql_poll_id)
/mob/dead/new_player/proc/vote_on_poll_irv(datum/poll_question/poll, list/href_list, admin_rank, sql_poll_id)
