/datum/foreign_calendar
/datum/foreign_calendar/New(yyyy, mm, dd)
/datum/foreign_calendar/proc/set_date()
/datum/foreign_calendar/proc/gregorian_to_jd(year, month, day)
/datum/foreign_calendar/proc/leap_gregorian(year)
/datum/foreign_calendar/proc/realtime_to_jd(realtime)
/datum/foreign_calendar/islamic/proc/leap_islamic(yr)
/datum/foreign_calendar/islamic/set_date()
/datum/foreign_calendar/islamic/proc/islamic_to_jd(year, month, day)
/datum/foreign_calendar/hebrew/proc/hebrew_leap(year)
/datum/foreign_calendar/hebrew/proc/hebrew_to_jd(year, month, day)
/datum/foreign_calendar/hebrew/set_date(jd)
/datum/foreign_calendar/hebrew/proc/hebrew_year_months(year)
/datum/foreign_calendar/hebrew/proc/hebrew_delay_1(year)
/datum/foreign_calendar/hebrew/proc/hebrew_delay_2(year)
/datum/foreign_calendar/hebrew/proc/hebrew_year_days(year)
/datum/foreign_calendar/hebrew/proc/hebrew_month_days(year, month)
