/proc/is_ic_filtered(message)
/proc/is_ic_filtered_for_pdas(message)
/proc/is_ooc_filtered(message)
/proc/is_soft_ic_filtered(message)
/proc/is_soft_ic_filtered_for_pdas(message)
/proc/is_soft_ooc_filtered(message)
