/datum/heap
/datum/heap/New(compare)
/datum/heap/Destroy(force, ...)
/datum/heap/proc/is_empty()
/datum/heap/proc/insert(atom/A)
/datum/heap/proc/pop()
/datum/heap/proc/swim(index)
/datum/heap/proc/sink(index)
/datum/heap/proc/get_greater_child(index)
/datum/heap/proc/resort(atom/A)
/datum/heap/proc/List()
