/datum/controller/subsystem/ticker/proc/poll_hearts()
/datum/controller/subsystem/ticker/proc/handle_hearts()
/mob/proc/query_heart(attempt=1)
	name = shuffle(name_checks)
/mob/proc/receive_heart(mob/heart_sender, duration = 24 HOURS, instant = FALSE)
