/atom/proc/calculate_adjacencies()
/atom/movable/calculate_adjacencies()
/atom/proc/smooth_icon()
/atom/proc/corners_diagonal_smooth(adjacencies)
/atom/proc/corners_cardinal_smooth(adjacencies)
/atom/proc/find_type_in_direction(direction)
/atom/proc/bitmask_smooth()
/atom/proc/set_smoothed_icon_state(new_junction)
/turf/closed/set_smoothed_icon_state(new_junction)
/turf/open/floor/set_smoothed_icon_state(new_junction)
/proc/smooth_zlevel(zlevel, now = FALSE)
/atom/proc/clear_smooth_overlays()
/atom/proc/replace_smooth_overlays(nw, ne, sw, se)
/proc/reverse_ndir(ndir)
/turf/closed/wall/smooth
	name = "smooth wall"
