/proc/chem_recipes_do_conflict(datum/chemical_reaction/r1, datum/chemical_reaction/r2)
/proc/get_chemical_reaction(id)
/proc/remove_chemical_reaction(datum/chemical_reaction/R)
/proc/add_chemical_reaction(datum/chemical_reaction/R)
/datum/reagents/proc/create_foam(foamtype,foam_volume,metaltype = 0,notification = null)
/proc/convert_ph_to_readable_color(pH)
/proc/get_reagent_type_from_product_string(string)
/proc/find_reagent(input)
/proc/find_reagent_object_from_type(input)
/proc/get_random_reagent_id()
/proc/get_chem_id(chem_name)
/proc/get_recipe_from_reagent_product(input_type)
/proc/reagent_paths_list_to_text(list/reagents, addendum)
