/datum/controller/subsystem/ticker/proc/gather_roundend_feedback()
	name = "Unknown Human" //Monkeymen and other mindless corpses
/datum/controller/subsystem/ticker/proc/gather_antag_data()
/datum/controller/subsystem/ticker/proc/record_nuke_disk_location()
/datum/controller/subsystem/ticker/proc/gather_newscaster()
/datum/controller/subsystem/ticker/proc/HandleRandomHardcoreScore(client/player_client)
/datum/controller/subsystem/ticker/proc/declare_completion()
/datum/controller/subsystem/ticker/proc/standard_reboot()
/datum/controller/subsystem/ticker/proc/build_roundend_report()
/datum/controller/subsystem/ticker/proc/survivor_report(popcount)
/client/proc/roundend_report_file()
/datum/controller/subsystem/ticker/proc/log_roundend_report()
/datum/controller/subsystem/ticker/proc/show_roundend_report(client/C, report_type = null)
/datum/controller/subsystem/ticker/proc/personal_report(client/C, popcount)
/datum/controller/subsystem/ticker/proc/display_report(popcount)
/datum/controller/subsystem/ticker/proc/law_report()
/datum/controller/subsystem/ticker/proc/goal_report()
/datum/controller/subsystem/ticker/proc/market_report()
/datum/controller/subsystem/ticker/proc/award_service(award)
/datum/controller/subsystem/ticker/proc/medal_report()
/datum/controller/subsystem/ticker/proc/hardcore_random_report()
/datum/controller/subsystem/ticker/proc/antag_report()
/proc/cmp_antag_category(datum/antagonist/A,datum/antagonist/B)
/datum/controller/subsystem/ticker/proc/give_show_report_button(client/C)
/datum/action/report
	name = "Show roundend report"
/datum/action/report/Trigger()
/datum/action/report/IsAvailable()
/datum/action/report/Topic(href,href_list)
/proc/printplayer(datum/mind/ply, fleecheck)
/proc/printplayerlist(list/players,fleecheck)
/proc/printobjectives(list/objectives)
/datum/controller/subsystem/ticker/proc/save_admin_data()
/datum/controller/subsystem/ticker/proc/update_everything_flag_in_db()
