/datum/looping_sound/showering
/datum/looping_sound/supermatter
/datum/looping_sound/destabilized_crystal
/datum/looping_sound/hypertorus
/datum/looping_sound/generator
/datum/looping_sound/deep_fryer
/datum/looping_sound/grill
/datum/looping_sound/oven
/datum/looping_sound/deep_fryer
/datum/looping_sound/microwave
/datum/looping_sound/jackpot
/datum/looping_sound/server
/datum/looping_sound/computer
/datum/looping_sound/gravgen
