/turf
/turf/open
/turf/open/Initialize(mapload)
/turf/open/Destroy()
/turf/open/assume_air(datum/gas_mixture/giver) //use this for machines to adjust air
/turf/open/remove_air(amount)
/turf/open/proc/copy_air_with_tile(turf/open/target_turf)
/turf/open/proc/copy_air(datum/gas_mixture/copy)
/turf/return_air()
/turf/open/return_air()
/turf/open/return_analyzable_air()
/turf/should_atmos_process(datum/gas_mixture/air, exposed_temperature)
/turf/atmos_expose(datum/gas_mixture/air, exposed_temperature)
/turf/proc/burn()
/turf/open/burn()
/turf/temperature_expose(datum/gas_mixture/air, exposed_temperature)
/turf/open/temperature_expose(datum/gas_mixture/air, exposed_temperature)
/turf/proc/archive()
/turf/open/archive()
/turf/open/proc/update_visuals()
/proc/typecache_of_gases_with_no_overlays()
/turf/proc/process_cell(fire_count)
/turf/open/process_cell(fire_count)
/turf/open/proc/consider_pressure_difference(turf/target_turf, difference)
/turf/open/proc/high_pressure_movements()
/atom/movable
/atom/movable/proc/experience_pressure_difference(pressure_difference, direction, pressure_resistance_prob_delta = 0)
/datum/excited_group
/datum/excited_group/New()
/datum/excited_group/proc/add_turf(turf/open/target_turf)
/datum/excited_group/proc/merge_groups(datum/excited_group/target_group)
/datum/excited_group/proc/reset_cooldowns()
/datum/excited_group/proc/self_breakdown(roundstart = FALSE, poke_turfs = FALSE)
/datum/excited_group/proc/dismantle()
/datum/excited_group/proc/garbage_collect()
/datum/excited_group/proc/display_turfs()
/datum/excited_group/proc/hide_turfs()
/datum/excited_group/proc/display_turf(turf/thing)
/turf/proc/conductivity_directions()
/turf/open/conductivity_directions()
/turf/proc/neighbor_conduct_with_src(turf/open/other)
/turf/open/neighbor_conduct_with_src(turf/other)
/turf/proc/super_conduct()
/turf/proc/finish_superconduction(temp = temperature)
/turf/open/finish_superconduction()
/turf/proc/consider_superconductivity(starting)
/turf/open/consider_superconductivity(starting)
/turf/closed/consider_superconductivity(starting)
/turf/proc/radiate_to_spess() //Radiate excess tile heat to space
/turf/open/proc/temperature_share_open_to_solid(turf/sharer)
/turf/proc/share_temperature_mutual_solid(turf/sharer, conduction_coefficient) //This is all just heat sharing, don't get freaked out
