/mob/living/silicon/proc/show_laws() //Redefined in ai/laws.dm and robot/laws.dm
/mob/living/silicon/proc/laws_sanity_check()
/mob/living/silicon/proc/log_current_laws()
/mob/living/silicon/proc/deadchat_lawchange()
/mob/living/silicon/proc/post_lawchange(announce = TRUE)
/mob/living/silicon/proc/set_zeroth_law(law, law_borg, announce = TRUE)
/mob/living/silicon/proc/add_inherent_law(law, announce = TRUE)
/mob/living/silicon/proc/clear_inherent_laws(announce = TRUE)
/mob/living/silicon/proc/add_supplied_law(number, law, announce = TRUE)
/mob/living/silicon/proc/clear_supplied_laws(announce = TRUE)
/mob/living/silicon/proc/add_ion_law(law, announce = TRUE)
/mob/living/silicon/proc/add_hacked_law(law, announce = TRUE)
/mob/living/silicon/proc/replace_random_law(law, groups, announce = TRUE)
/mob/living/silicon/proc/shuffle_laws(list/groups, announce = TRUE)
/mob/living/silicon/proc/remove_law(number, announce = TRUE)
/mob/living/silicon/proc/clear_ion_laws(announce = TRUE)
/mob/living/silicon/proc/clear_hacked_laws(announce = TRUE)
/mob/living/silicon/proc/make_laws()
/mob/living/silicon/proc/clear_zeroth_law(force, announce = TRUE)
