/mob/living/silicon/grippedby(mob/living/user, instant = FALSE)
/mob/living/silicon/get_ear_protection()//no ears
/mob/living/silicon/attack_alien(mob/living/carbon/alien/humanoid/user, list/modifiers)
/mob/living/silicon/attack_animal(mob/living/simple_animal/user, list/modifiers)
/mob/living/silicon/attack_paw(mob/living/user, list/modifiers)
/mob/living/silicon/attack_larva(mob/living/carbon/alien/larva/L)
/mob/living/silicon/attack_hulk(mob/living/carbon/human/user)
/mob/living/silicon/attack_hand(mob/living/carbon/human/user, list/modifiers)
/mob/living/silicon/attack_drone(mob/living/simple_animal/drone/M)
/mob/living/silicon/electrocute_act(shock_damage, source, siemens_coeff = 1, flags = NONE)
/mob/living/silicon/emp_act(severity)
/mob/living/silicon/bullet_act(obj/projectile/Proj, def_zone, piercing_hit = FALSE)
/mob/living/silicon/flash_act(intensity = 1, override_blindness_check = 0, affect_silicon = 0, visual = 0, type = /atom/movable/screen/fullscreen/flash/static, length = 25)
