/datum/customer_data
/datum/customer_data/New()
	name = world.file2list(prefix_file)
/datum/customer_data/proc/can_use(datum/venue/venue)
/datum/customer_data/proc/get_order(datum/venue/venue)
/datum/customer_data/proc/get_overlays(mob/living/simple_animal/robot_customer/customer)
/datum/customer_data/proc/get_underlays(mob/living/simple_animal/robot_customer/customer)
/datum/customer_data/american
/obj/item/food/burger/plain = 25,
/obj/item/food/burger/cheese = 15,
/obj/item/food/burger/superbite = 1,
/obj/item/food/fries = 10,
/obj/item/food/cheesyfries = 6,
/obj/item/food/pie/applepie = 4,
/obj/item/food/pie/pumpkinpie = 2,
/obj/item/food/hotdog = 8,
/obj/item/food/pizza/pineapple = 1,
/obj/item/food/burger/baconburger = 10,
/obj/item/food/pancakes = 4,
/obj/item/food/eggsausage = 5,
/datum/reagent/consumable/ethanol/b52 = 6,
/datum/reagent/consumable/ethanol/manhattan = 3,
/datum/reagent/consumable/ethanol/atomicbomb = 1,
/datum/reagent/consumable/ethanol/beer = 25,
/datum/customer_data/italian
/obj/item/food/spaghetti/pastatomato = 20,
/obj/item/food/spaghetti/copypasta = 6,
/obj/item/food/spaghetti/meatballspaghetti = 4,
/obj/item/food/spaghetti/butternoodles = 4,
/obj/item/food/pizza/vegetable = 2,
/obj/item/food/pizza/mushroom = 2,
/obj/item/food/pizza/meat = 2,
/obj/item/food/pizza/margherita = 2,
/obj/item/food/lasagna = 4,
/obj/item/food/cannoli = 3,
/obj/item/food/salad/risotto =5,
/obj/item/food/eggplantparm = 3,
/obj/item/food/cornuto = 2,
/datum/reagent/consumable/ethanol/fanciulli = 5,
/datum/reagent/consumable/ethanol/branca_menta = 3,
/datum/reagent/consumable/ethanol/beer = 5,
/datum/reagent/consumable/lemonade = 8,
/datum/reagent/consumable/ethanol/godfather = 5,
/datum/reagent/consumable/ethanol/wine = 3,
/datum/reagent/consumable/ethanol/grappa = 3,
/datum/reagent/consumable/ethanol/amaretto = 5,
/datum/customer_data/french
/obj/item/food/baguette = 20,
/obj/item/food/garlicbread = 5,
/obj/item/food/soup/onion = 4,
/obj/item/food/pie/berryclafoutis = 2,
/obj/item/food/omelette = 15,
/datum/reagent/consumable/ethanol/champagne = 10,
/datum/reagent/consumable/ethanol/cognac = 5,
/datum/reagent/consumable/ethanol/mojito = 5,
/datum/reagent/consumable/ethanol/sidecar = 5,
/datum/reagent/consumable/ethanol/between_the_sheets = 4,
/datum/reagent/consumable/ethanol/beer = 5,
/datum/reagent/consumable/ethanol/wine = 5,
/datum/customer_data/french/get_overlays(mob/living/simple_animal/robot_customer/customer)
/datum/customer_data/japanese
/obj/item/food/tofu = 5,
/obj/item/food/breadslice/plain = 5,
/obj/item/food/soup/miso = 10,
/obj/item/food/soup/vegetable = 4,
/obj/item/food/sashimi = 4,
/obj/item/food/chawanmushi = 4,
/obj/item/food/muffin/berry = 2,
/obj/item/food/beef_stroganoff = 2,
/datum/reagent/consumable/ethanol/sake = 8,
/datum/reagent/consumable/cafe_latte = 6,
/datum/reagent/consumable/ethanol/aloe = 6,
/datum/reagent/consumable/chocolatepudding = 4,
/datum/reagent/consumable/tea = 4,
/datum/reagent/consumable/cherryshake = 1,
/datum/reagent/consumable/ethanol/bastion_bourbon = 1,
/datum/customer_data/japanese/get_overlays(mob/living/simple_animal/robot_customer/customer)
/datum/customer_data/japanese/salaryman
/obj/item/food/tofu = 5,
/obj/item/food/soup/miso = 6,
/obj/item/food/soup/vegetable = 4,
/obj/item/food/sashimi = 4,
/obj/item/food/chawanmushi = 4,
/obj/item/food/meatbun = 4,
/obj/item/food/beef_stroganoff = 2,
/datum/reagent/consumable/ethanol/beer = 14,
/datum/reagent/consumable/ethanol/sake = 9,
/datum/reagent/consumable/cafe_latte = 3,
/datum/reagent/consumable/coffee = 3,
/datum/reagent/consumable/soy_latte = 3,
/datum/reagent/consumable/ethanol/atomicbomb = 1,
/datum/customer_data/moth
/obj/item/clothing/head/chefhat = 3,
/obj/item/clothing/shoes/sneakers/black = 3,
/obj/item/clothing/gloves/color/black = 1,
/datum/customer_data/moth/can_use(datum/venue/venue)
/datum/customer_data/moth/proc/get_dynamic_order(datum/venue/venue)
/datum/customer_data/moth/proc/get_wings(mob/living/simple_animal/robot_customer/customer)
/datum/customer_data/moth/get_underlays(mob/living/simple_animal/robot_customer/customer)
/datum/customer_data/moth/get_overlays(mob/living/simple_animal/robot_customer/customer)
/datum/customer_data/moth/get_order(datum/venue/venue)
/datum/customer_data/mexican
/obj/item/food/taco/plain = 25,
/obj/item/food/taco = 15,
/obj/item/food/burrito = 15,
/obj/item/food/fuegoburrito = 1,
/obj/item/food/cheesyburrito = 4,
/obj/item/food/nachos = 10,
/obj/item/food/cheesynachos = 6,
/obj/item/food/pie/dulcedebatata = 2,
/obj/item/food/cubannachos = 3,
/obj/item/food/stuffedlegion = 1,
/datum/reagent/consumable/ethanol/whiskey = 6,
/datum/reagent/consumable/ethanol/tequila = 20,
/datum/reagent/consumable/ethanol/tequila_sunrise = 1,
/datum/reagent/consumable/ethanol/beer = 15,
/datum/reagent/consumable/ethanol/patron = 5,
/datum/reagent/consumable/ethanol/brave_bull = 5,
/datum/reagent/consumable/ethanol/margarita = 8,
/datum/customer_data/british
/obj/item/food/fishandchips = 10,
/obj/item/food/soup/stew = 10,
/obj/item/food/salad/ricepudding = 5,
/obj/item/food/grilled_cheese_sandwich = 5,
/obj/item/food/pie/meatpie = 5,
/obj/item/food/benedict = 5,
/obj/item/food/full_english = 2,
/obj/item/food/soup/indian_curry = 3,
/obj/item/food/beef_wellington_slice = 2,
/datum/reagent/consumable/ethanol/ale = 10,
/datum/reagent/consumable/ethanol/beer = 10,
/datum/reagent/consumable/ethanol/gin = 5,
/datum/reagent/consumable/ethanol/hcider = 10,
/datum/reagent/consumable/ethanol/alliescocktail = 5,
/datum/reagent/consumable/ethanol/martini = 5,
/datum/reagent/consumable/ethanol/gintonic = 5,
/datum/reagent/consumable/tea = 10,
/datum/customer_data/british/gent
/datum/customer_data/british/bobby
/datum/customer_data/malfunction
/obj/item/toy/crayon/red = 1,
/obj/item/toy/crayon/orange = 1,
/obj/item/toy/crayon/yellow = 1,
/obj/item/toy/crayon/green = 1,
/obj/item/toy/crayon/blue = 1,
/obj/item/toy/crayon/purple = 1,
/obj/item/food/canned/peaches/maint = 6,
/datum/reagent/consumable/failed_reaction = 1,
/datum/reagent/spraytan = 1,
/datum/reagent/reaction_agent/basic_buffer = 1,
/datum/reagent/reaction_agent/acidic_buffer = 1,
