/datum/controller/configuration
	name = "Configuration"
/datum/controller/configuration/proc/admin_reload()
/datum/controller/configuration/proc/Load(_directory)
/datum/controller/configuration/proc/full_wipe()
/datum/controller/configuration/Destroy()
/datum/controller/configuration/proc/InitEntries()
/datum/controller/configuration/proc/RemoveEntry(datum/config_entry/CE)
/datum/controller/configuration/proc/LoadEntries(filename, list/stack = list())
/datum/controller/configuration/can_vv_get(var_name)
/datum/controller/configuration/vv_edit_var(var_name, var_value)
/datum/controller/configuration/stat_entry(msg)
/datum/controller/configuration/proc/Get(entry_type)
/datum/controller/configuration/proc/Set(entry_type, new_val)
/datum/controller/configuration/proc/LoadMOTD()
/datum/controller/configuration/proc/LoadPolicy()
/datum/controller/configuration/proc/loadmaplist(filename)
/datum/controller/configuration/proc/LoadChatFilter()
/datum/controller/configuration/proc/load_legacy_chat_filter()
/datum/controller/configuration/proc/update_chat_filter_regexes()
/datum/controller/configuration/proc/try_extract_from_word_filter(list/word_filter, key)
/datum/controller/configuration/proc/compile_filter_regex(list/banned_words)
/datum/controller/configuration/proc/DelayedMessageAdmins(text)
