/datum/chemical_reaction/drink
/datum/chemical_reaction/drink/goldschlager
/datum/chemical_reaction/drink/patron
/datum/chemical_reaction/drink/bilk
/datum/chemical_reaction/drink/icetea
/datum/chemical_reaction/drink/icecoffee
/datum/chemical_reaction/drink/hoticecoffee
/datum/chemical_reaction/drink/nuka_cola
/datum/chemical_reaction/drink/moonshine
/datum/chemical_reaction/drink/wine
/datum/chemical_reaction/drink/spacebeer
/datum/chemical_reaction/drink/vodka
/datum/chemical_reaction/drink/kahlua
/datum/chemical_reaction/drink/gin_tonic
/datum/chemical_reaction/drink/rum_coke
/datum/chemical_reaction/drink/cuba_libre
/datum/chemical_reaction/drink/martini
/datum/chemical_reaction/drink/vodkamartini
/datum/chemical_reaction/drink/white_russian
/datum/chemical_reaction/drink/whiskey_cola
/datum/chemical_reaction/drink/screwdriver
/datum/chemical_reaction/drink/bloody_mary
/datum/chemical_reaction/drink/gargle_blaster
/datum/chemical_reaction/drink/brave_bull
/datum/chemical_reaction/drink/tequila_sunrise
/datum/chemical_reaction/drink/toxins_special
/datum/chemical_reaction/drink/beepsky_smash
/datum/chemical_reaction/drink/doctor_delight
/datum/chemical_reaction/drink/irish_cream
/datum/chemical_reaction/drink/manly_dorf
/datum/chemical_reaction/drink/greenbeer
/datum/chemical_reaction/drink/greenbeer2 //apparently there's no other way to do this
/datum/chemical_reaction/drink/hooch
/datum/chemical_reaction/drink/irish_coffee
/datum/chemical_reaction/drink/b52
/datum/chemical_reaction/drink/atomicbomb
/datum/chemical_reaction/drink/margarita
/datum/chemical_reaction/drink/longislandicedtea
/datum/chemical_reaction/drink/threemileisland
/datum/chemical_reaction/drink/whiskeysoda
/datum/chemical_reaction/drink/black_russian
/datum/chemical_reaction/drink/hiveminderaser
/datum/chemical_reaction/drink/manhattan
/datum/chemical_reaction/drink/manhattan_proj
/datum/chemical_reaction/drink/vodka_tonic
/datum/chemical_reaction/drink/gin_fizz
/datum/chemical_reaction/drink/bahama_mama
/datum/chemical_reaction/drink/singulo
/datum/chemical_reaction/drink/alliescocktail
/datum/chemical_reaction/drink/demonsblood
/datum/chemical_reaction/drink/booger
/datum/chemical_reaction/drink/antifreeze
/datum/chemical_reaction/drink/barefoot
/datum/chemical_reaction/drink/moscow_mule
/datum/chemical_reaction/drink/painkiller
/datum/chemical_reaction/drink/pina_colada
/datum/chemical_reaction/drink/sbiten
/datum/chemical_reaction/drink/red_mead
/datum/chemical_reaction/drink/mead
/datum/chemical_reaction/drink/iced_beer
/datum/chemical_reaction/drink/grog
/datum/chemical_reaction/drink/soy_latte
/datum/chemical_reaction/drink/cafe_latte
/datum/chemical_reaction/drink/acidspit
/datum/chemical_reaction/drink/amasec
/datum/chemical_reaction/drink/changelingsting
/datum/chemical_reaction/drink/aloe
/datum/chemical_reaction/drink/andalusia
/datum/chemical_reaction/drink/neurotoxin
/datum/chemical_reaction/drink/snowwhite
/datum/chemical_reaction/drink/irishcarbomb
/datum/chemical_reaction/drink/syndicatebomb
/datum/chemical_reaction/drink/erikasurprise
/datum/chemical_reaction/drink/devilskiss
/datum/chemical_reaction/drink/hippiesdelight
/datum/chemical_reaction/drink/bananahonk
/datum/chemical_reaction/drink/silencer
/datum/chemical_reaction/drink/driestmartini
/datum/chemical_reaction/drink/thirteenloko
/datum/chemical_reaction/drink/cherryshake
/datum/chemical_reaction/drink/bluecherryshake
/datum/chemical_reaction/drink/drunkenblumpkin
/datum/chemical_reaction/drink/pumpkin_latte
/datum/chemical_reaction/drink/gibbfloats
/datum/chemical_reaction/drink/triple_citrus
/datum/chemical_reaction/drink/grape_soda
/datum/chemical_reaction/drink/grappa
/datum/chemical_reaction/drink/whiskey_sour
/datum/chemical_reaction/drink/fetching_fizz
/datum/chemical_reaction/drink/hearty_punch
/datum/chemical_reaction/drink/bacchus_blessing
/datum/chemical_reaction/drink/lemonade
/datum/chemical_reaction/drink/arnold_palmer
/datum/chemical_reaction/drink/chocolate_milk
/datum/chemical_reaction/drink/hot_coco
/datum/chemical_reaction/drink/hot_coco_from_chocolate_milk
/datum/chemical_reaction/drink/coffee
/datum/chemical_reaction/drink/tea
/datum/chemical_reaction/drink/eggnog
/datum/chemical_reaction/drink/narsour
/datum/chemical_reaction/drink/quadruplesec
/datum/chemical_reaction/drink/grasshopper
/datum/chemical_reaction/drink/stinger
/datum/chemical_reaction/drink/quintuplesec
/datum/chemical_reaction/drink/bastion_bourbon
/datum/chemical_reaction/drink/squirt_cider
/datum/chemical_reaction/drink/fringe_weaver
/datum/chemical_reaction/drink/sugar_rush
/datum/chemical_reaction/drink/crevice_spike
/datum/chemical_reaction/drink/sake
/datum/chemical_reaction/drink/peppermint_patty
/datum/chemical_reaction/drink/alexander
/datum/chemical_reaction/drink/sidecar
/datum/chemical_reaction/drink/between_the_sheets
/datum/chemical_reaction/drink/kamikaze
/datum/chemical_reaction/drink/mojito
/datum/chemical_reaction/drink/fernet_cola
/datum/chemical_reaction/drink/fanciulli
/datum/chemical_reaction/drink/branca_menta
/datum/chemical_reaction/drink/blank_paper
/datum/chemical_reaction/drink/wizz_fizz
/datum/chemical_reaction/drink/bug_spray
/datum/chemical_reaction/drink/jack_rose
/datum/chemical_reaction/drink/turbo
/datum/chemical_reaction/drink/old_timer
/datum/chemical_reaction/drink/rubberneck
/datum/chemical_reaction/drink/duplex
/datum/chemical_reaction/drink/trappist
/datum/chemical_reaction/drink/cream_soda
/datum/chemical_reaction/drink/blazaam
/datum/chemical_reaction/drink/planet_cracker
/datum/chemical_reaction/drink/red_queen
/datum/chemical_reaction/drink/mauna_loa
/datum/chemical_reaction/drink/godfather
/datum/chemical_reaction/drink/godmother
/datum/chemical_reaction/drink/amaretto_alexander
/datum/chemical_reaction/drink/ginger_amaretto
/datum/chemical_reaction/drink/mushroom_tea
/datum/chemical_reaction/drink/mushi_kombucha
/datum/chemical_reaction/drink/sea_breeze
/datum/chemical_reaction/drink/white_tiziran
/datum/chemical_reaction/drink/drunken_espatier
/datum/chemical_reaction/drink/protein_blend
/datum/chemical_reaction/drink/triumphal_arch
/datum/chemical_reaction/drink/the_juice
/datum/chemical_reaction/drink/admiralty
/datum/chemical_reaction/drink/long_haul
/datum/chemical_reaction/drink/long_john_silver
/datum/chemical_reaction/drink/tropical_storm
/datum/chemical_reaction/drink/dark_n_stormy
/datum/chemical_reaction/drink/salt_and_swell
/datum/chemical_reaction/drink/tiltaellen
/datum/chemical_reaction/drink/tich_toch
/datum/chemical_reaction/drink/toechtauese_syrup
