/datum/food_processor_process
/datum/food_processor_process/meat
/obj/item/food/meat/slab/corgi,
/obj/item/food/meat/slab/xeno,
/obj/item/food/meat/slab/bear,
/obj/item/food/meat/slab/chicken)
/datum/food_processor_process/cutlet
/obj/item/food/meat/cutlet/xeno,
/obj/item/food/meat/cutlet/bear,
/obj/item/food/meat/cutlet/chicken)
/datum/food_processor_process/meat/human
/datum/food_processor_process/cutlet/human
/datum/food_processor_process/meat/corgi
/datum/food_processor_process/meat/xeno
/datum/food_processor_process/cutlet/xeno
/datum/food_processor_process/meat/bear
/datum/food_processor_process/cutlet/bear
/datum/food_processor_process/meat/chicken
/datum/food_processor_process/cutlet/chicken
/datum/food_processor_process/bacon
/datum/food_processor_process/potatowedges
/datum/food_processor_process/sweetpotato
/datum/food_processor_process/potato
/datum/food_processor_process/carrot
/datum/food_processor_process/soybeans
/datum/food_processor_process/spaghetti
/datum/food_processor_process/corn
/datum/food_processor_process/tortilla
/datum/food_processor_process/parsnip
/datum/food_processor_process/mob/slime
/datum/food_processor_process/towercap
