/mob/living/silicon/robot/get_active_held_item()
/obj/item/proc/cyborg_unequip(mob/user)
/mob/living/silicon/robot/proc/activate_module(obj/item/item_module)
/mob/living/silicon/robot/proc/equip_module_to_slot(obj/item/item_module, module_num)
/mob/living/silicon/robot/proc/unequip_module_from_slot(obj/item/item_module, module_num)
/mob/living/silicon/robot/proc/break_cyborg_slot(module_num)
/mob/living/silicon/robot/proc/break_all_cyborg_slots()
/mob/living/silicon/robot/proc/repair_cyborg_slot(module_num)
/mob/living/silicon/robot/proc/repair_all_cyborg_slots()
/mob/living/silicon/robot/proc/observer_screen_update(obj/item/item_module, add = TRUE)
/mob/living/silicon/robot/proc/uneq_active()
/mob/living/silicon/robot/proc/uneq_all()
/mob/living/silicon/robot/proc/activated(obj/item/item_module)
/mob/living/silicon/robot/proc/is_invalid_module_number(module_num, check_all_slots = FALSE)
/mob/living/silicon/robot/proc/get_selected_module()
/mob/living/silicon/robot/proc/select_module(module_num)
/mob/living/silicon/robot/proc/deselect_module(module_num)
/mob/living/silicon/robot/proc/toggle_module(module_num)
/mob/living/silicon/robot/proc/cycle_modules()
/mob/living/silicon/robot/swap_hand()
/mob/living/silicon/robot/can_hold_items(obj/item/I)
