/mob/living/silicon/robot/Life(delta_time = SSMOBS_DT, times_fired)
/mob/living/silicon/robot/proc/handle_robot_cell(delta_time, times_fired)
/mob/living/silicon/robot/proc/use_power(delta_time, times_fired)
/mob/living/silicon/robot/proc/handle_robot_hud_updates()
/mob/living/silicon/robot/update_health_hud()
/mob/living/silicon/robot/proc/update_cell_hud_icon()
/mob/living/silicon/robot/handle_fire(delta_time, times_fired)
/mob/living/silicon/robot/update_fire()
