/mob/living/silicon/robot/Initialize(mapload)
/mob/living/silicon/robot/model/syndicate/Initialize(mapload)
/mob/living/silicon/robot/proc/create_modularInterface()
/mob/living/silicon/robot/model/syndicate/create_modularInterface()
/mob/living/silicon/robot/proc/set_modularInterface_theme()
/mob/living/silicon/robot/Destroy()
/mob/living/silicon/robot/Topic(href, href_list)
/mob/living/silicon/robot/get_cell()
/mob/living/silicon/robot/proc/pick_model()
/mob/living/silicon/robot/proc/setup_default_name()
/mob/living/silicon/robot/proc/updatename(client/pref_source)
/mob/living/silicon/robot/proc/get_standard_name()
/mob/living/silicon/robot/proc/ionpulse()
/mob/living/silicon/robot/proc/toggle_ionpulse()
/mob/living/silicon/robot/get_status_tab_items()
/mob/living/silicon/robot/proc/alarm_triggered(datum/source, alarm_type, area/source_area)
/mob/living/silicon/robot/proc/alarm_cleared(datum/source, alarm_type, area/source_area)
/mob/living/silicon/robot/can_interact_with(atom/A)
/mob/living/silicon/robot/proc/allowed(mob/M)
/mob/living/silicon/robot/proc/check_access(obj/item/card/id/I)
/mob/living/silicon/robot/regenerate_icons()
/mob/living/silicon/robot/update_icons()
/mob/living/silicon/robot/proc/self_destruct(mob/usr)
/mob/living/silicon/robot/proc/UnlinkSelf()
/mob/living/silicon/robot/mode()
/mob/living/silicon/robot/proc/SetLockdown(state = TRUE)
/mob/living/silicon/robot/proc/set_lockcharge(new_lockcharge)
/mob/living/silicon/robot/proc/SetEmagged(new_state)
/mob/living/silicon/robot/proc/on_light_eater(mob/living/silicon/robot/source, datum/light_eater)
/mob/living/silicon/robot/proc/smash_headlamp()
/mob/living/silicon/robot/proc/toggle_headlamp(turn_off = FALSE, update_color = FALSE)
/mob/living/silicon/robot/proc/deconstruct()
/mob/living/silicon/robot/proc/notify_ai(notifytype, oldname, newname)
/mob/living/silicon/robot/canUseTopic(atom/movable/M, be_close=FALSE, no_dexterity=FALSE, no_tk=FALSE, need_hands = FALSE, floor_okay=FALSE)
/mob/living/silicon/robot/updatehealth()
/mob/living/silicon/robot/update_sight()
/mob/living/silicon/robot/update_stat()
/mob/living/silicon/robot/revive(full_heal = FALSE, admin_revive = FALSE)
/mob/living/silicon/robot/fully_replace_character_name(oldname, newname)
/mob/living/silicon/robot/proc/ResetModel()
/mob/living/silicon/robot/model/syndicate/ResetModel()
/mob/living/silicon/robot/proc/has_model()
/mob/living/silicon/robot/proc/update_module_innate()
/mob/living/silicon/robot/proc/place_on_head(obj/item/new_hat)
/mob/living/silicon/robot/Exited(atom/movable/gone, direction)
/mob/living/silicon/robot/proc/add_to_upgrades(obj/item/borg/upgrade/new_upgrade, mob/user)
/mob/living/silicon/robot/proc/remove_from_upgrades(obj/item/borg/upgrade/old_upgrade)
/mob/living/silicon/robot/proc/on_upgrade_deleted(obj/item/borg/upgrade/old_upgrade)
/mob/living/silicon/robot/proc/make_shell(obj/item/borg/upgrade/ai/board)
	name = "Empty AI Shell-[ident]"
/mob/living/silicon/robot/proc/revert_shell()
	name = "Unformatted Cyborg-[ident]"
/mob/living/silicon/robot/proc/deploy_init(mob/living/silicon/ai/AI)
	name = real_name
/datum/action/innate/undeployment
	name = "Disconnect from shell"
	desc = "Stop controlling your shell and resume normal core operations."
/datum/action/innate/undeployment/Trigger()
/mob/living/silicon/robot/proc/undeploy()
/mob/living/silicon/robot/attack_ai(mob/user)
/mob/living/silicon/robot/mouse_buckle_handling(mob/living/M, mob/living/user)
/mob/living/silicon/robot/buckle_mob(mob/living/M, force = FALSE, check_loc = TRUE, buckle_mob_flags= RIDER_NEEDS_ARM)
/mob/living/silicon/robot/resist()
/mob/living/silicon/robot/proc/TryConnectToAI()
/mob/living/silicon/robot/proc/picturesync()
/mob/living/silicon/robot/proc/charge(datum/source, amount, repairs)
/mob/living/silicon/robot/proc/set_connected_ai(new_ai)
/mob/living/silicon/robot/proc/logevent(string = "")
/mob/living/silicon/robot/replace_identification_name(oldname,newname)
/mob/living/silicon/robot/get_exp_list(minutes)
