/datum/species/human/felinid
	name = "Felinid"
/datum/species/human/felinid/handle_chemicals(datum/reagent/chem, mob/living/carbon/human/H, delta_time, times_fired)
/datum/species/human/felinid/spec_death(gibbed, mob/living/carbon/human/H)
/datum/species/human/felinid/spec_stun(mob/living/carbon/human/H,amount)
/datum/species/human/felinid/can_wag_tail(mob/living/carbon/human/H)
/datum/species/human/felinid/is_wagging_tail(mob/living/carbon/human/H)
/datum/species/human/felinid/start_wagging_tail(mob/living/carbon/human/H)
/datum/species/human/felinid/stop_wagging_tail(mob/living/carbon/human/H)
/datum/species/human/felinid/on_species_gain(mob/living/carbon/C, datum/species/old_species, pref_load)
/proc/mass_purrbation()
/proc/mass_remove_purrbation()
/proc/purrbation_toggle(mob/living/carbon/human/H, silent = FALSE)
/proc/purrbation_apply(mob/living/carbon/human/H, silent = FALSE)
/proc/purrbation_remove(mob/living/carbon/human/H, silent = FALSE)
/datum/species/human/felinid/prepare_human_for_preview(mob/living/carbon/human/human)
