/datum/greyscale_config
/datum/greyscale_config/New()
/datum/greyscale_config/Destroy(force, ...)
/datum/greyscale_config/process(delta_time)
/datum/greyscale_config/proc/EnableAutoRefresh(live_type)
/datum/greyscale_config/proc/DisableAutoRefresh(live_type, remove_all=FALSE)
/datum/greyscale_config/proc/Refresh(loadFromDisk=FALSE)
/datum/greyscale_config/proc/CrossVerify()
/datum/greyscale_config/proc/DebugName()
/datum/greyscale_config/proc/ReadIconStateConfiguration(list/data)
/datum/greyscale_config/proc/ReadLayersFromJson(list/data)
/datum/greyscale_config/proc/ReadLayerGroup(list/data)
/datum/greyscale_config/proc/ReadMetadata()
/datum/greyscale_config/proc/SaveOutput(color_string)
/datum/greyscale_config/proc/Generate(color_string)
/datum/greyscale_config/proc/GenerateBundle(list/colors, list/render_steps)
/datum/greyscale_config/proc/GenerateLayerGroup(list/colors, list/group, list/render_steps)
/datum/greyscale_config/proc/GenerateDebug(colors)
