/datum/ntnet
/datum/ntnet/New(net_id, net_part_id, datum/ntnet/P = null)
/datum/ntnet/Destroy()
/datum/ntnet/proc/collect_interfaces(include_children=TRUE)
/datum/ntnet/proc/find_interface(tag_or_hid)
/datum/ntnet/proc/add_interface(datum/component/ntnet_interface/interface)
/datum/ntnet/proc/remove_interface(datum/component/ntnet_interface/interface, remove_all_alias=FALSE)
/datum/ntnet/proc/move_interface(datum/component/ntnet_interface/interface, target_network, original_network = null)
/datum/ntnet/station_root
/datum/ntnet/station_root/New(root_name)
/datum/ntnet/station_root/Destroy()
/datum/ntnet/station_root/proc/find_service_id(id)
/datum/ntnet/station_root/proc/find_service_path(path)
/datum/ntnet/station_root/proc/register_service(datum/ntnet_service/S)
/datum/ntnet/station_root/proc/unregister_service(datum/ntnet_service/S)
/datum/ntnet/station_root/proc/create_service(type)
/datum/ntnet/station_root/proc/destroy_service(type)
/datum/ntnet/station_root/proc/process_data_transmit(datum/component/ntnet_interface/sender, datum/netdata/data)
/datum/ntnet/station_root/proc/check_function(specific_action = 0)
/datum/ntnet/station_root/proc/build_software_lists()
/datum/ntnet/station_root/proc/find_ntnet_file_by_name(filename)
/datum/ntnet/station_root/proc/get_chat_channel_by_id(id)
/datum/ntnet/station_root/proc/resetIDS()
/datum/ntnet/station_root/proc/toggleIDS()
/datum/ntnet/station_root/proc/toggle_function(function)
/datum/ntnet/station_root/proc/register_map_supremecy() //called at map init to make this what station networks use.
