/mob/living/simple_animal/hostile/guardian/gravitokinetic
/mob/living/simple_animal/hostile/guardian/gravitokinetic/death()
/mob/living/simple_animal/hostile/guardian/gravitokinetic/AttackingTarget()
/mob/living/simple_animal/hostile/guardian/gravitokinetic/AltClickOn(atom/A)
/mob/living/simple_animal/hostile/guardian/gravitokinetic/Recall(forced)
/mob/living/simple_animal/hostile/guardian/gravitokinetic/Manifest(forced)
/mob/living/simple_animal/hostile/guardian/gravitokinetic/Moved(oldLoc, dir)
/mob/living/simple_animal/hostile/guardian/gravitokinetic/proc/add_gravity(atom/A, new_gravity = 3)
/mob/living/simple_animal/hostile/guardian/gravitokinetic/proc/remove_gravity(atom/target)
/mob/living/simple_animal/hostile/guardian/gravitokinetic/proc/__distance_check(atom/movable/AM, OldLoc, Dir, Forced)
