/datum/ai_planning_subtree/basic_melee_attack_subtree
/datum/ai_planning_subtree/basic_melee_attack_subtree/SelectBehaviors(datum/ai_controller/controller, delta_time)
/datum/ai_planning_subtree/basic_ranged_attack_subtree
/datum/ai_planning_subtree/basic_ranged_attack_subtree/SelectBehaviors(datum/ai_controller/controller, delta_time)
