/obj/machinery/atmospherics
/obj/machinery/atmospherics/LateInitialize()
/obj/machinery/atmospherics/examine(mob/user)
/obj/machinery/atmospherics/New(loc, process = TRUE, setdir, init_dir = ALL_CARDINALS)
/obj/machinery/atmospherics/Initialize(mapload)
/obj/machinery/atmospherics/Destroy()
/obj/machinery/atmospherics/proc/destroy_network()
/obj/machinery/atmospherics/proc/rebuild_pipes()
/obj/machinery/atmospherics/proc/get_rebuild_targets()
/obj/machinery/atmospherics/proc/nullify_node(i)
/obj/machinery/atmospherics/proc/get_node_connects()
/obj/machinery/atmospherics/proc/normalize_cardinal_directions()
/obj/machinery/atmospherics/proc/atmos_init(list/node_connects)
/obj/machinery/atmospherics/proc/set_piping_layer(new_layer)
/obj/machinery/atmospherics/update_icon()
/obj/machinery/atmospherics/proc/can_be_node(obj/machinery/atmospherics/target, iteration)
/obj/machinery/atmospherics/proc/find_connecting(direction, prompted_layer)
/obj/machinery/atmospherics/proc/connection_check(obj/machinery/atmospherics/target, given_layer)
/obj/machinery/atmospherics/proc/check_init_directions(obj/machinery/atmospherics/target)
/obj/machinery/atmospherics/proc/is_connectable(obj/machinery/atmospherics/target, given_layer)
/obj/machinery/atmospherics/proc/check_connectable_layer(obj/machinery/atmospherics/target, given_layer)
/obj/machinery/atmospherics/proc/check_connectable_color(obj/machinery/atmospherics/target)
/obj/machinery/atmospherics/proc/pipeline_expansion()
/obj/machinery/atmospherics/proc/set_init_directions(init_dir)
/obj/machinery/atmospherics/proc/get_init_directions()
/obj/machinery/atmospherics/proc/return_pipenet()
/obj/machinery/atmospherics/proc/return_pipenet_airs()
/obj/machinery/atmospherics/proc/set_pipenet()
/obj/machinery/atmospherics/proc/replace_pipenet()
/obj/machinery/atmospherics/proc/disconnect(obj/machinery/atmospherics/reference)
/obj/machinery/atmospherics/attackby(obj/item/W, mob/user, params)
/obj/machinery/atmospherics/wrench_act(mob/living/user, obj/item/I)
/obj/machinery/atmospherics/proc/can_unwrench(mob/user)
/obj/machinery/atmospherics/proc/unsafe_pressure_release(mob/user, pressures = null)
/obj/machinery/atmospherics/deconstruct(disassembled = TRUE)
/obj/machinery/atmospherics/proc/get_pipe_image(iconfile, iconstate, direction, color = COLOR_VERY_LIGHT_GRAY, piping_layer = 3, trinary = FALSE)
/obj/machinery/atmospherics/on_construction(obj_color, set_layer = PIPING_LAYER_DEFAULT)
/obj/machinery/atmospherics/update_name()
	name = "[GLOB.pipe_color_name[pipe_color]] [initial(name)]"
/obj/machinery/atmospherics/vv_edit_var(vname, vval)
/obj/machinery/atmospherics/Entered(atom/movable/arrived, atom/old_loc, list/atom/old_locs)
/obj/machinery/atmospherics/singularity_pull(S, current_size)
/obj/machinery/atmospherics/relaymove(mob/living/user, direction)
/obj/machinery/atmospherics/AltClick(mob/living/L)
/obj/machinery/atmospherics/proc/return_pipenets()
/obj/machinery/atmospherics/update_remote_sight(mob/user)
/obj/machinery/atmospherics/proc/can_see_pipes()
/obj/machinery/atmospherics/proc/update_layer()
/obj/machinery/atmospherics/proc/paint(paint_color)
