/datum/pipeline
/datum/pipeline/New()
/datum/pipeline/Destroy()
/datum/pipeline/process()
/datum/pipeline/proc/build_pipeline(obj/machinery/atmospherics/base)
/datum/pipeline/proc/build_pipeline_blocking(obj/machinery/atmospherics/base)
/datum/pipeline/proc/add_machinery_member(obj/machinery/atmospherics/components/considered_component)
/datum/pipeline/proc/add_member(obj/machinery/atmospherics/reference_device, obj/machinery/atmospherics/device_to_add)
/datum/pipeline/proc/merge(datum/pipeline/parent_pipeline)
/obj/machinery/atmospherics/proc/add_member(obj/machinery/atmospherics/considered_device)
/obj/machinery/atmospherics/pipe/add_member(obj/machinery/atmospherics/considered_device)
/obj/machinery/atmospherics/components/add_member(obj/machinery/atmospherics/considered_device)
/datum/pipeline/proc/temporarily_store_air()
/datum/pipeline/proc/temperature_interact(turf/target, share_volume, thermal_conductivity)
/datum/pipeline/proc/return_air()
/datum/pipeline/proc/reconcile_air()
