/datum/adventure_browser
/datum/adventure_browser/ui_interact(mob/user, datum/tgui/ui)
/datum/adventure_browser/ui_state(mob/user)
/datum/adventure_browser/proc/resolve_adventure(datum/source,result)
/datum/adventure_browser/ui_act(action, list/params, datum/tgui/ui, datum/ui_state/state)
/datum/adventure_browser/ui_data(mob/user)
/datum/adventure_browser/ui_close(mob/user)
/datum/adventure_browser/ui_assets(mob/user)
/datum/adventure_browser/Destroy(force, ...)
/client/proc/adventure_manager()
