/proc/get_airlock_overlay(icon_state, icon_file, em_block)
/obj/machinery/door/airlock
	name = "airlock"
/obj/machinery/door/airlock/Initialize(mapload)
/obj/machinery/door/airlock/LateInitialize()
/obj/machinery/door/airlock/connect_to_shuttle(obj/docking_port/mobile/port, obj/docking_port/stationary/dock)
/obj/machinery/door/airlock/proc/update_other_id()
/obj/machinery/door/airlock/proc/cyclelinkairlock()
/obj/machinery/door/airlock/vv_edit_var(var_name)
/obj/machinery/door/airlock/check_access_ntnet(datum/netdata/data)
/obj/machinery/door/airlock/proc/ntnet_receive(datum/source, datum/netdata/data)
/obj/machinery/door/airlock/lock()
/obj/machinery/door/airlock/proc/bolt()
/obj/machinery/door/airlock/proc/set_bolt(should_bolt)
/obj/machinery/door/airlock/unlock()
/obj/machinery/door/airlock/proc/unbolt()
/obj/machinery/door/airlock/narsie_act()
/obj/machinery/door/airlock/Destroy()
/obj/machinery/door/airlock/handle_atom_del(atom/A)
/obj/machinery/door/airlock/bumpopen(mob/living/user) //Airlocks now zap you when you 'bump' them open when they're electrified. --NeoFite
/obj/machinery/door/airlock/proc/isElectrified()
/obj/machinery/door/airlock/proc/canAIControl(mob/user)
/obj/machinery/door/airlock/proc/canAIHack()
/obj/machinery/door/airlock/hasPower()
/obj/machinery/door/airlock/requiresID()
/obj/machinery/door/airlock/proc/isAllPowerCut()
/obj/machinery/door/airlock/proc/regainMainPower()
/obj/machinery/door/airlock/proc/handlePowerRestore()
/obj/machinery/door/airlock/proc/loseMainPower()
/obj/machinery/door/airlock/proc/loseBackupPower()
/obj/machinery/door/airlock/proc/regainBackupPower()
/obj/machinery/door/airlock/proc/shock(mob/living/user, prb)
/obj/machinery/door/airlock/update_icon(updates=ALL, state=0, override=FALSE)
/obj/machinery/door/airlock/update_icon_state()
/obj/machinery/door/airlock/update_overlays()
/obj/machinery/door/airlock/do_animate(animation)
/obj/machinery/door/airlock/examine(mob/user)
/obj/machinery/door/airlock/attack_ai(mob/user)
/obj/machinery/door/airlock/proc/hack(mob/user)
/obj/machinery/door/airlock/attack_animal(mob/user, list/modifiers)
/obj/machinery/door/airlock/attack_paw(mob/user, list/modifiers)
/obj/machinery/door/airlock/proc/on_attack_hand(atom/source, mob/user, list/modifiers)
/obj/machinery/door/airlock/attack_hand(mob/user, list/modifiers)
/obj/machinery/door/airlock/attempt_wire_interaction(mob/user)
/obj/machinery/door/airlock/proc/electrified_loop()
/obj/machinery/door/airlock/Topic(href, href_list, nowindow = 0)
/obj/machinery/door/airlock/attackby(obj/item/C, mob/user, params)
/obj/machinery/door/airlock/try_to_weld(obj/item/weldingtool/W, mob/living/user)
/obj/machinery/door/airlock/try_to_weld_secondary(obj/item/weldingtool/tool, mob/user)
/obj/machinery/door/airlock/proc/weld_checks(obj/item/weldingtool/W, mob/user)
/obj/machinery/door/airlock/try_remove_seal(mob/living/user)
/obj/machinery/door/airlock/try_to_crowbar(obj/item/I, mob/living/user, forced = FALSE)
/obj/machinery/door/airlock/open(forced=0)
/obj/machinery/door/airlock/close(forced = FALSE, force_crush = FALSE)
/obj/machinery/door/airlock/proc/prison_open()
/obj/machinery/door/airlock/proc/change_paintjob(obj/item/airlock_painter/painter, mob/user)
/obj/machinery/door/airlock/CanAStarPass(obj/item/card/id/ID, to_dir, atom/movable/caller)
/obj/machinery/door/airlock/emag_act(mob/user, obj/item/card/emag/doorjack/D)
/obj/machinery/door/airlock/attack_alien(mob/living/carbon/alien/humanoid/user, list/modifiers)
/obj/machinery/door/airlock/hostile_lockdown(mob/origin)
/obj/machinery/door/airlock/disable_lockdown()
/obj/machinery/door/airlock/proc/on_break()
/obj/machinery/door/airlock/proc/set_electrified(seconds, mob/user)
/obj/machinery/door/airlock/take_damage(damage_amount, damage_type = BRUTE, damage_flag = 0, sound_effect = 1, attack_dir)
/obj/machinery/door/airlock/deconstruct(disassembled = TRUE, mob/user)
/obj/machinery/door/airlock/rcd_vals(mob/user, obj/item/construction/rcd/the_rcd)
/obj/machinery/door/airlock/rcd_act(mob/user, obj/item/construction/rcd/the_rcd, passed_mode)
/obj/machinery/door/airlock/proc/note_type() //Returns a string representing the type of note pinned to this airlock
/obj/machinery/door/airlock/ui_interact(mob/user, datum/tgui/ui)
/obj/machinery/door/airlock/ui_data()
/obj/machinery/door/airlock/ui_act(action, params)
/obj/machinery/door/airlock/proc/user_allowed(mob/user)
/obj/machinery/door/airlock/proc/shock_restore(mob/user)
/obj/machinery/door/airlock/proc/shock_temp(mob/user)
/obj/machinery/door/airlock/proc/shock_perm(mob/user)
/obj/machinery/door/airlock/proc/toggle_bolt(mob/user)
/obj/machinery/door/airlock/proc/toggle_emergency(mob/user)
/obj/machinery/door/airlock/proc/user_toggle_open(mob/user)
/obj/machinery/door/airlock/proc/set_wires()
