/obj/item/clothing/suit/hooded
/obj/item/clothing/suit/hooded/Initialize(mapload)
/obj/item/clothing/suit/hooded/Destroy()
/obj/item/clothing/suit/hooded/proc/MakeHood()
/obj/item/clothing/suit/hooded/ui_action_click()
/obj/item/clothing/suit/hooded/item_action_slot_check(slot, mob/user)
/obj/item/clothing/suit/hooded/equipped(mob/user, slot)
/obj/item/clothing/suit/hooded/proc/RemoveHood()
/obj/item/clothing/suit/hooded/dropped()
/obj/item/clothing/suit/hooded/proc/ToggleHood()
/obj/item/clothing/head/hooded
/obj/item/clothing/head/hooded/Destroy()
/obj/item/clothing/head/hooded/dropped()
/obj/item/clothing/head/hooded/equipped(mob/user, slot)
/obj/item/clothing/suit/toggle
/obj/item/clothing/suit/toggle/Initialize(mapload)
/obj/item/clothing/suit/space/hardsuit/Initialize(mapload)
/obj/item/clothing/suit/space/hardsuit/Destroy()
/obj/item/clothing/head/helmet/space/hardsuit/Destroy()
/obj/item/clothing/suit/space/hardsuit/proc/MakeHelmet()
/obj/item/clothing/suit/space/hardsuit/ui_action_click()
/obj/item/clothing/suit/space/hardsuit/equipped(mob/user, slot)
/obj/item/clothing/suit/space/hardsuit/proc/RemoveHelmet()
/obj/item/clothing/suit/space/hardsuit/dropped()
/obj/item/clothing/suit/space/hardsuit/proc/ToggleHelmet()
