/datum/addiction
/datum/addiction/proc/on_gain_addiction_points(datum/mind/victim_mind)
/datum/addiction/proc/become_addicted(datum/mind/victim_mind)
/datum/addiction/proc/on_lose_addiction_points(datum/mind/victim_mind)
/datum/addiction/proc/lose_addiction(datum/mind/victim_mind)
/datum/addiction/proc/process_addiction(mob/living/carbon/affected_carbon, delta_time, times_fired)
/datum/addiction/proc/withdrawal_enters_stage_1(mob/living/carbon/affected_carbon)
/datum/addiction/proc/withdrawal_enters_stage_2(mob/living/carbon/affected_carbon)
/datum/addiction/proc/withdrawal_enters_stage_3(mob/living/carbon/affected_carbon)
/datum/addiction/proc/end_withdrawal(mob/living/carbon/affected_carbon)
/datum/addiction/proc/withdrawal_stage_1_process(mob/living/carbon/affected_carbon, delta_time)
/datum/addiction/proc/withdrawal_stage_2_process(mob/living/carbon/affected_carbon, delta_time)
/datum/addiction/proc/withdrawal_stage_3_process(mob/living/carbon/affected_carbon, delta_time)
