/mob/living/carbon/perform_update_transform()
/mob/living/carbon
/mob/living/carbon/proc/apply_overlay(cache_index)
/mob/living/carbon/proc/remove_overlay(cache_index)
/mob/living/carbon/regenerate_icons()
/mob/living/carbon/update_inv_hands()
/mob/living/carbon/update_fire(fire_icon = "Generic_mob_burning")
/mob/living/carbon/update_damage_overlays()
/mob/living/carbon/update_inv_wear_mask()
/mob/living/carbon/update_inv_neck()
/mob/living/carbon/update_inv_back()
/mob/living/carbon/update_inv_head()
/mob/living/carbon/update_inv_handcuffed()
/mob/living/carbon/proc/update_hud_handcuffed()
/mob/living/carbon/proc/update_hud_head(obj/item/I)
/mob/living/carbon/proc/update_hud_wear_mask(obj/item/I)
/mob/living/carbon/proc/update_hud_neck(obj/item/I)
/mob/living/carbon/proc/update_hud_back(obj/item/I)
/obj/item/proc/worn_overlays(mutable_appearance/standing, isinhands = FALSE, icon_file, mutant_styles = NONE)
/mob/living/carbon/update_body()
/mob/living/carbon/proc/assign_bodypart_ownership()
/mob/living/carbon/proc/update_body_parts()
/mob/living/carbon/proc/generate_icon_render_key()
/mob/living/carbon/proc/load_limb_from_cache()
