/mob/living/carbon/slip(knockdown_amount, obj/O, lube, paralyze, force_drop)
/mob/living/carbon/Process_Spacemove(movement_dir = 0)
/mob/living/carbon/Move(NewLoc, direct)
/mob/living/carbon/set_usable_legs(new_value)
/mob/living/carbon/set_usable_hands(new_value)
/mob/living/carbon/on_movement_type_flag_enabled(datum/source, flag, old_movement_type)
/mob/living/carbon/on_movement_type_flag_disabled(datum/source, flag, old_movement_type)
