/mob/living/carbon/apply_damage(damage, damagetype = BRUTE, def_zone = null, blocked = FALSE, forced = FALSE, spread_damage = FALSE, wound_bonus = 0, bare_wound_bonus = 0, sharpness = NONE)
/mob/living/carbon/getBruteLoss()
/mob/living/carbon/getFireLoss()
/mob/living/carbon/adjustBruteLoss(amount, updating_health = TRUE, forced = FALSE, required_status)
/mob/living/carbon/adjustFireLoss(amount, updating_health = TRUE, forced = FALSE, required_status)
/mob/living/carbon/adjustToxLoss(amount, updating_health = TRUE, forced = FALSE)
/mob/living/carbon/getStaminaLoss()
/mob/living/carbon/adjustStaminaLoss(amount, updating_health = TRUE, forced = FALSE)
/mob/living/carbon/setStaminaLoss(amount, updating_health = TRUE, forced = FALSE)
/mob/living/carbon/adjustOrganLoss(slot, amount, maximum)
/mob/living/carbon/setOrganLoss(slot, amount)
/mob/living/carbon/getOrganLoss(slot)
/mob/living/carbon/proc/get_damaged_bodyparts(brute = FALSE, burn = FALSE, stamina = FALSE, status)
/mob/living/carbon/proc/get_damageable_bodyparts(status)
/mob/living/carbon/proc/get_wounded_bodyparts(brute = FALSE, burn = FALSE, stamina = FALSE, status)
/mob/living/carbon/heal_bodypart_damage(brute = 0, burn = 0, stamina = 0, updating_health = TRUE, required_status)
/mob/living/carbon/take_bodypart_damage(brute = 0, burn = 0, stamina = 0, updating_health = TRUE, required_status, check_armor = FALSE, wound_bonus = 0, bare_wound_bonus = 0, sharpness = NONE)
/mob/living/carbon/heal_overall_damage(brute = 0, burn = 0, stamina = 0, required_status, updating_health = TRUE)
/mob/living/carbon/take_overall_damage(brute = 0, burn = 0, stamina = 0, updating_health = TRUE, required_status)
