/mob/living/carbon/get_item_by_slot(slot_id)
/mob/living/carbon/proc/equip_in_one_of_slots(obj/item/I, list/slots, qdel_on_fail = 1)
/mob/living/carbon/equip_to_slot(obj/item/I, slot, initial = FALSE, redraw_mob = FALSE)
/mob/living/carbon/proc/has_equipped(obj/item/item, slot, initial = FALSE)
/mob/living/carbon/doUnEquip(obj/item/I, force, newloc, no_move, invdrop = TRUE, silent = FALSE)
/mob/living/proc/wear_mask_update(obj/item/I, toggle_off = 1)
/mob/living/carbon/wear_mask_update(obj/item/I, toggle_off = 1)
/mob/living/carbon/proc/head_update(obj/item/I, forced)
/mob/living/carbon/proc/get_holding_bodypart_of_item(obj/item/I)
/mob/living/carbon/proc/give()
/mob/living/carbon/proc/take(mob/living/carbon/offerer, obj/item/I)
