/mob/living/carbon/Life(delta_time = SSMOBS_DT, times_fired)
/mob/living/carbon/handle_breathing(delta_time, times_fired)
/mob/living/carbon/proc/breathe(delta_time, times_fired)
/mob/living/carbon/proc/has_smoke_protection()
/mob/living/carbon/proc/check_breath(datum/gas_mixture/breath)
/mob/living/carbon/proc/handle_breath_temperature(datum/gas_mixture/breath)
/mob/living/carbon/proc/get_breath_from_internal(volume_needed)
/mob/living/carbon/proc/handle_blood(delta_time, times_fired)
/mob/living/carbon/proc/handle_bodyparts(delta_time, times_fired)
/mob/living/carbon/proc/handle_organs(delta_time, times_fired)
/mob/living/carbon/handle_diseases(delta_time, times_fired)
/mob/living/carbon/handle_wounds(delta_time, times_fired)
/mob/living/carbon/proc/handle_changeling(delta_time, times_fired)
/mob/living/carbon/handle_mutations(time_since_irradiated, delta_time, times_fired)
	name = real_name
/mob/living/carbon/handle_status_effects(delta_time, times_fired)
/mob/living/carbon/handle_environment(datum/gas_mixture/environment, delta_time, times_fired)
/mob/living/carbon/proc/natural_bodytemperature_stabilization(datum/gas_mixture/environment, delta_time, times_fired)
/mob/living/carbon/proc/get_insulation_protection(temperature)
/mob/living/carbon/proc/get_heat_protection(temperature)
/mob/living/carbon/proc/get_cold_protection(temperature)
/mob/living/carbon/proc/share_bodytemperature(mob/living/carbon/M)
/mob/living/carbon/adjust_bodytemperature(amount, min_temp=0, max_temp=INFINITY, use_insulation=FALSE, use_steps=FALSE, capped=TRUE)
/mob/living/carbon/get_fullness()
/mob/living/carbon/has_reagent(reagent, amount = -1, needs_metabolizing = FALSE)
/mob/living/carbon/proc/handle_liver(delta_time, times_fired)
/mob/living/carbon/proc/undergoing_liver_failure()
/mob/living/carbon/proc/check_cremation(delta_time, times_fired)
/mob/living/carbon/proc/handle_brain_damage(delta_time, times_fired)
/mob/living/carbon/proc/can_heartattack()
/mob/living/carbon/proc/needs_heart()
/mob/living/carbon/proc/undergoing_cardiac_arrest()
/mob/living/carbon/proc/set_heartattack(status)
