/mob/living/carbon/IsParalyzed(include_stamcrit = TRUE)
/mob/living/carbon/proc/enter_stamcrit()
/mob/living/carbon/adjust_drugginess(amount)
/mob/living/carbon/set_drugginess(amount)
/mob/living/carbon/adjust_disgust(amount)
/mob/living/carbon/set_disgust(amount)
/mob/living/carbon/proc/get_traumas()
/mob/living/carbon/proc/has_trauma_type(brain_trauma_type, resilience)
/mob/living/carbon/proc/gain_trauma(datum/brain_trauma/trauma, resilience, ...)
/mob/living/carbon/proc/gain_trauma_type(brain_trauma_type = /datum/brain_trauma, resilience)
/mob/living/carbon/proc/cure_trauma_type(brain_trauma_type = /datum/brain_trauma, resilience)
/mob/living/carbon/proc/cure_all_traumas(resilience)
