/mob/living/carbon/human/handle_blood(delta_time, times_fired)
/mob/living/carbon/proc/bleed(amt)
/mob/living/carbon/human/bleed(amt)
/mob/living/carbon/proc/get_bleed_rate()
/mob/living/carbon/human/get_bleed_rate()
/mob/living/carbon/proc/bleed_warn(bleed_amt = 0, forced = FALSE)
/mob/living/carbon/human/bleed_warn(bleed_amt = 0, forced = FALSE)
/mob/living/proc/restore_blood()
/mob/living/carbon/restore_blood()
/mob/living/proc/transfer_blood_to(atom/movable/AM, amount, forced)
/mob/living/proc/get_blood_data(blood_id)
/mob/living/carbon/get_blood_data(blood_id)
/mob/proc/get_blood_id()
/mob/living/simple_animal/get_blood_id()
/mob/living/carbon/human/get_blood_id()
/proc/get_safe_blood(bloodtype)
/mob/living/proc/add_splatter_floor(turf/T, small_drip)
/mob/living/carbon/human/add_splatter_floor(turf/T, small_drip)
/mob/living/carbon/alien/add_splatter_floor(turf/T, small_drip)
/mob/living/silicon/robot/add_splatter_floor(turf/T, small_drip)
