/mob/living/proc/gib(no_brain, no_organs, no_bodyparts)
/mob/living/proc/gib_animation()
/mob/living/proc/spawn_gibs()
/mob/living/proc/spill_organs()
/mob/living/proc/spread_bodyparts()
/mob/living/proc/dust(just_ash, drop_items, force)
/mob/living/proc/dust_animation()
/mob/living/proc/spawn_dust(just_ash = FALSE)
/mob/living/proc/death(gibbed)
