/mob/living/proc/register_init_signals()
/mob/living/proc/on_knockedout_trait_gain(datum/source)
/mob/living/proc/on_knockedout_trait_loss(datum/source)
/mob/living/proc/on_deathcoma_trait_gain(datum/source)
/mob/living/proc/on_deathcoma_trait_loss(datum/source)
/mob/living/proc/on_immobilized_trait_gain(datum/source)
/mob/living/proc/on_immobilized_trait_loss(datum/source)
/mob/living/proc/on_floored_trait_gain(datum/source)
/mob/living/proc/on_floored_trait_loss(datum/source)
/mob/living/proc/on_forced_standing_trait_gain(datum/source)
/mob/living/proc/on_forced_standing_trait_loss(datum/source)
/mob/living/proc/on_handsblocked_trait_gain(datum/source)
/mob/living/proc/on_handsblocked_trait_loss(datum/source)
/mob/living/proc/on_ui_blocked_trait_gain(datum/source)
/mob/living/proc/on_ui_blocked_trait_loss(datum/source)
/mob/living/proc/on_pull_blocked_trait_gain(datum/source)
/mob/living/proc/on_pull_blocked_trait_loss(datum/source)
/mob/living/proc/on_incapacitated_trait_gain(datum/source)
/mob/living/proc/on_incapacitated_trait_loss(datum/source)
/mob/living/proc/on_restrained_trait_gain(datum/source)
/mob/living/proc/on_restrained_trait_loss(datum/source)
/mob/living/proc/update_succumb_action()
/mob/living/proc/on_movement_type_flag_enabled(datum/source, flag, old_movement_type)
/mob/living/proc/on_movement_type_flag_disabled(datum/source, flag, old_movement_type)
/mob/living/proc/on_skittish_trait_gain(datum/source)
/mob/living/proc/on_skittish_trait_loss(datum/source)
