/mob/living/proc/Life(delta_time = SSMOBS_DT, times_fired)
/mob/living/proc/handle_breathing(delta_time, times_fired)
/mob/living/proc/handle_mutations(delta_time, times_fired)
/mob/living/proc/handle_diseases(delta_time, times_fired)
/mob/living/proc/handle_wounds(delta_time, times_fired)
/mob/living/proc/handle_random_events(delta_time, times_fired)
/mob/living/proc/handle_environment(datum/gas_mixture/environment, delta_time, times_fired)
/mob/living/proc/handle_fire(delta_time, times_fired)
/mob/living/proc/get_fullness()
/mob/living/proc/has_reagent(reagent, amount = -1, needs_metabolizing = FALSE)
/mob/living/proc/handle_status_effects(delta_time, times_fired)
/mob/living/proc/handle_traits(delta_time, times_fired)
/mob/living/proc/update_damage_hud()
/mob/living/proc/handle_gravity(delta_time, times_fired)
/mob/living/proc/gravity_animate()
/mob/living/proc/gravity_pulse_animation()
/mob/living/proc/handle_high_gravity(gravity, delta_time, times_fired)
