/mob/living/Moved()
/mob/living/CanAllowThrough(atom/movable/mover, border_dir)
/mob/living/toggle_move_intent()
/mob/living/update_config_movespeed()
/mob/living/proc/update_move_intent_slowdown()
/mob/living/proc/update_turf_movespeed(turf/open/T)
/mob/living/proc/update_pull_movespeed()
/mob/living/zMove(dir, turf/target, z_move_flags = ZMOVE_FLIGHT_FLAGS)
/mob/living/can_z_move(direction, turf/start, turf/destination, z_move_flags = ZMOVE_FLIGHT_FLAGS, mob/living/rider)
/mob/set_currently_z_moving(value)
/mob/living/keybind_face_direction(direction)
