/datum/job/proc/required_playtime_remaining(client/C)
/datum/job/proc/get_exp_req_amount()
/datum/job/proc/get_exp_req_type()
/client/proc/calc_exp_type(exptype)
/client/proc/get_exp_living(pure_numeric = FALSE)
/proc/get_exp_format(expnum)
/datum/controller/subsystem/blackbox/proc/update_exp(mins)
/datum/controller/subsystem/blackbox/proc/update_exp_db()
/client/proc/set_exp_from_db()
/client/proc/update_flag_db(newflag, state = FALSE)
/client/proc/update_exp_list(minutes)
/client/proc/set_db_player_flags()
