/obj/item/ammo_casing/energy/laser
/obj/item/ammo_casing/energy/laser/hellfire
/obj/item/ammo_casing/energy/laser/hellfire/antique
/obj/item/ammo_casing/energy/lasergun
/obj/item/ammo_casing/energy/lasergun/old
/obj/item/ammo_casing/energy/laser/hos
/obj/item/ammo_casing/energy/laser/practice
/obj/item/ammo_casing/energy/laser/scatter
/obj/item/ammo_casing/energy/laser/scatter/disabler
/obj/item/ammo_casing/energy/laser/heavy
/obj/item/ammo_casing/energy/laser/pulse
/obj/item/ammo_casing/energy/laser/bluetag
/obj/item/ammo_casing/energy/laser/bluetag/hitscan
/obj/item/ammo_casing/energy/laser/redtag
/obj/item/ammo_casing/energy/laser/redtag/hitscan
/obj/item/ammo_casing/energy/xray
/obj/item/ammo_casing/energy/mindflayer
/obj/item/ammo_casing/energy/laser/minigun
