/obj/item/circuit_component
	name = COMPONENT_DEFAULT_NAME
/obj/item/circuit_component/proc/populate_options()
/obj/item/circuit_component/proc/populate_ports()
/obj/item/circuit_component/proc/add_option_port(name, list/list_to_use, order = 0, trigger = .proc/input_received)
/obj/item/circuit_component/Initialize(mapload)
	name = "[lowertext(display_name)] [COMPONENT_DEFAULT_NAME]"
	desc = " Incompatible with module components."
/obj/item/circuit_component/Destroy()
/obj/item/circuit_component/drop_location()
/obj/item/circuit_component/examine(mob/user)
/obj/item/circuit_component/proc/register_shell(atom/movable/shell)
/obj/item/circuit_component/proc/unregister_shell(atom/movable/shell)
/obj/item/circuit_component/proc/disconnect()
/obj/item/circuit_component/proc/add_input_port(name, type, order = 1, trigger = .proc/input_received, default = null, port_type = /datum/port/input, extra_args = null)
/obj/item/circuit_component/proc/remove_input_port(datum/port/input/input_port)
/obj/item/circuit_component/proc/add_output_port(name, type, order = 1)
/obj/item/circuit_component/proc/remove_output_port(datum/port/output/output_port)
/obj/item/circuit_component/proc/trigger_component(datum/port/input/port, list/return_values)
/obj/item/circuit_component/proc/set_circuit_size(new_size)
/obj/item/circuit_component/proc/should_receive_input(datum/port/input/port)
/obj/item/circuit_component/proc/get_location()
/obj/item/circuit_component/balloon_alert(mob/viewer, text)
/obj/item/circuit_component/proc/pre_input_received(datum/port/input/port)
/obj/item/circuit_component/proc/input_received(datum/port/input/port, list/return_values)
/obj/item/circuit_component/proc/add_to(obj/item/integrated_circuit/added_to)
/obj/item/circuit_component/proc/removed_from(obj/item/integrated_circuit/removed_from)
/obj/item/circuit_component/proc/get_ui_notices()
/obj/item/circuit_component/proc/ui_perform_action(mob/user, action)
/obj/item/circuit_component/proc/create_ui_notice(content, color, icon)
/obj/item/circuit_component/ui_host(mob/user)
/obj/item/circuit_component/proc/create_table_notices(list/entries)
/obj/item/circuit_component/proc/register_usb_parent(atom/movable/shell)
/obj/item/circuit_component/proc/unregister_usb_parent(atom/movable/shell)
