/proc/generate_circuit_datatypes()
/datum/circuit_datatype
/datum/circuit_datatype/proc/convert_value(datum/port/port, value_to_convert, force = FALSE)
/datum/circuit_datatype/proc/can_receive_from_datatype(datatype_to_check)
/datum/circuit_datatype/proc/on_gain(datum/port/gained_port)
/datum/circuit_datatype/proc/on_loss(datum/port/lost_port)
/datum/circuit_datatype/proc/is_compatible(datum/port/port)
/datum/circuit_datatype/proc/datatype_ui_data(datum/port/port)
/datum/circuit_datatype/proc/handle_manual_input(datum/port/input/port, mob/user, user_input)
/datum/circuit_datatype/proc/get_datatypes()
