/obj/vehicle/sealed/car/clowncar
	name = "clown car"
	desc = "How someone could even fit in there is byond me."
/obj/vehicle/sealed/car/clowncar/Initialize(mapload)
/obj/vehicle/sealed/car/clowncar/process()
/obj/vehicle/sealed/car/clowncar/generate_actions()
/obj/vehicle/sealed/car/clowncar/auto_assign_occupant_flags(mob/M)
/obj/vehicle/sealed/car/clowncar/mob_forced_enter(mob/M, silent = FALSE)
/obj/vehicle/sealed/car/clowncar/proc/irish_car_bomb()
/obj/vehicle/sealed/car/clowncar/after_add_occupant(mob/M, control_flags)
/obj/vehicle/sealed/car/clowncar/attack_animal(mob/living/simple_animal/user, list/modifiers)
/obj/vehicle/sealed/car/clowncar/mob_exit(mob/M, silent = FALSE, randomstep = FALSE)
/obj/vehicle/sealed/car/clowncar/take_damage(damage_amount, damage_type = BRUTE, damage_flag = 0, sound_effect = 1, attack_dir)
/obj/vehicle/sealed/car/clowncar/attacked_by(obj/item/I, mob/living/user)
/obj/vehicle/sealed/car/clowncar/Bump(atom/bumped)
/obj/vehicle/sealed/car/clowncar/emag_act(mob/user)
/obj/vehicle/sealed/car/clowncar/atom_destruction(damage_flag)
/obj/vehicle/sealed/car/clowncar/proc/roll_the_dice(mob/user)
/obj/vehicle/sealed/car/clowncar/proc/reset_icon()
/obj/vehicle/sealed/car/clowncar/proc/cover_in_oil()
/obj/vehicle/sealed/car/clowncar/proc/stop_dropping_oil()
/obj/vehicle/sealed/car/clowncar/proc/toggle_cannon(mob/user)
/obj/vehicle/sealed/car/clowncar/proc/activate_cannon()
/obj/vehicle/sealed/car/clowncar/proc/deactivate_cannon()
/obj/vehicle/sealed/car/clowncar/proc/fire_cannon_at(mob/user, atom/target, list/modifiers)
/obj/vehicle/sealed/car/clowncar/proc/increment_thanks_counter()
