/proc/circuit_signal_response(name, bitflag)
/proc/circuit_signal_param(name, type)
/proc/generate_circuit_signal_list()
/proc/generate_global_circuit_signal_list()
/obj/item/circuit_component/signal_handler/ui_state(mob/user)
/obj/item/circuit_component/signal_handler/ui_static_data(mob/user)
/obj/item/circuit_component/signal_handler/ui_interact(mob/user, datum/tgui/ui)
/obj/item/circuit_component/signal_handler/ui_act(action, list/params, datum/tgui/ui)
