/obj/projectile
	name = "projectile"
/obj/projectile/Initialize(mapload)
/obj/projectile/proc/Range()
/obj/projectile/proc/on_range() //if we want there to be effects when they reach the end of their range
/mob/living/proc/check_limb_hit(hit_zone)
/mob/living/carbon/check_limb_hit(hit_zone)
/obj/projectile/proc/on_hit(atom/target, blocked = FALSE, pierce_hit)
/obj/projectile/proc/vol_by_damage()
/obj/projectile/proc/on_ricochet(atom/A)
/obj/projectile/proc/store_hitscan_collision(datum/point/point_cache)
/obj/projectile/Bump(atom/A)
/obj/projectile/proc/Impact(atom/A)
/obj/projectile/proc/process_hit(turf/T, atom/target, atom/bumped, hit_something = FALSE)
/obj/projectile/proc/select_target(turf/T, atom/target, atom/bumped)
/obj/projectile/proc/can_hit_target(atom/target, direct_target = FALSE, ignore_loc = FALSE, cross_failed = FALSE)
/obj/projectile/proc/scan_crossed_hit(atom/movable/A)
/obj/projectile/proc/scan_moved_turf()
/obj/projectile/proc/on_entered(datum/source, atom/movable/AM)
/obj/projectile/CanPassThrough(atom/blocker, movement_dir, blocker_opinion)
/obj/projectile/Moved(atom/OldLoc, Dir)
/obj/projectile/proc/prehit_pierce(atom/A)
/obj/projectile/proc/check_ricochet(atom/A)
/obj/projectile/proc/check_ricochet_flag(atom/A)
/obj/projectile/proc/return_predicted_turf_after_moves(moves, forced_angle) //I say predicted because there's no telling that the projectile won't change direction/location in flight.
/obj/projectile/proc/return_pathing_turfs_in_moves(moves, forced_angle)
/obj/projectile/Process_Spacemove(movement_dir = 0)
/obj/projectile/process()
/obj/projectile/proc/fire(angle, atom/direct_target)
/obj/projectile/proc/set_angle(new_angle) //wrapper for overrides.
/obj/projectile/proc/set_angle_centered(new_angle)
/obj/projectile/forceMove(atom/target)
/obj/projectile/proc/after_z_change(atom/olcloc, atom/newloc)
/obj/projectile/proc/before_z_change(atom/oldloc, atom/newloc)
/obj/projectile/vv_edit_var(var_name, var_value)
/obj/projectile/proc/set_pixel_speed(new_speed)
/obj/projectile/proc/record_hitscan_start(datum/point/point_cache)
/obj/projectile/proc/process_hitscan()
/obj/projectile/proc/pixel_move(trajectory_multiplier, hitscanning = FALSE)
/obj/projectile/proc/process_homing() //may need speeding up in the future performance wise.
/obj/projectile/proc/set_homing_target(atom/A)
/obj/projectile/proc/preparePixelProjectile(atom/target, atom/source, modifiers, spread = 0)
/proc/calculate_projectile_angle_and_pixel_offsets(mob/user, modifiers)
/obj/projectile/Destroy()
/obj/projectile/proc/cleanup_beam_segments()
/obj/projectile/proc/finalize_hitscan_and_generate_tracers(impacting = TRUE)
/obj/projectile/proc/generate_hitscan_tracers(cleanup = TRUE, duration = 3, impacting = TRUE)
/obj/projectile/experience_pressure_difference()
/obj/projectile/proc/updateEmbedding()
