/obj/item/reagent_containers
	name = "Container"
	desc = "..."
/obj/item/reagent_containers/Initialize(mapload, vol)
/obj/item/reagent_containers/proc/attack_on_liquids_turf(obj/item/reagent_containers/my_beaker, turf/T, mob/living/user, obj/effect/abstract/liquid_turf/liquids)
/obj/item/reagent_containers/examine()
/obj/item/reagent_containers/create_reagents(max_vol, flags)
/obj/item/reagent_containers/attack(mob/living/M, mob/living/user, params)
/obj/item/reagent_containers/proc/on_reagents_del(datum/reagents/reagents)
/obj/item/reagent_containers/proc/add_initial_reagents()
/obj/item/reagent_containers/attack_self(mob/user)
/obj/item/reagent_containers/attack_self_secondary(mob/user)
/obj/item/reagent_containers/proc/mode_change_message(mob/user)
/obj/item/reagent_containers/proc/change_transfer_amount(mob/user, direction = FORWARD)
/obj/item/reagent_containers/AltClick(mob/user)
/obj/item/reagent_containers/attack(mob/M, mob/living/user, def_zone)
/obj/item/reagent_containers/pre_attack_secondary(atom/target, mob/living/user, params)
/obj/item/reagent_containers/proc/try_splash(mob/user, atom/target)
/obj/item/reagent_containers/proc/canconsume(mob/eater, mob/user)
/obj/item/reagent_containers/on_accidental_consumption(mob/living/carbon/M, mob/living/carbon/user, obj/item/source_item,  discover_after = TRUE)
/obj/item/reagent_containers/ex_act(severity)
/obj/item/reagent_containers/fire_act(exposed_temperature, exposed_volume)
/obj/item/reagent_containers/throw_impact(atom/hit_atom, datum/thrownthing/throwingdatum)
/obj/item/reagent_containers/proc/bartender_check(atom/target)
/obj/item/reagent_containers/proc/SplashReagents(atom/target, thrown = FALSE, override_spillable = FALSE)
/obj/item/reagent_containers/microwave_act(obj/machinery/microwave/M)
/obj/item/reagent_containers/fire_act(temperature, volume)
/obj/item/reagent_containers/proc/on_reagent_change(datum/reagents/holder, ...)
/obj/item/reagent_containers/update_overlays()
