/obj/structure/aquarium
	name = "aquarium"
/obj/structure/aquarium/Initialize(mapload)
/obj/structure/aquarium/proc/request_layer(layer_type)
/obj/structure/aquarium/proc/free_layer(value)
/obj/structure/aquarium/proc/get_surface_properties()
/obj/structure/aquarium/update_overlays()
/obj/structure/aquarium/examine(mob/user)
/obj/structure/aquarium/AltClick(mob/user)
/obj/structure/aquarium/wrench_act(mob/living/user, obj/item/I)
/obj/structure/aquarium/attackby(obj/item/I, mob/living/user, params)
/obj/structure/aquarium/proc/feed_feedback(datum/source, obj/item/thing, mob/user, params)
/obj/structure/aquarium/interact(mob/user)
/obj/structure/aquarium/proc/try_to_put_mob_in(mob/user)
/obj/structure/aquarium/proc/admire(mob/user)
/obj/structure/aquarium/ui_data(mob/user)
/obj/structure/aquarium/ui_static_data(mob/user)
/obj/structure/aquarium/ui_act(action, params)
/obj/structure/aquarium/ui_interact(mob/user, datum/tgui/ui)
/obj/structure/aquarium/atom_break(damage_flag)
/obj/structure/aquarium/proc/aquarium_smash()
