/datum/movespeed_modifier/obesity
/datum/movespeed_modifier/monkey_reagent_speedmod
/datum/movespeed_modifier/monkey_health_speedmod
/datum/movespeed_modifier/monkey_temperature_speedmod
/datum/movespeed_modifier/hunger
/datum/movespeed_modifier/slaughter
/datum/movespeed_modifier/resonance
/datum/movespeed_modifier/damage_slowdown
/datum/movespeed_modifier/damage_slowdown_flying
/datum/movespeed_modifier/equipment_speedmod
/datum/movespeed_modifier/grab_slowdown
/datum/movespeed_modifier/grab_slowdown/aggressive
/datum/movespeed_modifier/grab_slowdown/neck
/datum/movespeed_modifier/grab_slowdown/kill
/datum/movespeed_modifier/slime_reagentmod
/datum/movespeed_modifier/slime_healthmod
/datum/movespeed_modifier/config_walk_run
/datum/movespeed_modifier/config_walk_run/proc/sync()
/datum/movespeed_modifier/config_walk_run/walk/sync()
/datum/movespeed_modifier/config_walk_run/run/sync()
/datum/movespeed_modifier/turf_slowdown
/datum/movespeed_modifier/bulky_drag
/datum/movespeed_modifier/cold
/datum/movespeed_modifier/shove
/datum/movespeed_modifier/human_carry
/datum/movespeed_modifier/limbless
/datum/movespeed_modifier/simplemob_varspeed
/datum/movespeed_modifier/tarantula_web
/datum/movespeed_modifier/gravity
/datum/movespeed_modifier/carbon_softcrit
/datum/movespeed_modifier/slime_tempmod
/datum/movespeed_modifier/carbon_crawling
/datum/movespeed_modifier/mob_config_speedmod
/datum/movespeed_modifier/metabolicboost
/datum/movespeed_modifier/dragon_rage
/datum/movespeed_modifier/dragon_depression
/datum/movespeed_modifier/morph_disguised
