/obj/structure/grille
	desc = "A flimsy framework of iron rods."
	name = "grille"
/obj/structure/grille/Initialize(mapload)
/obj/structure/grille/Destroy()
/obj/structure/grille/take_damage(damage_amount, damage_type = BRUTE, damage_flag = 0, sound_effect = 1, attack_dir)
/obj/structure/grille/update_appearance(updates)
/obj/structure/grille/update_icon_state()
/obj/structure/grille/examine(mob/user)
/obj/structure/grille/rcd_vals(mob/user, obj/item/construction/rcd/the_rcd)
/obj/structure/grille/rcd_act(mob/user, obj/item/construction/rcd/the_rcd, passed_mode)
/obj/structure/grille/proc/clear_tile(mob/user)
/obj/structure/grille/Bumped(atom/movable/AM)
/obj/structure/grille/attack_animal(mob/user, list/modifiers)
/obj/structure/grille/attack_paw(mob/user, list/modifiers)
/obj/structure/grille/hulk_damage()
/obj/structure/grille/attack_hulk(mob/living/carbon/human/user)
/obj/structure/grille/attack_hand(mob/living/user, list/modifiers)
/obj/structure/grille/attack_alien(mob/living/user, list/modifiers)
/obj/structure/grille/CanAllowThrough(atom/movable/mover, border_dir)
/obj/structure/grille/CanAStarPass(obj/item/card/id/ID, to_dir, atom/movable/caller)
/obj/structure/grille/attackby(obj/item/W, mob/user, params)
/obj/structure/grille/play_attack_sound(damage_amount, damage_type = BRUTE, damage_flag = 0)
/obj/structure/grille/deconstruct(disassembled = TRUE)
/obj/structure/grille/atom_break()
/obj/structure/grille/proc/repair_grille()
/obj/structure/grille/proc/shock(mob/user, prb)
/obj/structure/grille/should_atmos_process(datum/gas_mixture/air, exposed_temperature)
/obj/structure/grille/atmos_expose(datum/gas_mixture/air, exposed_temperature)
/obj/structure/grille/hitby(atom/movable/AM, skipcatch, hitpush, blocked, datum/thrownthing/throwingdatum)
/obj/structure/grille/get_dumping_location(datum/component/storage/source,mob/user)
/obj/structure/grille/broken // Pre-broken grilles for map placement
/obj/structure/grille/broken/Initialize(mapload)
