/datum/exploration_event
/datum/exploration_event/proc/encounter(obj/item/exodrone/drone)
/datum/exploration_event/proc/get_discovery_message(obj/item/exodrone/drone)
/datum/exploration_event/proc/is_targetable()
/datum/exploration_event/simple
/datum/exploration_event/simple/encounter(obj/item/exodrone/drone)
/datum/exploration_event/simple/proc/fire(obj/item/exodrone/drone)
/datum/exploration_event/simple/proc/end(obj/item/exodrone/drone)
/datum/exploration_event/simple/proc/get_description(obj/item/exodrone/drone)
/datum/exploration_event/simple/proc/get_action_text(obj/item/exodrone/drone)
/datum/exploration_event/simple/proc/action_enabled(obj/item/exodrone/drone)
/datum/exploration_event/simple/proc/build_ui_event(obj/item/exodrone/drone)
