/datum/sort_instance
/datum/sort_instance/proc/timSort(start, end)
/datum/sort_instance/proc/binarySort(lo, hi, start)
/datum/sort_instance/proc/countRunAndMakeAscending(lo, hi)
/datum/sort_instance/proc/minRunLength(n)
/datum/sort_instance/proc/mergeCollapse()
/datum/sort_instance/proc/mergeForceCollapse()
/datum/sort_instance/proc/mergeAt(i)
/datum/sort_instance/proc/gallopLeft(key, base, len, hint)
/datum/sort_instance/proc/gallopRight(key, base, len, hint)
/datum/sort_instance/proc/mergeLo(base1, len1, base2, len2)
/datum/sort_instance/proc/mergeHi(base1, len1, base2, len2)
/datum/sort_instance/proc/mergeSort(start, end)
/datum/sort_instance/proc/mergeAt2(i)
