/turf/open/floor/iron
/turf/open/floor/iron/setup_broken_states()
/turf/open/floor/iron/setup_burnt_states()
/turf/open/floor/iron/examine(mob/user)
/turf/open/floor/iron/rust_heretic_act()
/turf/open/floor/iron/update_icon_state()
/turf/open/floor/iron/airless
/turf/open/floor/iron/telecomms
/turf/open/floor/iron/icemoon
/turf/open/floor/iron/edge
/turf/open/floor/iron/half
/turf/open/floor/iron/corner
/turf/open/floor/iron/large
/turf/open/floor/iron/textured
/turf/open/floor/iron/textured_edge
/turf/open/floor/iron/textured_half
/turf/open/floor/iron/textured_corner
/turf/open/floor/iron/textured_large
/turf/open/floor/iron/dark
/turf/open/floor/iron/dark/smooth_edge
/turf/open/floor/iron/dark/smooth_half
/turf/open/floor/iron/dark/smooth_corner
/turf/open/floor/iron/dark/smooth_large
/turf/open/floor/iron/dark/side
/turf/open/floor/iron/dark/corner
/turf/open/floor/iron/checker
/turf/open/floor/iron/dark/textured
/turf/open/floor/iron/dark/textured_edge
/turf/open/floor/iron/dark/textured_half
/turf/open/floor/iron/dark/textured_corner
/turf/open/floor/iron/dark/textured_large
/turf/open/floor/iron/dark/airless
/turf/open/floor/iron/dark/telecomms
/turf/open/floor/iron/dark/side/airless
/turf/open/floor/iron/dark/corner/airless
/turf/open/floor/iron/checker/airless
/turf/open/floor/iron/white
/turf/open/floor/iron/white/smooth_edge
/turf/open/floor/iron/white/smooth_half
/turf/open/floor/iron/white/smooth_corner
/turf/open/floor/iron/white/smooth_large
/turf/open/floor/iron/white/side
/turf/open/floor/iron/white/corner
/turf/open/floor/iron/cafeteria
/turf/open/floor/iron/white/textured
/turf/open/floor/iron/white/textured_edge
/turf/open/floor/iron/white/textured_half
/turf/open/floor/iron/white/textured_corner
/turf/open/floor/iron/white/textured_large
/turf/open/floor/iron/white/airless
/turf/open/floor/iron/white/telecomms
/turf/open/floor/iron/white/side/airless
/turf/open/floor/iron/white/corner/airless
/turf/open/floor/iron/cafeteria/airless
/turf/open/floor/iron/recharge_floor
/turf/open/floor/iron/recharge_floor/asteroid
/turf/open/floor/iron/smooth
/turf/open/floor/iron/smooth_edge
/turf/open/floor/iron/smooth_half
/turf/open/floor/iron/smooth_corner
/turf/open/floor/iron/smooth_large
/turf/open/floor/iron/chapel
/turf/open/floor/iron/showroomfloor
/turf/open/floor/iron/showroomfloor/airless
/turf/open/floor/iron/solarpanel
/turf/open/floor/iron/solarpanel/airless
/turf/open/floor/iron/freezer
/turf/open/floor/iron/freezer/airless
/turf/open/floor/iron/kitchen_coldroom
	name = "cold room floor"
/turf/open/floor/iron/kitchen_coldroom/Initialize(mapload)
/turf/open/floor/iron/kitchen_coldroom/freezerfloor
/turf/open/floor/iron/grimy
/turf/open/floor/iron/vaporwave
/turf/open/floor/iron/goonplaque
	name = "commemorative plaque"
	desc = "\"This is a plaque in honour of our comrades on the G4407 Stations. Hopefully TG4407 model can live up to your fame and fortune.\" Scratched in beneath that is a crude image of a meteor and a spaceman. The spaceman is laughing. The meteor is exploding."
/turf/open/floor/iron/stairs
/turf/open/floor/iron/stairs/left
/turf/open/floor/iron/stairs/medium
/turf/open/floor/iron/stairs/right
/turf/open/floor/iron/stairs/old
/turf/open/floor/iron/bluespace
	desc = "Sadly, these don't seem to make you faster..."
/turf/open/floor/iron/sepia
	desc = "Well, the flow of time is normal on these tiles, weird."
