/obj/item/transfer_valve
	name = "tank transfer valve"
	desc = "Regulates the transfer of air between two tanks."
/obj/item/transfer_valve/Destroy()
/obj/item/transfer_valve/IsAssemblyHolder()
/obj/item/transfer_valve/handle_atom_del(atom/deleted_atom)
/obj/item/transfer_valve/attackby(obj/item/item, mob/user, params)
/obj/item/transfer_valve/Move()
/obj/item/transfer_valve/dropped()
/obj/item/transfer_valve/on_found(mob/finder)
/obj/item/transfer_valve/attack_hand(mob/user, list/modifiers)
/obj/item/transfer_valve/proc/process_activation(obj/item/D)
/obj/item/transfer_valve/proc/toggle_off()
/obj/item/transfer_valve/update_icon_state()
/obj/item/transfer_valve/update_overlays()
/obj/item/transfer_valve/proc/merge_gases(datum/gas_mixture/target, change_volume = TRUE)
/obj/item/transfer_valve/proc/split_gases()
/obj/item/transfer_valve/proc/toggle_valve()
/obj/item/transfer_valve/proc/c_state()
/obj/item/transfer_valve/ui_state(mob/user)
/obj/item/transfer_valve/ui_interact(mob/user, datum/tgui/ui)
/obj/item/transfer_valve/ui_data(mob/user)
/obj/item/transfer_valve/ui_act(action, params)
/obj/item/transfer_valve/proc/ready()
