/obj/machinery/telecomms
/obj/machinery/telecomms/proc/relay_information(datum/signal/subspace/signal, filter, copysig, amount = 20)
/obj/machinery/telecomms/proc/relay_direct_information(datum/signal/signal, obj/machinery/telecomms/machine)
/obj/machinery/telecomms/proc/receive_information(datum/signal/signal, obj/machinery/telecomms/machine_from)
/obj/machinery/telecomms/proc/is_freq_listening(datum/signal/signal)
/obj/machinery/telecomms/Initialize(mapload)
/obj/machinery/telecomms/LateInitialize()
/obj/machinery/telecomms/Destroy()
/obj/machinery/telecomms/proc/add_link(obj/machinery/telecomms/T)
/obj/machinery/telecomms/update_icon_state()
/obj/machinery/telecomms/proc/update_power()
/obj/machinery/telecomms/process(delta_time)
/obj/machinery/telecomms/emp_act(severity)
/obj/machinery/telecomms/proc/de_emp()
