/client/verb/ooc(msg as text)
/proc/toggle_ooc(toggle = null)
/proc/toggle_dooc(toggle = null)
/client/proc/set_ooc()
/client/proc/reset_ooc()
/client/verb/admin_notice()
/client/verb/motd()
/client/proc/self_notes()
/client/proc/self_playtime()
/client/verb/select_ignore()
/client/verb/select_unignore()
/client/proc/show_previous_roundend_report()
/client/proc/show_servers_last_roundend_report()
/client/verb/fit_viewport()
/client/verb/policy()
/client/verb/fix_stat_panel()
