/mob/proc/set_suicide(suicide_state)
/mob/living/carbon/set_suicide(suicide_state) //you thought that box trick was pretty clever, didn't you? well now hardmode is on, boyo.
/mob/living/silicon/robot/set_suicide(suicide_state)
/mob/living/carbon/human/verb/suicide()
/mob/living/brain/verb/suicide()
/mob/living/silicon/ai/verb/suicide()
/mob/living/silicon/robot/verb/suicide()
/mob/living/silicon/pai/verb/suicide()
/mob/living/carbon/alien/humanoid/verb/suicide()
/mob/living/simple_animal/verb/suicide()
/mob/living/proc/suicide_log()
/mob/living/carbon/human/suicide_log()
/mob/living/proc/canSuicide()
/mob/living/carbon/canSuicide()
