/datum/module_picker
/datum/module_picker/New()
/proc/cmp_malfmodules_priority(datum/ai_module/A, datum/ai_module/B)
/proc/get_malf_modules()
/datum/module_picker/ui_state(mob/user)
/datum/module_picker/ui_interact(mob/user, datum/tgui/ui)
/datum/module_picker/ui_data(mob/user)
/datum/module_picker/ui_static_data(mob/user)
/datum/module_picker/ui_act(action, list/params)
/datum/module_picker/proc/purchase_module(mob/living/silicon/ai/AI, datum/ai_module/AM)
