/obj/effect/holodeck_effect
/obj/effect/holodeck_effect/proc/activate(obj/machinery/computer/holodeck/HC)
/obj/effect/holodeck_effect/proc/deactivate(obj/machinery/computer/holodeck/HC)
/obj/effect/holodeck_effect/proc/tick(obj/machinery/computer/holodeck/HC)
/obj/effect/holodeck_effect/proc/safety(active)
/obj/effect/holodeck_effect/cards
/obj/effect/holodeck_effect/cards/activate(obj/machinery/computer/holodeck/HC)
/obj/effect/holodeck_effect/cards/proc/handle_card_delete(datum/source)
/obj/effect/holodeck_effect/cards/safety(active)
/obj/effect/holodeck_effect/sparks/activate(obj/machinery/computer/holodeck/HC)
/obj/effect/holodeck_effect/random_book
/obj/effect/holodeck_effect/random_book/activate(obj/machinery/computer/holodeck/father_holodeck)
/obj/effect/holodeck_effect/mobspawner
/obj/effect/holodeck_effect/mobspawner/activate(obj/machinery/computer/holodeck/HC)
/obj/effect/holodeck_effect/mobspawner/deactivate(obj/machinery/computer/holodeck/HC)
/obj/effect/holodeck_effect/mobspawner/proc/handle_mob_delete(datum/source)
/obj/effect/holodeck_effect/mobspawner/pet
/obj/effect/holodeck_effect/mobspawner/pet/Initialize(mapload)
/mob/living/simple_animal/pet/dog/pug)
/obj/effect/holodeck_effect/mobspawner/bee
/obj/effect/holodeck_effect/mobspawner/monkey
/obj/effect/holodeck_effect/mobspawner/penguin
/obj/effect/holodeck_effect/mobspawner/penguin/Initialize(mapload)
/obj/effect/holodeck_effect/mobspawner/penguin_baby
