/datum/weather
/datum/weather/New(z_levels)
/datum/weather/proc/telegraph()
/datum/weather/proc/start()
/datum/weather/proc/wind_down()
/datum/weather/proc/end()
/datum/weather/proc/can_weather_act(mob/living/mob_to_check)
/datum/weather/proc/weather_act(mob/living/L)
/datum/weather/proc/update_areas()
