/datum/antagonist/cult
	name = "Cultist"
/datum/antagonist/cult/get_team()
/datum/antagonist/cult/create_team(datum/team/cult/new_team)
/datum/antagonist/cult/proc/add_objectives()
/datum/antagonist/cult/Destroy()
/datum/antagonist/cult/can_be_owned(datum/mind/new_owner)
/datum/antagonist/cult/greet()
/datum/antagonist/cult/on_gain()
/datum/antagonist/cult/on_removal()
/datum/antagonist/cult/get_preview_icon()
/datum/antagonist/cult/proc/equip_cultist(metal=TRUE)
/datum/antagonist/cult/proc/cult_give_item(obj/item/item_path, mob/living/carbon/human/mob)
/datum/antagonist/cult/apply_innate_effects(mob/living/mob_override)
/datum/antagonist/cult/remove_innate_effects(mob/living/mob_override)
/datum/antagonist/cult/on_mindshield(mob/implanter)
/datum/antagonist/cult/on_removal()
/datum/antagonist/cult/admin_add(datum/mind/new_owner,mob/admin)
/datum/antagonist/cult/admin_remove(mob/user)
/datum/antagonist/cult/get_admin_commands()
/datum/antagonist/cult/proc/admin_give_dagger(mob/admin)
/datum/antagonist/cult/proc/admin_give_metal(mob/admin)
/datum/antagonist/cult/proc/admin_take_all(mob/admin)
/datum/antagonist/cult/master
/datum/antagonist/cult/master/Destroy()
/datum/antagonist/cult/master/greet()
/datum/antagonist/cult/master/apply_innate_effects(mob/living/mob_override)
/datum/antagonist/cult/master/remove_innate_effects(mob/living/mob_override)
/datum/team/cult
	name = "Cult"
/datum/team/cult/proc/check_size()
/datum/team/cult/proc/rise(cultist)
/datum/team/cult/proc/ascend(cultist)
/datum/team/cult/proc/make_image(datum/objective/sacrifice/sac_objective)
/datum/team/cult/proc/setup_objectives()
/datum/objective/sacrifice
/datum/objective/sacrifice/proc/clear_sacrifice()
/datum/objective/sacrifice/find_target(dupe_search_range)
/datum/objective/sacrifice/proc/on_target_body_del()
/datum/objective/sacrifice/proc/on_mind_transfer(datum/source, mob/previous_body)
/datum/objective/sacrifice/proc/on_possible_mindswap(mob/source)
/datum/objective/sacrifice/proc/do_we_have_a_body()
/datum/objective/sacrifice/check_completion()
/datum/objective/sacrifice/update_explanation_text()
/datum/objective/eldergod
/datum/objective/eldergod/New()
/datum/objective/eldergod/update_explanation_text()
/datum/objective/eldergod/check_completion()
/datum/team/cult/proc/check_cult_victory()
/datum/team/cult/roundend_report()
/datum/team/cult/proc/is_sacrifice_target(datum/mind/mind)
/proc/is_convertable_to_cult(mob/living/M, datum/team/cult/specific_cult)
/datum/outfit/cultist
	name = "Cultist (Preview only)"
/datum/outfit/cultist/post_equip(mob/living/carbon/human/H, visualsOnly)
