/obj/item/organ/brain/proc/remove_skillchip(obj/item/skillchip/skillchip, silent = FALSE)
/obj/item/organ/brain/proc/implant_skillchip(obj/item/skillchip/skillchip, force = FALSE)
/obj/item/organ/brain/proc/clone_skillchip_list(not_removable = FALSE)
/obj/item/organ/brain/proc/destroy_all_skillchips(silent = TRUE)
/obj/item/organ/brain/proc/get_max_skillchip_complexity()
/obj/item/organ/brain/proc/get_used_skillchip_complexity()
/obj/item/organ/brain/proc/get_max_skillchip_slots()
/obj/item/organ/brain/proc/get_used_skillchip_slots()
/obj/item/organ/brain/proc/activate_skillchip_failsafe(silent = TRUE)
/obj/item/organ/brain/proc/update_skillchips()
