/mob/living/carbon/superior_animal"
/client/proc/SDQL2_query(query_text as message)
/world/proc/SDQL2_query(query_text, log_entry1, log_entry2, silent = FALSE)
/datum/sdql2_query
/datum/sdql2_query/New(list/tree, SU = FALSE, admin_interact = TRUE, _options = SDQL2_OPTIONS_DEFAULT, finished_qdel = FALSE)
/datum/sdql2_query/Destroy()
/datum/sdql2_query/proc/get_query_text()
/proc/recursive_list_print(list/output = list(), list/input, datum/callback/datum_handler, datum/callback/atom_handler)
/datum/sdql2_query/proc/text_state()
/datum/sdql2_query/proc/generate_stat()
/datum/sdql2_query/proc/delete_click()
/datum/sdql2_query/proc/action_click()
/datum/sdql2_query/proc/admin_halt(user = usr)
/datum/sdql2_query/proc/admin_run(mob/user = usr)
/datum/sdql2_query/proc/admin_del(user = usr)
/datum/sdql2_query/proc/set_option(name, value)
/datum/sdql2_query/proc/ARun()
/datum/sdql2_query/proc/Run()
/datum/sdql2_query/proc/PreSearch()
/datum/sdql2_query/proc/Search(list/tree)
/datum/sdql2_query/proc/SDQL_from_objs(list/tree)
/datum/sdql2_query/proc/SDQL_get_all(type, location)
/datum/sdql2_query/proc/Execute(list/found)
/datum/sdql2_query/proc/SDQL_print(object, list/text_list, print_nulls = TRUE)
/datum/sdql2_query/CanProcCall()
/datum/sdql2_query/vv_edit_var(var_name, var_value)
/datum/sdql2_query/proc/SDQL_internal_vv(d, list/set_list)
/datum/sdql2_query/proc/SDQL_function_blocking(datum/object, procname, list/arguments, source)
/datum/sdql2_query/proc/SDQL_function_async(datum/object, procname, list/arguments, source)
/datum/sdql2_query/proc/SDQL_expression(datum/object, list/expression, start = 1)
/datum/sdql2_query/proc/SDQL_value(datum/object, list/expression, start = 1)
/proc/SDQL_parse(list/query_list)
/proc/SDQL_testout(list/query_tree, indent = 0)
/world/proc/SDQL_var(object, list/expression, start = 1, source, superuser, datum/sdql2_query/query)
/proc/SDQL2_tokenize(query_text)
/proc/is_proper_datum(thing)
/obj/effect/statclick/SDQL2_delete/Click()
/obj/effect/statclick/SDQL2_action/Click()
/obj/effect/statclick/sdql2_vv_all
	name = "VIEW VARIABLES"
/obj/effect/statclick/sdql2_vv_all/Click()
