/proc/ui_style2icon(ui_style)
/proc/erp_ui_style2icon(ui_style)
/datum/hud
/datum/hud/New(mob/owner)
/datum/hud/Destroy()
/mob/proc/create_mob_hud()
/datum/hud/proc/show_hud(version = 0, mob/viewmob)
/datum/hud/proc/plane_masters_update()
/datum/hud/human/show_hud(version = 0,mob/viewmob)
/datum/hud/robot/show_hud(version = 0, mob/viewmob)
/datum/hud/proc/hidden_inventory_update()
/datum/hud/proc/persistent_inventory_update(mob/viewer)
/datum/hud/proc/update_ui_style(new_ui_style)
/datum/hud/proc/update_erp_ui_style(new_erp_ui_style)
/mob/verb/button_pressed_F12()
/datum/hud/proc/build_hand_slots()
/datum/hud/proc/update_locked_slots()
