/obj/item/stack
/obj/item/stack/Initialize(mapload, new_amount, merge = TRUE, list/mat_override=null, mat_amt=1)
/obj/item/stack/proc/set_mats_per_unit(list/mats, multiplier=1)
/obj/item/stack/proc/update_custom_materials()
/obj/item/stack/set_custom_materials(list/materials, multiplier=1, is_update=FALSE)
/obj/item/stack/on_grind()
/obj/item/stack/grind_requirements()
/obj/item/stack/proc/get_main_recipes()
/obj/item/stack/proc/update_weight()
/obj/item/stack/update_icon_state()
/obj/item/stack/examine(mob/user)
/obj/item/stack/proc/get_amount()
/obj/item/stack/proc/recursively_build_recipes(list/recipe_to_iterate)
/obj/item/stack/proc/build_recipe(datum/stack_recipe/R)
/obj/item/stack/proc/is_valid_recipe(datum/stack_recipe/R, list/recipe_list)
/obj/item/stack/ui_state(mob/user)
/obj/item/stack/ui_interact(mob/user, datum/tgui/ui)
/obj/item/stack/ui_data(mob/user)
/obj/item/stack/ui_static_data(mob/user)
/obj/item/stack/ui_act(action, params)
/obj/item/stack/vv_edit_var(vname, vval)
/obj/item/stack/proc/building_checks(datum/stack_recipe/recipe, multiplier)
/obj/item/stack/use(used, transfer = FALSE, check = TRUE) // return 0 = borked; return 1 = had enough
/obj/item/stack/tool_use_check(mob/living/user, amount)
/obj/item/stack/proc/is_zero_amount(delete_if_zero = TRUE)
/obj/item/stack/proc/add(_amount)
/obj/item/stack/proc/can_merge(obj/item/stack/check)
/obj/item/stack/proc/merge_without_del(obj/item/stack/target_stack, limit)
/obj/item/stack/proc/merge(obj/item/stack/target_stack, limit)
/obj/item/stack/proc/on_movable_entered_occupied_turf(datum/source, atom/movable/arrived)
/obj/item/stack/hitby(atom/movable/hitting, skipcatch, hitpush, blocked, datum/thrownthing/throwingdatum)
/obj/item/stack/attack_hand(mob/user, list/modifiers)
/obj/item/stack/attack_hand_secondary(mob/user, modifiers)
/obj/item/stack/proc/split_stack(mob/user, amount)
/obj/item/stack/attackby(obj/item/W, mob/user, params)
/obj/item/stack/proc/copy_evidences(obj/item/stack/from)
/obj/item/stack/microwave_act(obj/machinery/microwave/M)
/datum/stack_recipe
/datum/stack_recipe/New(title, result_type, req_amount = 1, res_amount = 1, max_res_amount = 1,time = 0, one_per_turf = FALSE, on_floor = FALSE, window_checks = FALSE, placement_checks = FALSE, applies_mats = FALSE, trait_booster = null, trait_modifier = 1)
/datum/stack_recipe_list
/datum/stack_recipe_list/New(title, recipes)
