/obj/machinery/rnd
	name = "R&D Device"
/obj/machinery/rnd/proc/reset_busy()
/obj/machinery/rnd/Initialize(mapload)
/obj/machinery/rnd/Destroy()
/obj/machinery/rnd/proc/shock(mob/user, prb)
/obj/machinery/rnd/attackby(obj/item/O, mob/user, params)
/obj/machinery/rnd/crowbar_act(mob/living/user, obj/item/tool)
/obj/machinery/rnd/crowbar_act_secondary(mob/living/user, obj/item/tool)
/obj/machinery/rnd/screwdriver_act(mob/living/user, obj/item/tool)
/obj/machinery/rnd/screwdriver_act_secondary(mob/living/user, obj/item/tool)
/obj/machinery/rnd/multitool_act(mob/living/user, obj/item/tool)
/obj/machinery/rnd/multitool_act_secondary(mob/living/user, obj/item/tool)
/obj/machinery/rnd/wirecutter_act(mob/living/user, obj/item/tool)
/obj/machinery/rnd/wirecutter_act_secondary(mob/living/user, obj/item/tool)
/obj/machinery/rnd/proc/Insert_Item(obj/item/I, mob/user)
/obj/machinery/rnd/proc/is_insertion_ready(mob/user)
/obj/machinery/rnd/on_deconstruction()
/obj/machinery/rnd/proc/AfterMaterialInsert(item_inserted, id_inserted, amount_inserted)
