/obj/vehicle/sealed
/obj/vehicle/sealed/generate_actions()
/obj/vehicle/sealed/generate_action_type()
/obj/vehicle/sealed/MouseDrop_T(atom/dropping, mob/M)
/obj/vehicle/sealed/Exited(atom/movable/gone, direction)
/obj/vehicle/sealed/Bump(atom/A)
/obj/vehicle/sealed/after_add_occupant(mob/M)
/obj/vehicle/sealed/after_remove_occupant(mob/M)
/obj/vehicle/sealed/proc/mob_try_enter(mob/M)
/obj/vehicle/sealed/proc/get_enter_delay(mob/M)
/obj/vehicle/sealed/proc/mob_enter(mob/M, silent = FALSE)
/obj/vehicle/sealed/proc/mob_try_exit(mob/M, mob/user, silent = FALSE, randomstep = FALSE)
/obj/vehicle/sealed/proc/mob_exit(mob/M, silent = FALSE, randomstep = FALSE)
/obj/vehicle/sealed/proc/exit_location(M)
/obj/vehicle/sealed/attackby(obj/item/I, mob/user, params)
/obj/vehicle/sealed/proc/remove_key(mob/user)
/obj/vehicle/sealed/Destroy()
/obj/vehicle/sealed/proc/dump_mobs(randomstep = TRUE)
/obj/vehicle/sealed/proc/dump_specific_mobs(flag, randomstep = TRUE)
/obj/vehicle/sealed/AllowDrop()
/obj/vehicle/sealed/relaymove(mob/living/user, direction)
/obj/vehicle/sealed/proc/vehicle_move(direction)
