/mob/living/simple_animal/bot/firebot
	name = "\improper Firebot"
	desc = "A little fire extinguishing bot. He looks rather anxious."
/mob/living/simple_animal/bot/firebot/Initialize(mapload)
/mob/living/simple_animal/bot/firebot/bot_reset()
/mob/living/simple_animal/bot/firebot/proc/create_extinguisher()
/mob/living/simple_animal/bot/firebot/UnarmedAttack(atom/A, proximity_flag, list/modifiers)
/mob/living/simple_animal/bot/firebot/RangedAttack(atom/A, proximity_flag, list/modifiers)
/mob/living/simple_animal/bot/firebot/turn_on()
/mob/living/simple_animal/bot/firebot/turn_off()
/mob/living/simple_animal/bot/firebot/bot_reset()
/mob/living/simple_animal/bot/firebot/proc/soft_reset()
/mob/living/simple_animal/bot/firebot/emag_act(mob/user)
/mob/living/simple_animal/bot/firebot/ui_data(mob/user)
/mob/living/simple_animal/bot/firebot/ui_act(action, params)
/mob/living/simple_animal/bot/firebot/proc/is_burning(atom/target)
/mob/living/simple_animal/bot/firebot/handle_automated_action()
/mob/living/simple_animal/bot/firebot/process_scan(atom/scan_target)
/mob/living/simple_animal/bot/firebot/should_atmos_process(datum/gas_mixture/air, exposed_temperature)
/mob/living/simple_animal/bot/firebot/atmos_expose(datum/gas_mixture/air, exposed_temperature)
/mob/living/simple_animal/bot/firebot/proc/spray_water(atom/target, mob/user)
/mob/living/simple_animal/bot/firebot/update_icon_state()
/mob/living/simple_animal/bot/firebot/explode()
