	name = "Networks"
/datum/controller/subsystem/networks/PreInit()
/datum/controller/subsystem/networks/stat_entry(msg)
/datum/controller/subsystem/networks/Initialize()
/datum/controller/subsystem/networks/proc/_process_packet(receiver_id, datum/netdata/data)
/datum/controller/subsystem/networks/fire(resumed = 0)
/datum/controller/subsystem/networks/proc/transmit(datum/netdata/data)
/datum/controller/subsystem/networks/proc/check_relay_operation(zlevel=0) //can be expanded later but right now it's true/false.
/datum/controller/subsystem/networks/proc/log_data_transfer( datum/netdata/data)
/datum/controller/subsystem/networks/proc/add_log(log_string, network = null , hardware_id = null)
/datum/controller/subsystem/networks/proc/purge_logs()
/datum/controller/subsystem/networks/proc/update_max_log_count(lognumber)
/datum/controller/subsystem/networks/proc/lookup_area_root_id(area/A, datum/map_template/M=null)
/datum/controller/subsystem/networks/proc/assign_area_network_id(area/A, datum/map_template/M=null)
/datum/controller/subsystem/networks/proc/assign_areas_root_ids(list/areas, datum/map_template/M=null)
/datum/controller/subsystem/networks/proc/network_list_to_string(list/tree)
/datum/controller/subsystem/networks/proc/network_string_to_list(name)
/datum/controller/subsystem/networks/proc/_hard_create_network(list/network_tree)
/datum/controller/subsystem/networks/proc/create_network_simple(network_id)
/datum/controller/subsystem/networks/proc/create_network(...)
/datum/controller/subsystem/networks/proc/get_next_HID()
/datum/controller/subsystem/networks/proc/assign_random_name(len=5, prefix="", postfix="")
