/datum/computer_file/program
/datum/computer_file/program/New(obj/item/modular_computer/comp = null)
/datum/computer_file/program/Destroy()
/datum/computer_file/program/clone()
/datum/computer_file/program/proc/update_computer_icon()
/datum/computer_file/program/proc/generate_network_log(text)
/datum/computer_file/program/proc/tap(atom/A, mob/living/user, params)
/datum/computer_file/program/proc/is_supported_by_hardware(hardware_flag = 0, loud = 0, mob/user = null)
/datum/computer_file/program/proc/get_signal(specific_action = 0)
/datum/computer_file/program/proc/process_tick(delta_time)
/datum/computer_file/program/proc/can_run(mob/user, loud = FALSE, access_to_check, transfer = FALSE, list/access)
/datum/computer_file/program/proc/get_header_data()
/datum/computer_file/program/proc/run_program(mob/living/user)
/datum/computer_file/program/proc/run_emag()
/datum/computer_file/program/proc/kill_program(forced = FALSE)
/datum/computer_file/program/ui_interact(mob/user, datum/tgui/ui)
/datum/computer_file/program/ui_act(action,list/params,datum/tgui/ui)
/datum/computer_file/program/ui_host()
/datum/computer_file/program/ui_status(mob/user)
