/datum/tgs_api/v3210
/datum/tgs_api/v3210/ApiVersion()
/datum/tgs_api/v3210/proc/trim_left(text)
/datum/tgs_api/v3210/proc/trim_right(text)
/datum/tgs_api/v3210/proc/file2list(filename)
/datum/tgs_api/v3210/OnWorldNew(minimum_required_security_level)
/datum/tgs_api/v3210/OnInitializationComplete()
/datum/tgs_api/v3210/InstanceName()
/datum/tgs_api/v3210/proc/ExportService(command, skip_compat_check = FALSE)
/datum/tgs_api/v3210/OnTopic(T)
/datum/tgs_api/v3210/OnReboot()
/datum/tgs_api/v3210/TestMerges()
/datum/tgs_api/v3210/Revision()
/datum/tgs_api/v3210/EndProcess()
/datum/tgs_api/v3210/ChatChannelInfo()
/datum/tgs_api/v3210/ChatBroadcast(message, list/channels)
/datum/tgs_api/v3210/ChatTargetedBroadcast(message, admin_only)
/datum/tgs_api/v3210/ChatPrivateMessage(message, datum/tgs_chat_user/user)
/datum/tgs_api/v3210/SecurityLevel()
