/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/check_part_connectivity()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/activate(mob/living/user)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/unregister_signals(only_signals = FALSE)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/deactivate()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/assert_gases()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/update_pipenets()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/update_temperature_status(delta_time)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/play_ambience()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/check_fuel()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/check_power_use()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/check_gas_requirements()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/dump_gases()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/get_status()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/alarm()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/get_integrity_percent()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/get_area_cell_percent()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/check_alert()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/countdown()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/meltdown()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/induce_hallucination(strength, delta_time, force=FALSE)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/emit_rads()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/check_cracked_parts()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/create_crack()
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/spill_gases(obj/origin, datum/gas_mixture/target_mix, ratio)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/check_spill(delta_time)
