/obj/machinery/atmospherics/components/unary/hypertorus/core/process(delta_time)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/fusion_process(delta_time)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/moderator_fuel_process(delta_time, production_amount, consumption_amount, datum/gas_mixture/internal_output, moderator_list, datum/hfr_fuel/fuel, fuel_list)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/moderator_common_process(delta_time, scaled_production, datum/gas_mixture/internal_output, moderator_list, dirty_production_rate, heat_output, radiation_modifier)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/evaporate_moderator(delta_time)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/process_damageheal(delta_time)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/check_nuclear_particles(moderator_list)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/check_lightning_arcs(moderator_list)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/check_gravity_pulse(delta_time)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/remove_waste(delta_time)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/process_internal_cooling(delta_time)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/inject_from_side_components(delta_time)
/obj/machinery/atmospherics/components/unary/hypertorus/core/proc/check_deconstructable()
