/obj/item/gun/energy
	name = "energy gun"
	desc = "A basic energy-based gun."
/obj/item/gun/energy/emp_act(severity)
/obj/item/gun/energy/get_cell()
/obj/item/gun/energy/Initialize(mapload)
/obj/item/gun/energy/add_weapon_description()
/obj/item/gun/energy/proc/add_notes_energy()
/obj/item/gun/energy/ComponentInitialize()
/obj/item/gun/energy/proc/update_ammo_types()
/obj/item/gun/energy/Destroy()
/obj/item/gun/energy/handle_atom_del(atom/A)
/obj/item/gun/energy/process(delta_time)
/obj/item/gun/energy/attack_self(mob/living/user as mob)
/obj/item/gun/energy/can_shoot()
/obj/item/gun/energy/recharge_newshot(no_cyborg_drain)
/obj/item/gun/energy/handle_chamber()
/obj/item/gun/energy/process_fire(atom/target, mob/living/user, message = TRUE, params = null, zone_override = "", bonus_spread = 0)
/obj/item/gun/energy/process_burst(mob/living/user, atom/target, message = TRUE, params = null, zone_override="", sprd = 0, randomized_gun_spread = 0, randomized_bonus_spread = 0, rand_spr = 0, iteration = 0)
/obj/item/gun/energy/proc/select_fire(mob/living/user)
/obj/item/gun/energy/update_icon_state()
/obj/item/gun/energy/update_overlays()
/obj/item/gun/energy/proc/get_charge_ratio()
/obj/item/gun/energy/suicide_act(mob/living/user)
/obj/item/gun/energy/vv_edit_var(var_name, var_value)
/obj/item/gun/energy/ignition_effect(atom/A, mob/living/user)
/obj/item/gun/energy/proc/instant_recharge()
