/datum/chemical_reaction/formaldehyde
/datum/chemical_reaction/fentanyl
/datum/chemical_reaction/cyanide
/datum/chemical_reaction/itching_powder
/datum/chemical_reaction/facid
/datum/chemical_reaction/nitracid
/datum/chemical_reaction/sulfonal
/datum/chemical_reaction/lipolicide
/datum/chemical_reaction/mutagen
/datum/chemical_reaction/lexorin
/datum/chemical_reaction/hot_ice_melt
/datum/chemical_reaction/chloralhydrate
/datum/chemical_reaction/mutetoxin //i'll just fit this in here snugly between other unfun chemicals :v
/datum/chemical_reaction/zombiepowder
/datum/chemical_reaction/ghoulpowder
/datum/chemical_reaction/mindbreaker
/datum/chemical_reaction/heparin
/datum/chemical_reaction/rotatium
/datum/chemical_reaction/anacea
/datum/chemical_reaction/mimesbane
/datum/chemical_reaction/bonehurtingjuice
