/proc/init_gaslist_cache()
/datum/gas_mixture
/datum/gas_mixture/New(volume)
/datum/gas_mixture/proc/assert_gas(gas_id)
/datum/gas_mixture/proc/assert_gases(...)
/datum/gas_mixture/proc/add_gas(gas_id)
/datum/gas_mixture/proc/add_gases(...)
/datum/gas_mixture/proc/garbage_collect(list/tocheck)
/datum/gas_mixture/proc/heat_capacity(data = MOLES)
/datum/gas_mixture/turf/heat_capacity(data = MOLES)
/datum/gas_mixture/proc/total_moles()
/datum/gas_mixture/proc/has_gas(gas_id, amount=0)
/datum/gas_mixture/proc/return_pressure()
/datum/gas_mixture/proc/return_temperature()
/datum/gas_mixture/proc/return_volume()
/datum/gas_mixture/proc/return_visuals()
/datum/gas_mixture/proc/thermal_energy()
/datum/gas_mixture/proc/archive()
/datum/gas_mixture/proc/merge(datum/gas_mixture/giver)
/datum/gas_mixture/proc/remove(amount)
/datum/gas_mixture/proc/remove_ratio(ratio)
/datum/gas_mixture/proc/remove_specific(gas_id, amount)
/datum/gas_mixture/proc/remove_specific_ratio(gas_id, ratio)
/datum/gas_mixture/proc/equalize(datum/gas_mixture/other)
/datum/gas_mixture/proc/copy()
/datum/gas_mixture/proc/copy_from(datum/gas_mixture/sample, partial = 1)
/datum/gas_mixture/proc/copy_from_turf(turf/model)
/datum/gas_mixture/proc/parse_gas_string(gas_string)
/datum/gas_mixture/proc/share(datum/gas_mixture/sharer, atmos_adjacent_turfs = 4)
/datum/gas_mixture/proc/temperature_share(datum/gas_mixture/sharer, conduction_coefficient, sharer_temperature, sharer_heat_capacity)
/datum/gas_mixture/proc/compare(datum/gas_mixture/sample)
/datum/gas_mixture/proc/react(datum/holder)
/datum/gas_mixture/proc/get_breath_partial_pressure(gas_pressure)
/datum/gas_mixture/proc/get_true_breath_pressure(partial_pressure)
/datum/gas_mixture/proc/pump_gas_to(datum/gas_mixture/output_air, target_pressure, specific_gas = null)
/datum/gas_mixture/proc/release_gas_to(datum/gas_mixture/output_air, target_pressure, rate=1)
