/obj/machinery/computer/communications
	name = "communications console"
	desc = "A console used for high-priority announcements and emergencies."
/obj/machinery/computer/communications/Initialize(mapload)
/obj/machinery/computer/communications/proc/authenticated_as_non_silicon_captain(mob/user)
/obj/machinery/computer/communications/proc/authenticated_as_silicon_or_captain(mob/user)
/obj/machinery/computer/communications/proc/authenticated(mob/user)
/obj/machinery/computer/communications/proc/authenticated_as_ai_or_captain(mob/user)
/obj/machinery/computer/communications/attackby(obj/I, mob/user, params)
/obj/machinery/computer/communications/emag_act(mob/user)
/obj/machinery/computer/communications/ui_act(action, list/params)
/obj/machinery/computer/communications/proc/emergency_access_cooldown(mob/user)
/obj/machinery/computer/communications/proc/send_cross_comms_message(mob/user, destination, message)
/obj/machinery/computer/communications/ui_data(mob/user)
/obj/machinery/computer/communications/ui_interact(mob/user, datum/tgui/ui)
/obj/machinery/computer/communications/ui_static_data(mob/user)
/obj/machinery/computer/communications/Topic(href, href_list)
/obj/machinery/computer/communications/proc/has_communication()
/obj/machinery/computer/communications/proc/set_state(mob/user, new_state)
/obj/machinery/computer/communications/proc/can_buy_shuttles(mob/user)
/obj/machinery/computer/communications/proc/can_purchase_this_shuttle(datum/map_template/shuttle/shuttle_template)
/obj/machinery/computer/communications/proc/can_send_messages_to_other_sectors(mob/user)
/obj/machinery/computer/communications/proc/emergency_meeting(mob/living/user)
/obj/machinery/computer/communications/proc/make_announcement(mob/living/user)
/obj/machinery/computer/communications/proc/post_status(command, data1, data2)
/obj/machinery/computer/communications/Destroy()
/obj/machinery/computer/communications/proc/override_cooldown()
/obj/machinery/computer/communications/proc/add_message(datum/comm_message/new_message)
/datum/comm_message
/datum/comm_message/New(new_title,new_content,new_possible_answers)
