/obj/machinery/computer/scan_consolenew
	name = "DNA Console"
	desc = "Scan DNA."
/obj/machinery/computer/scan_consolenew/process()
/obj/machinery/computer/scan_consolenew/attackby(obj/item/I, mob/user, params)
/obj/machinery/computer/scan_consolenew/AltClick(mob/user)
/obj/machinery/computer/scan_consolenew/Initialize(mapload)
/obj/machinery/computer/scan_consolenew/ui_interact(mob/user, datum/tgui/ui)
/obj/machinery/computer/scan_consolenew/ui_assets()
/obj/machinery/computer/scan_consolenew/ui_data(mob/user)
/obj/machinery/computer/scan_consolenew/ui_act(action, list/params)
/obj/machinery/computer/scan_consolenew/proc/apply_genetic_makeup(type, buffer_slot)
/obj/machinery/computer/scan_consolenew/proc/scanner_operational()
/obj/machinery/computer/scan_consolenew/proc/can_modify_occupant()
/obj/machinery/computer/scan_consolenew/proc/connect_to_scanner()
/obj/machinery/computer/scan_consolenew/proc/on_scanner_close()
/obj/machinery/computer/scan_consolenew/proc/on_scanner_open()
/obj/machinery/computer/scan_consolenew/proc/build_genetic_makeup_list()
/obj/machinery/computer/scan_consolenew/proc/build_mutation_list(can_modify_occ)
/obj/machinery/computer/scan_consolenew/proc/build_chrom_list(mutation)
/obj/machinery/computer/scan_consolenew/proc/check_discovery(alias)
/obj/machinery/computer/scan_consolenew/proc/get_mut_by_ref(ref, target_flags)
/obj/machinery/computer/scan_consolenew/proc/randomize_GENETIC_DAMAGE_accuracy(position, pulse_duration, number_of_blocks)
/obj/machinery/computer/scan_consolenew/proc/scramble(input,rs)
/obj/machinery/computer/scan_consolenew/proc/genetic_damage_pulse()
/obj/machinery/computer/scan_consolenew/proc/set_default_state()
/obj/machinery/computer/scan_consolenew/proc/eject_disk(mob/user)
/obj/machinery/computer/scan_consolenew/proc/set_connected_scanner(new_scanner)
/obj/machinery/computer/scan_consolenew/proc/react_to_scanner_del(datum/source)
