/datum/component/riding/creature
/datum/component/riding/creature/Initialize(mob/living/riding_mob, force = FALSE, ride_check_flags = NONE, potion_boost = FALSE)
/datum/component/riding/creature/Destroy(force, silent)
/datum/component/riding/creature/RegisterWithParent()
/datum/component/riding/creature/proc/log_riding(mob/living/living_parent, mob/living/rider)
/datum/component/riding/creature/ride_check(mob/living/rider, consequences = TRUE)
/datum/component/riding/creature/vehicle_mob_buckle(datum/source, mob/living/rider, force = FALSE)
/datum/component/riding/creature/vehicle_mob_unbuckle(mob/living/living_parent, mob/living/former_rider, force = FALSE)
/datum/component/riding/creature/driver_move(atom/movable/movable_parent, mob/living/user, direction)
/datum/component/riding/creature/proc/force_dismount(mob/living/rider, gentle = FALSE)
/datum/component/riding/creature/proc/check_emote(mob/living/user, datum/emote/emote)
/datum/component/riding/creature/proc/setup_abilities(mob/living/rider)
/datum/component/riding/creature/proc/remove_abilities(mob/living/rider)
/datum/component/riding/creature/riding_can_z_move(atom/movable/movable_parent, direction, turf/start, turf/destination, z_move_flags, mob/living/rider)
/datum/component/riding/creature/human
/datum/component/riding/creature/human/Initialize(mob/living/riding_mob, force = FALSE, ride_check_flags = NONE, potion_boost = FALSE)
/datum/component/riding/creature/human/RegisterWithParent()
/datum/component/riding/creature/human/log_riding(mob/living/living_parent, mob/living/rider)
/datum/component/riding/creature/human/vehicle_mob_unbuckle(datum/source, mob/living/former_rider, force = FALSE)
/datum/component/riding/creature/human/proc/on_host_unarmed_melee(mob/living/carbon/human/human_parent, atom/target, proximity, modifiers)
/datum/component/riding/creature/human/proc/check_carrier_fall_over(mob/living/carbon/human/human_parent)
/datum/component/riding/creature/human/handle_vehicle_layer(dir)
/datum/component/riding/creature/human/get_offsets(pass_index)
/datum/component/riding/creature/human/force_dismount(mob/living/dismounted_rider)
/datum/component/riding/creature/cyborg
/datum/component/riding/creature/cyborg/ride_check(mob/living/user, consequences = TRUE)
/datum/component/riding/creature/cyborg/handle_vehicle_layer(dir)
/datum/component/riding/creature/cyborg/get_offsets(pass_index) // list(dir = x, y, layer)
/datum/component/riding/creature/cyborg/handle_vehicle_offsets(dir)
/datum/component/riding/creature/mulebot/handle_specials()
/datum/component/riding/creature/cow/handle_specials()
/datum/component/riding/creature/bear/handle_specials()
/datum/component/riding/creature/carp
/datum/component/riding/creature/carp/handle_specials()
/datum/component/riding/creature/megacarp/handle_specials()
/datum/component/riding/creature/vatbeast
/datum/component/riding/creature/vatbeast/handle_specials()
/datum/component/riding/creature/goliath
/datum/component/riding/creature/goliath/handle_specials()
/datum/component/riding/creature/glutton/handle_specials()
