/datum/component/riding
/datum/component/riding/Initialize(mob/living/riding_mob, force = FALSE, buckle_mob_flags= NONE, potion_boost = FALSE)
/datum/component/riding/RegisterWithParent()
/datum/component/riding/proc/handle_specials()
/datum/component/riding/proc/vehicle_mob_unbuckle(datum/source, mob/living/rider, force = FALSE)
/datum/component/riding/proc/vehicle_mob_buckle(datum/source, mob/living/rider, force = FALSE)
/datum/component/riding/proc/handle_vehicle_layer(dir)
/datum/component/riding/proc/set_vehicle_dir_layer(dir, layer)
/datum/component/riding/proc/vehicle_moved(datum/source, oldloc, dir, forced)
/datum/component/riding/proc/vehicle_turned(datum/source, _old_dir, new_dir)
/datum/component/riding/proc/ride_check(mob/living/rider, consequences = TRUE)
/datum/component/riding/proc/handle_vehicle_offsets(dir)
/datum/component/riding/proc/set_vehicle_dir_offsets(dir, x, y)
/datum/component/riding/proc/get_offsets(pass_index) // list(dir = x, y, layer)
/datum/component/riding/proc/set_riding_offsets(index, list/offsets)
/datum/component/riding/proc/keycheck(mob/user)
/datum/component/riding/proc/restore_position(mob/living/buckled_mob)
/datum/component/riding/proc/turf_check(turf/next, turf/current)
/datum/component/riding/proc/driver_move(atom/movable/movable_parent, mob/living/user, direction)
/datum/component/riding/proc/vehicle_bump(atom/movable/movable_parent, obj/machinery/door/possible_bumped_door)
/datum/component/riding/proc/Unbuckle(atom/movable/M)
/datum/component/riding/proc/Process_Spacemove(direction)
/datum/component/riding/proc/unequip_buckle_inhands(mob/living/carbon/user)
/datum/component/riding/proc/riding_can_z_move(atom/movable/movable_parent, direction, turf/start, turf/destination, z_move_flags, mob/living/rider)
