/obj/machinery/disposal
/obj/machinery/disposal/Initialize(mapload, obj/structure/disposalconstruct/make_from)
/obj/machinery/disposal/proc/trunk_check()
/obj/machinery/disposal/Destroy()
/obj/machinery/disposal/handle_atom_del(atom/A)
/obj/machinery/disposal/singularity_pull(S, current_size)
/obj/machinery/disposal/LateInitialize()
/obj/machinery/disposal/attackby(obj/item/I, mob/living/user, params)
/obj/machinery/disposal/proc/rat_rummage(mob/living/simple_animal/hostile/regalrat/king)
/obj/machinery/disposal/proc/place_item_in_disposal(obj/item/I, mob/user)
/obj/machinery/disposal/MouseDrop_T(mob/living/target, mob/living/user)
/obj/machinery/disposal/proc/stuff_mob_in(mob/living/target, mob/living/user)
/obj/machinery/disposal/relaymove(mob/living/user, direction)
/obj/machinery/disposal/container_resist_act(mob/living/user)
/obj/machinery/disposal/proc/attempt_escape(mob/user)
/obj/machinery/disposal/proc/go_out(mob/user)
/obj/machinery/disposal/attack_paw(mob/user, list/modifiers)
/obj/machinery/disposal/proc/eject()
/obj/machinery/disposal/proc/flush()
/obj/machinery/disposal/proc/newHolderDestination(obj/structure/disposalholder/H)
/obj/machinery/disposal/proc/flushAnimation()
/obj/machinery/disposal/proc/expel(obj/structure/disposalholder/H)
/obj/machinery/disposal/deconstruct(disassembled = TRUE)
/obj/machinery/disposal/get_dumping_location(obj/item/storage/source,mob/user)
/obj/machinery/disposal/storage_contents_dump_act(datum/component/storage/src_object, mob/user)
/obj/machinery/disposal/bin
	name = "disposal unit"
	desc = "A pneumatic waste disposal unit."
/obj/machinery/disposal/bin/attackby(obj/item/I, mob/user, params)
/obj/machinery/disposal/bin/ui_state(mob/user)
/obj/machinery/disposal/bin/ui_interact(mob/user, datum/tgui/ui)
/obj/machinery/disposal/bin/ui_data(mob/user)
/obj/machinery/disposal/bin/ui_act(action, params)
/obj/machinery/disposal/bin/hitby(atom/movable/AM, skipcatch, hitpush, blocked, datum/thrownthing/throwingdatum)
/obj/machinery/disposal/bin/flush()
/obj/machinery/disposal/bin/update_appearance(updates)
/obj/machinery/disposal/bin/update_overlays()
/obj/machinery/disposal/bin/proc/do_flush()
/obj/machinery/disposal/bin/process(delta_time)
/obj/machinery/disposal/bin/get_remote_view_fullscreens(mob/user)
/obj/machinery/disposal/delivery_chute
	name = "delivery chute"
	desc = "A chute for big and small packages alike!"
/obj/machinery/disposal/delivery_chute/Initialize(mapload, obj/structure/disposalconstruct/make_from)
/obj/machinery/disposal/delivery_chute/place_item_in_disposal(obj/item/I, mob/user)
/obj/machinery/disposal/delivery_chute/Bumped(atom/movable/AM) //Go straight into the chute
/atom/movable/proc/CanEnterDisposals()
/obj/projectile/CanEnterDisposals()
/obj/effect/CanEnterDisposals()
/obj/vehicle/sealed/mecha/CanEnterDisposals()
/obj/machinery/disposal/bin/newHolderDestination(obj/structure/disposalholder/H)
/obj/machinery/disposal/delivery_chute/newHolderDestination(obj/structure/disposalholder/H)
/obj/machinery/disposal/proc/on_rat_rummage(datum/source, mob/living/simple_animal/hostile/regalrat/king)
/obj/machinery/disposal/proc/trash_carbon(datum/source, mob/living/carbon/shover, mob/living/carbon/target, shove_blocked)
