/datum/component/storage/concrete
/datum/component/storage/concrete/Initialize()
/datum/component/storage/concrete/Destroy()
/datum/component/storage/concrete/master()
/datum/component/storage/concrete/real_location()
/datum/component/storage/concrete/PreTransfer()
/datum/component/storage/concrete/PostTransfer()
/datum/component/storage/concrete/_insert_physical_item(obj/item/I, override = FALSE)
/datum/component/storage/concrete/refresh_mob_views()
/datum/component/storage/concrete/emp_act(datum/source, severity)
/datum/component/storage/concrete/proc/on_slave_link(datum/component/storage/S)
/datum/component/storage/concrete/proc/on_slave_unlink(datum/component/storage/S)
/datum/component/storage/concrete/proc/on_contents_del(datum/source, atom/A)
/datum/component/storage/concrete/proc/on_deconstruct(datum/source, disassembled)
/datum/component/storage/concrete/can_see_contents()
/datum/component/storage/concrete/_removal_reset(atom/movable/thing)
/datum/component/storage/concrete/remove_from_storage(atom/movable/AM, atom/new_location)
/datum/component/storage/concrete/proc/slave_can_insert_object(datum/component/storage/slave, obj/item/I, stop_messages = FALSE, mob/M)
/datum/component/storage/concrete/proc/handle_item_insertion_from_slave(datum/component/storage/slave, obj/item/I, prevent_warning = FALSE, M)
/datum/component/storage/concrete/handle_item_insertion(obj/item/I, prevent_warning = FALSE, mob/M, datum/component/storage/remote) //Remote is null or the slave datum
/datum/component/storage/concrete/update_icon()
