/datum/computer_file/program/supermatter_monitor
/datum/computer_file/program/supermatter_monitor/Destroy()
/datum/computer_file/program/supermatter_monitor/process_tick()
/datum/computer_file/program/supermatter_monitor/run_program(mob/living/user)
/datum/computer_file/program/supermatter_monitor/kill_program(forced = FALSE)
/datum/computer_file/program/supermatter_monitor/proc/refresh()
/datum/computer_file/program/supermatter_monitor/proc/get_status()
/datum/computer_file/program/supermatter_monitor/proc/set_signals()
/datum/computer_file/program/supermatter_monitor/proc/clear_signals()
/datum/computer_file/program/supermatter_monitor/proc/send_alert()
/datum/computer_file/program/supermatter_monitor/proc/send_start_alert()
/datum/computer_file/program/supermatter_monitor/ui_data(mob/user)
/datum/computer_file/program/supermatter_monitor/ui_act(action, params)
/datum/computer_file/program/supermatter_monitor/proc/react_to_del(datum/source)
/datum/computer_file/program/supermatter_monitor/proc/clear_supermatter(matter)
