/obj/item/circuit_component/printer
	desc = "A component that prints a string input on a paper. Requires a shell and paper. \
/obj/item/circuit_component/printer/populate_ports()
/obj/item/circuit_component/printer/populate_options()
/obj/item/circuit_component/printer/Destroy()
/obj/item/circuit_component/printer/add_to(obj/item/integrated_circuit/add_to)
/obj/item/circuit_component/printer/removed_from(obj/item/integrated_circuit/removed_from)
/obj/item/circuit_component/printer/register_shell(atom/movable/shell)
/obj/item/circuit_component/printer/unregister_shell(atom/movable/shell)
/obj/item/circuit_component/printer/get_ui_notices()
/obj/item/circuit_component/printer/proc/handle_secondary_attackby(atom/movable/shell, obj/item/item, mob/living/attacker)
/obj/item/circuit_component/printer/proc/on_examine(datum/source, mob/user, list/examine_list)
/obj/item/circuit_component/printer/attackby(obj/item/item, mob/living/user, params)
/obj/item/circuit_component/printer/proc/load_paper(obj/item/paper/paper, mob/living/user)
/obj/item/circuit_component/printer/attack_self(mob/living/user)
/obj/item/circuit_component/printer/Exited(atom/movable/movable)
/obj/item/circuit_component/printer/pre_input_received(datum/port/input/port)
/obj/item/circuit_component/printer/proc/print_on_paper(datum/port/input/port)
/obj/item/circuit_component/printer/proc/eject_paper(datum/port/input/port, list/return_values)
