/datum/component/acid
/datum/component/acid/Initialize(_acid_power, _acid_volume, _max_volume=null)
/datum/component/acid/Destroy(force, silent)
/datum/component/acid/RegisterWithParent()
/datum/component/acid/UnregisterFromParent()
/datum/component/acid/InheritComponent(datum/component/C, i_am_original, _acid_power, _acid_volume)
/datum/component/acid/proc/set_volume(new_volume)
/datum/component/acid/process(delta_time)
/datum/component/acid/proc/process_obj(obj/target, delta_time)
/datum/component/acid/proc/process_mob(mob/living/target, delta_time)
/datum/component/acid/proc/process_turf(turf/target_turf, delta_time)
/datum/component/acid/proc/on_update_overlays(atom/parent_atom, list/overlays)
/datum/component/acid/proc/on_examine(atom/A, mob/user, list/examine_list)
/datum/component/acid/proc/on_clean(atom/A, clean_types)
/datum/component/acid/proc/on_expose_reagent(atom/parent_atom, datum/reagent/exposing_reagent, reac_volume)
/datum/component/acid/proc/on_attack_hand(atom/parent_atom, mob/living/carbon/user)
/datum/component/acid/proc/on_entered(datum/source, atom/movable/arrived, atom/old_loc, list/atom/old_locs)
