/datum/component/aquarium_content
/datum/component/aquarium_content/Initialize(property_type)
/datum/component/aquarium_content/PreTransfer()
/datum/component/aquarium_content/Destroy(force, silent)
/datum/component/aquarium_content/proc/enter_aquarium(datum/source, OldLoc, Dir, Forced)
/datum/component/aquarium_content/proc/is_ready_to_insert(obj/structure/aquarium/aquarium)
/datum/component/aquarium_content/proc/on_inserted(atom/aquarium)
/datum/component/aquarium_content/proc/on_surface_changed()
/datum/component/aquarium_content/proc/attack_reaction(datum/source, obj/item/thing, mob/user, params)
/datum/component/aquarium_content/proc/on_fluid_changed()
/datum/component/aquarium_content/proc/remove_visual_from_aquarium()
/datum/component/aquarium_content/proc/generate_base_vc()
/datum/component/aquarium_content/proc/generate_animation()
/datum/component/aquarium_content/proc/swim_animation()
/datum/component/aquarium_content/proc/dead_animation()
/proc/flop_animation(atom/movable/animation_target)
/datum/component/aquarium_content/proc/start_flopping()
/datum/component/aquarium_content/proc/stop_flopping()
/datum/component/aquarium_content/proc/set_vc_base_position()
/datum/component/aquarium_content/proc/on_removed(datum/source, atom/movable/gone, direction)
/datum/component/aquarium_content/proc/remove_from_aquarium()
/datum/component/aquarium_content/proc/on_tank_stasis()
