/datum/component/bloodysoles
/datum/component/bloodysoles/Initialize()
/datum/component/bloodysoles/proc/unregister()
/datum/component/bloodysoles/proc/is_obscured()
/datum/component/bloodysoles/proc/update_icon()
/datum/component/bloodysoles/proc/share_blood(obj/effect/decal/cleanable/pool)
/datum/component/bloodysoles/proc/find_pool_by_blood_state(turf/turfLoc, typeFilter = null)
/datum/component/bloodysoles/proc/add_parent_to_footprint(obj/effect/decal/cleanable/blood/footprints/FP)
/datum/component/bloodysoles/proc/on_equip(datum/source, mob/equipper, slot)
/datum/component/bloodysoles/proc/on_drop(datum/source, mob/dropper)
/datum/component/bloodysoles/proc/on_moved(datum/source, OldLoc, Dir, Forced)
/datum/component/bloodysoles/proc/on_step_blood(datum/source, obj/effect/decal/cleanable/pool)
/datum/component/bloodysoles/proc/on_clean(datum/source, clean_types)
/datum/component/bloodysoles/feet
/datum/component/bloodysoles/feet/Initialize()
/datum/component/bloodysoles/feet/update_icon()
/datum/component/bloodysoles/feet/add_parent_to_footprint(obj/effect/decal/cleanable/blood/footprints/FP)
/datum/component/bloodysoles/feet/is_obscured()
/datum/component/bloodysoles/feet/on_moved(datum/source, OldLoc, Dir, Forced)
/datum/component/bloodysoles/feet/on_step_blood(datum/source, obj/effect/decal/cleanable/pool)
/datum/component/bloodysoles/feet/proc/fix_soles()
/datum/component/bloodysoles/feet/proc/unequip_shoecover(datum/source)
/datum/component/bloodysoles/feet/proc/equip_shoecover(datum/source)
