/datum/component/curse_of_hunger
/datum/component/curse_of_hunger/Initialize(add_dropdel = FALSE)
/datum/component/curse_of_hunger/RegisterWithParent()
/datum/component/curse_of_hunger/UnregisterFromParent()
/datum/component/curse_of_hunger/proc/on_examine(datum/source, mob/user, list/examine_list)
/datum/component/curse_of_hunger/proc/on_equip(datum/source, mob/equipper, slot)
/datum/component/curse_of_hunger/proc/on_unequip(mob/living/unequipper, force, atom/newloc, no_move, invdrop, silent)
/datum/component/curse_of_hunger/proc/on_pickup(datum/source, mob/grabber)
/datum/component/curse_of_hunger/proc/on_drop(datum/source, mob/dropper)
/datum/component/curse_of_hunger/proc/the_curse_begins(mob/cursed)
/datum/component/curse_of_hunger/proc/the_curse_ends(mob/uncursed)
/datum/component/curse_of_hunger/proc/seek_new_target()
/datum/component/curse_of_hunger/process(delta_time)
/datum/component/curse_of_hunger/proc/test()
