/datum/component/deadchat_control
/datum/component/deadchat_control/Initialize(_deadchat_mode, _inputs, _input_cooldown = 12 SECONDS, _on_removal)
/datum/component/deadchat_control/Destroy(force, silent)
/datum/component/deadchat_control/proc/deadchat_react(mob/source, message)
/datum/component/deadchat_control/proc/democracy_loop()
/datum/component/deadchat_control/proc/count_democracy_votes()
/datum/component/deadchat_control/vv_edit_var(var_name, var_value)
/datum/component/deadchat_control/proc/orbit_begin(atom/source, atom/orbiter)
/datum/component/deadchat_control/proc/orbit_stop(atom/source, atom/orbiter)
/datum/component/deadchat_control/proc/handle_vv_topic(datum/source, mob/user, list/href_list)
/datum/component/deadchat_control/proc/async_handle_vv_topic(mob/user, list/href_list)
/datum/component/deadchat_control/proc/on_examine(atom/A, mob/user, list/examine_list)
/datum/component/deadchat_control/cardinal_movement/Initialize(_deadchat_mode, _inputs, _input_cooldown, _on_removal)
/datum/component/deadchat_control/immovable_rod/Initialize(_deadchat_mode, _inputs, _input_cooldown, _on_removal)
