/datum/component/automatic_fire
/datum/component/automatic_fire/Initialize(_autofire_shot_delay)
/datum/component/automatic_fire/Destroy()
/datum/component/automatic_fire/process(delta_time)
/datum/component/automatic_fire/proc/wake_up(datum/source, mob/user, slot)
/datum/component/automatic_fire/proc/autofire_on(client/usercli)
/datum/component/automatic_fire/proc/autofire_off(datum/source)
/datum/component/automatic_fire/proc/on_client_login(mob/source)
/datum/component/automatic_fire/proc/on_mouse_down(client/source, atom/_target, turf/location, control, params)
/datum/component/automatic_fire/proc/start_autofiring()
/datum/component/automatic_fire/proc/on_mouse_up(datum/source, atom/object, turf/location, control, params)
/datum/component/automatic_fire/proc/stop_autofiring(datum/source, atom/object, turf/location, control, params)
/datum/component/automatic_fire/proc/on_mouse_drag(client/source, atom/src_object, atom/over_object, turf/src_location, turf/over_location, src_control, over_control, params)
/datum/component/automatic_fire/proc/process_shot()
/obj/item/gun/proc/on_autofire_start(mob/living/shooter)
/obj/item/gun/proc/autofire_bypass_check(datum/source, client/clicker, atom/target, turf/location, control, params)
/obj/item/gun/proc/do_autofire(datum/source, atom/target, mob/living/shooter, params)
/obj/item/gun/proc/do_autofire_shot(datum/source, atom/target, mob/living/shooter, params)
