/datum/component/lockon_aiming
/datum/component/lockon_aiming/Initialize(range, list/typecache, amount, list/immune, datum/callback/when_locked, icon, icon_state, datum/callback/target_callback)
/datum/component/lockon_aiming/Destroy()
/datum/component/lockon_aiming/proc/show_visuals()
/datum/component/lockon_aiming/proc/clear_visuals()
/datum/component/lockon_aiming/proc/refresh_visuals()
/datum/component/lockon_aiming/proc/generate_lock_visuals()
/datum/component/lockon_aiming/proc/unlock_all(refresh_vis = TRUE)
/datum/component/lockon_aiming/proc/unlock(atom/A, refresh_vis = TRUE)
/datum/component/lockon_aiming/proc/lock(atom/A, refresh_vis = TRUE)
/datum/component/lockon_aiming/proc/add_immune_atom(atom/A)
/datum/component/lockon_aiming/proc/remove_immune_atom(atom/A)
/datum/component/lockon_aiming/process()
/datum/component/lockon_aiming/proc/autolock()
/datum/component/lockon_aiming/proc/can_target(atom/A)
/datum/component/lockon_aiming/proc/get_nearest(turf/T, list/typecache, amount, range)
