/datum/component/manual_blinking
/datum/component/manual_blinking/Initialize()
/datum/component/manual_blinking/Destroy(force, silent)
/datum/component/manual_blinking/RegisterWithParent()
/datum/component/manual_blinking/UnregisterFromParent()
/datum/component/manual_blinking/proc/restart()
/datum/component/manual_blinking/proc/pause()
/datum/component/manual_blinking/process()
/datum/component/manual_blinking/proc/check_added_organ(mob/who_cares, obj/item/organ/O)
/datum/component/manual_blinking/proc/check_removed_organ(mob/who_cares, obj/item/organ/O)
/datum/component/manual_blinking/proc/check_emote(mob/living/carbon/user, datum/emote/emote)
