/datum/component/material_container
/datum/component/material_container/Initialize(list/init_mats, max_amt = 0, _mat_container_flags=NONE, list/allowed_mats=init_mats, list/allowed_items, datum/callback/_insertion_check, datum/callback/_precondition, datum/callback/_after_insert)
/datum/component/material_container/Destroy(force, silent)
/datum/component/material_container/RegisterWithParent()
/datum/component/material_container/vv_edit_var(var_name, var_value)
/datum/component/material_container/proc/on_examine(datum/source, mob/user, list/examine_texts)
/datum/component/material_container/proc/on_attackby(datum/source, obj/item/I, mob/living/user)
/datum/component/material_container/proc/user_insert(obj/item/I, mob/living/user, breakdown_flags = mat_container_flags)
/datum/component/material_container/proc/insert_item(obj/item/I, multiplier = 1, stack_amt, breakdown_flags = mat_container_flags)
/datum/component/material_container/proc/insert_item_materials(obj/item/source, multiplier = 1, breakdown_flags = mat_container_flags)
/datum/component/material_container/proc/can_hold_material(datum/material/mat)
/datum/component/material_container/proc/insert_amount_mat(amt, datum/material/mat)
/datum/component/material_container/proc/use_amount_mat(amt, datum/material/mat)
/datum/component/material_container/proc/transer_amt_to(datum/component/material_container/T, amt, datum/material/mat)
/datum/component/material_container/proc/can_insert_amount_mat(amt, datum/material/mat)
/datum/component/material_container/proc/use_materials(list/mats, multiplier=1)
/datum/component/material_container/proc/retrieve_sheets(sheet_amt, datum/material/M, atom/target = null)
/datum/component/material_container/proc/retrieve_all(target = null)
/datum/component/material_container/proc/has_space(amt = 0)
/datum/component/material_container/proc/has_materials(list/mats, multiplier=1)
/datum/component/material_container/proc/get_categories(list/mats)
/datum/component/material_container/proc/has_enough_of_material(datum/material/req_mat, amount, multiplier=1)
/datum/component/material_container/proc/has_enough_of_category(category, amount, multiplier=1)
/datum/component/material_container/proc/amount2sheet(amt)
/datum/component/material_container/proc/sheet2amount(sheet_amt)
/datum/component/material_container/proc/get_item_material_amount(obj/item/I, breakdown_flags = mat_container_flags)
/datum/component/material_container/proc/get_material_amount(datum/material/mat)
/datum/component/material_container/ui_data(mob/user)
