/datum/component/nanites
/datum/component/nanites/Initialize(amount = 100, cloud = 0)
/datum/component/nanites/RegisterWithParent()
/datum/component/nanites/UnregisterFromParent()
/datum/component/nanites/Destroy()
/datum/component/nanites/InheritComponent(datum/component/nanites/new_nanites, i_am_original, amount, cloud)
/datum/component/nanites/process(delta_time)
/datum/component/nanites/proc/delete_nanites()
/datum/component/nanites/proc/sync(datum/signal_source, datum/component/nanites/source, full_overwrite = TRUE, copy_activation = FALSE)
/datum/component/nanites/proc/cloud_sync()
/datum/component/nanites/proc/add_program(datum/source, datum/nanite_program/new_program, datum/nanite_program/source_program)
/datum/component/nanites/proc/consume_nanites(amount, force = FALSE)
/datum/component/nanites/proc/adjust_nanites(datum/source, amount)
/datum/component/nanites/proc/reject_excess_nanites()
/datum/component/nanites/proc/set_nanite_bar(remove = FALSE)
/datum/component/nanites/proc/on_emp(datum/source, severity)
/datum/component/nanites/proc/on_shock(datum/source, shock_damage, siemens_coeff = 1, flags = NONE)
/datum/component/nanites/proc/on_minor_shock(datum/source)
/datum/component/nanites/proc/check_stealth(datum/source)
/datum/component/nanites/proc/on_death(datum/source, gibbed)
/datum/component/nanites/proc/receive_signal(datum/source, code, source = "an unidentified source")
/datum/component/nanites/proc/receive_comm_signal(datum/source, comm_code, comm_message, comm_source = "an unidentified source")
/datum/component/nanites/proc/check_viable_biotype()
/datum/component/nanites/proc/check_access(datum/source, obj/O)
/datum/component/nanites/proc/set_volume(datum/source, amount)
/datum/component/nanites/proc/set_max_volume(datum/source, amount)
/datum/component/nanites/proc/set_cloud(datum/source, amount)
/datum/component/nanites/proc/set_cloud_sync(datum/source, method)
/datum/component/nanites/proc/set_safety(datum/source, amount)
/datum/component/nanites/proc/set_regen(datum/source, amount)
/datum/component/nanites/proc/confirm_nanites()
/datum/component/nanites/proc/get_programs(datum/source, list/nanite_programs)
/datum/component/nanites/proc/add_research()
/datum/component/nanites/proc/nanite_scan(datum/source, mob/user, full_scan)
/datum/component/nanites/proc/nanite_ui_data(datum/source, list/data, scan_level)
