/datum/component/overlay_lighting
/datum/component/overlay_lighting/Initialize(_range, _power, _color, starts_on, is_directional)
/datum/component/overlay_lighting/RegisterWithParent()
/datum/component/overlay_lighting/UnregisterFromParent()
/datum/component/overlay_lighting/Destroy()
/datum/component/overlay_lighting/proc/clean_old_turfs()
/datum/component/overlay_lighting/proc/get_new_turfs()
/datum/component/overlay_lighting/proc/make_luminosity_update()
/datum/component/overlay_lighting/proc/add_dynamic_lumi()
/datum/component/overlay_lighting/proc/remove_dynamic_lumi()
/datum/component/overlay_lighting/proc/set_parent_attached_to(atom/movable/new_parent_attached_to)
/datum/component/overlay_lighting/proc/set_holder(atom/movable/new_holder)
/datum/component/overlay_lighting/proc/check_holder()
/datum/component/overlay_lighting/proc/on_holder_qdel(atom/movable/source, force)
/datum/component/overlay_lighting/proc/on_holder_moved(atom/movable/source, OldLoc, Dir, Forced)
/datum/component/overlay_lighting/proc/on_parent_moved(atom/movable/source, OldLoc, Dir, Forced)
/datum/component/overlay_lighting/proc/on_parent_attached_to_qdel(atom/movable/source, force)
/datum/component/overlay_lighting/proc/on_parent_attached_to_moved(atom/movable/source, OldLoc, Dir, Forced)
/datum/component/overlay_lighting/proc/set_range(atom/source, old_range)
/datum/component/overlay_lighting/proc/set_power(atom/source, old_power)
/datum/component/overlay_lighting/proc/set_color(atom/source, old_color)
/datum/component/overlay_lighting/proc/on_toggle(atom/source, old_value)
/datum/component/overlay_lighting/proc/on_light_flags_change(atom/source, old_flags)
/datum/component/overlay_lighting/proc/turn_on()
/datum/component/overlay_lighting/proc/turn_off()
/datum/component/overlay_lighting/proc/set_lum_power(new_lum_power)
/datum/component/overlay_lighting/proc/cast_directional_light()
/datum/component/overlay_lighting/proc/on_holder_dir_change(atom/movable/source, olddir, newdir)
/datum/component/overlay_lighting/proc/on_parent_dir_change(atom/movable/source, olddir, newdir)
/datum/component/overlay_lighting/proc/set_direction(newdir)
/datum/component/overlay_lighting/proc/on_parent_crafted(datum/source, atom/movable/new_craft)
/datum/component/overlay_lighting/proc/on_light_eater(datum/source, list/light_queue, datum/light_eater)
