/datum/component/pellet_cloud
/datum/component/pellet_cloud/Initialize(projectile_type=/obj/item/shrapnel, magnitude=5)
/datum/component/pellet_cloud/Destroy(force, silent)
/datum/component/pellet_cloud/RegisterWithParent()
/datum/component/pellet_cloud/UnregisterFromParent()
/datum/component/pellet_cloud/proc/create_casing_pellets(obj/item/ammo_casing/shell, atom/target, mob/living/user, fired_from, randomspread, spread, zone_override, params, distro)
/datum/component/pellet_cloud/proc/create_blast_pellets(obj/O, mob/living/triggerer)
/datum/component/pellet_cloud/proc/handle_martyrs(mob/living/punishable_triggerer)
/datum/component/pellet_cloud/proc/pellet_hit(obj/projectile/P, atom/movable/firer, atom/target, Angle, hit_zone)
/datum/component/pellet_cloud/proc/pellet_range(obj/projectile/P)
/datum/component/pellet_cloud/proc/pew(atom/target, landmine_victim)
/datum/component/pellet_cloud/proc/finalize()
/datum/component/pellet_cloud/proc/grenade_armed(obj/item/nade)
/datum/component/pellet_cloud/proc/grenade_dropped(obj/item/nade, mob/living/slick_willy)
/datum/component/pellet_cloud/proc/grenade_moved()
/datum/component/pellet_cloud/proc/grenade_uncrossed(datum/source, atom/movable/gone, direction)
/datum/component/pellet_cloud/proc/nullspace_parent()
/datum/component/pellet_cloud/proc/on_target_qdel(atom/target)
