/datum/component/simple_rotation
/datum/component/simple_rotation/Initialize(rotation_flags = NONE ,can_user_rotate,can_be_rotated,after_rotation)
/datum/component/simple_rotation/proc/add_signals()
/datum/component/simple_rotation/proc/add_verbs()
/datum/component/simple_rotation/proc/remove_verbs()
/datum/component/simple_rotation/proc/remove_signals()
/datum/component/simple_rotation/RegisterWithParent()
/datum/component/simple_rotation/PostTransfer()
/datum/component/simple_rotation/UnregisterFromParent()
/datum/component/simple_rotation/Destroy()
/datum/component/simple_rotation/ClearFromParent()
/datum/component/simple_rotation/proc/ExamineMessage(datum/source, mob/user, list/examine_list)
/datum/component/simple_rotation/proc/HandRot(datum/source, mob/user, rotation = default_rotation_direction)
/datum/component/simple_rotation/proc/WrenchRot(datum/source, obj/item/I, mob/living/user)
/datum/component/simple_rotation/proc/BaseRot(mob/user,rotation_type)
/datum/component/simple_rotation/proc/default_can_user_rotate(mob/living/user, rotation_type)
/datum/component/simple_rotation/proc/default_can_be_rotated(mob/user, rotation_type)
/datum/component/simple_rotation/proc/default_after_rotation(mob/user, rotation_type)
/atom/movable/proc/simple_rotate_clockwise()
/atom/movable/proc/simple_rotate_counterclockwise()
/atom/movable/proc/simple_rotate_flip()
