/datum/component/shell
/datum/component/shell/Initialize(unremovable_circuit_components, capacity, shell_flags, starting_circuit)
/datum/component/shell/RegisterWithParent()
/datum/component/shell/proc/set_unremovable_circuit_components(list/components)
/datum/component/shell/proc/save_component(datum/source, list/objects)
/datum/component/shell/proc/on_load(datum/source, obj/item/integrated_circuit/circuit, list/components)
/datum/component/shell/UnregisterFromParent()
/datum/component/shell/Destroy(force, silent)
/datum/component/shell/proc/on_object_deconstruct()
/datum/component/shell/proc/on_attack_ghost(datum/source, mob/dead/observer/ghost)
/datum/component/shell/proc/on_examine(atom/movable/source, mob/user, list/examine_text)
/datum/component/shell/proc/on_set_anchored(atom/movable/source, previous_value)
/datum/component/shell/proc/on_attack_by(atom/source, obj/item/item, mob/living/attacker)
/datum/component/shell/proc/set_locked(new_value)
/datum/component/shell/proc/on_multitool_act(atom/source, mob/user, obj/item/tool)
/datum/component/shell/proc/on_screwdriver_act(atom/source, mob/user, obj/item/tool)
/datum/component/shell/proc/on_circuit_moved(obj/item/integrated_circuit/circuit, atom/old_loc)
/datum/component/shell/proc/on_circuit_delete(datum/source)
/datum/component/shell/proc/on_circuit_add_component_manually(atom/source, obj/item/circuit_component/added_comp, mob/living/user)
/datum/component/shell/proc/override_power_usage(datum/source, power_to_use)
/datum/component/shell/proc/attach_circuit(obj/item/integrated_circuit/circuitboard, mob/living/user)
/datum/component/shell/proc/remove_circuit()
/datum/component/shell/proc/on_atom_usb_cable_try_attach(atom/source, obj/item/usb_cable/usb_cable, mob/user)
/datum/component/shell/proc/is_authorized(mob/user)
