/datum/component/singularity
/datum/component/singularity/Initialize(
/datum/component/singularity/RegisterWithParent()
/datum/component/singularity/Destroy(force, silent)
/datum/component/singularity/UnregisterFromParent()
/datum/component/singularity/process(delta_time)
/datum/component/singularity/proc/block_blob()
/datum/component/singularity/proc/on_entered(datum/source, atom/movable/arrived, atom/old_loc, list/atom/old_locs)
/datum/component/singularity/proc/consume(datum/source, atom/thing)
/datum/component/singularity/proc/consume_attack(datum/source, mob/user)
/datum/component/singularity/proc/consume_attackby(datum/source, obj/item/item, mob/user)
/datum/component/singularity/proc/consume_bullets(datum/source, obj/projectile/projectile)
/datum/component/singularity/proc/default_singularity_act(atom/thing)
/datum/component/singularity/proc/eat()
/datum/component/singularity/proc/move()
/datum/component/singularity/proc/moved(datum/source, atom/new_location)
/datum/component/singularity/proc/can_move(turf/to_move)
/datum/component/singularity/proc/check_turfs_in(direction, steps)
/datum/component/singularity/proc/admin_investigate_setup()
/datum/component/singularity/proc/bluespace_reaction()
