/datum/component/spirit_holding
/datum/component/spirit_holding/Initialize()
/datum/component/spirit_holding/Destroy(force, silent)
/datum/component/spirit_holding/RegisterWithParent()
/datum/component/spirit_holding/UnregisterFromParent()
/datum/component/spirit_holding/proc/on_examine(datum/source, mob/user, list/examine_list)
/datum/component/spirit_holding/proc/on_attack_self(datum/source, mob/user)
/datum/component/spirit_holding/proc/attempt_spirit_awaken(mob/awakener)
/datum/component/spirit_holding/proc/block_buckle_message(datum/source, mob/living/user, direction)
/datum/component/spirit_holding/proc/on_bible_smacked(datum/source, mob/living/user, direction)
/datum/component/spirit_holding/proc/attempt_exorcism(mob/exorcist)
/datum/component/spirit_holding/proc/on_destroy(datum/source)
