/datum/component/tackler
/datum/component/tackler/Initialize(stamina_cost = 25, base_knockdown = 1 SECONDS, range = 4, speed = 1, skill_mod = 0, min_distance = min_distance)
/datum/component/tackler/Destroy()
/datum/component/tackler/RegisterWithParent()
/datum/component/tackler/UnregisterFromParent()
/datum/component/tackler/proc/registerTackle(mob/living/carbon/user, datum/thrownthing/TT)
/datum/component/tackler/proc/checkTackle(mob/living/carbon/user, atom/A, list/modifiers)
/datum/component/tackler/proc/sack(mob/living/carbon/user, atom/hit)
/datum/component/tackler/proc/rollTackle(mob/living/carbon/target)
/datum/component/tackler/proc/splat(mob/living/carbon/user, atom/hit)
/datum/component/tackler/proc/resetTackle()
/datum/component/tackler/proc/splatWindow(mob/living/carbon/user, obj/structure/window/W)
/datum/component/tackler/proc/delayedSmash(obj/structure/window/W)
/datum/component/tackler/proc/checkObstacle(mob/living/carbon/owner)
