/datum/component/uplink
/datum/component/uplink/Initialize(_owner, _lockable = TRUE, _enabled = FALSE, uplink_flag = UPLINK_TRAITORS, starting_tc = TELECRYSTALS_DEFAULT)
/datum/component/uplink/InheritComponent(datum/component/uplink/U)
/datum/component/uplink/Destroy()
/datum/component/uplink/proc/update_items(user)
/datum/component/uplink/proc/update_sales(updated_items)
/datum/component/uplink/proc/update_special_equipment(mob/user, updated_items)
	name = capitalize(name_words[i])
/datum/component/uplink/proc/LoadTC(mob/user, obj/item/stack/telecrystal/TC, silent = FALSE)
/datum/component/uplink/proc/OnAttackBy(datum/source, obj/item/I, mob/user)
/datum/component/uplink/proc/interact(datum/source, mob/user)
/datum/component/uplink/ui_state(mob/user)
/datum/component/uplink/ui_interact(mob/user, datum/tgui/ui)
/datum/component/uplink/ui_data(mob/user)
/datum/component/uplink/ui_static_data(mob/user)
/datum/component/uplink/ui_act(action, params)
/datum/component/uplink/proc/MakePurchase(mob/user, datum/uplink_item/U)
/datum/component/uplink/proc/implant_activation()
/datum/component/uplink/proc/implanting(datum/source, list/arguments)
/datum/component/uplink/proc/old_implant(datum/source, list/arguments, obj/item/implant/new_implant)
/datum/component/uplink/proc/new_implant(datum/source, datum/component/uplink/uplink)
/datum/component/uplink/proc/new_ringtone(datum/source, mob/living/user, new_ring_text)
/datum/component/uplink/proc/check_detonate()
/datum/component/uplink/proc/new_frequency(datum/source, list/arguments)
/datum/component/uplink/proc/pen_rotation(datum/source, degrees, mob/living/carbon/user)
/datum/component/uplink/proc/setup_unlock_code()
/datum/component/uplink/proc/generate_code()
/datum/component/uplink/proc/failsafe(mob/living/carbon/user)
