/datum/component/usb_port
/datum/component/usb_port/Initialize(list/circuit_component_types)
/datum/component/usb_port/proc/set_circuit_components(list/components)
/datum/component/usb_port/RegisterWithParent()
/datum/component/usb_port/UnregisterFromParent()
/datum/component/usb_port/proc/save_component(datum/source, list/objects)
/datum/component/usb_port/proc/on_load(datum/source, obj/item/integrated_circuit/circuit, list/components)
/datum/component/usb_port/Destroy()
/datum/component/usb_port/proc/unregister_circuit_signals()
/datum/component/usb_port/proc/unregister_physical_signals()
/datum/component/usb_port/proc/attach_circuit_components(obj/item/integrated_circuit/circuitboard)
/datum/component/usb_port/proc/on_examine(datum/source, mob/user, list/examine_text)
/datum/component/usb_port/proc/on_examine_shell(datum/source, mob/user, list/examine_text)
/datum/component/usb_port/proc/on_atom_usb_cable_try_attach(datum/source, obj/item/usb_cable/connecting_cable, mob/user)
/datum/component/usb_port/proc/set_physical_object(atom/movable/new_physical_object)
/datum/component/usb_port/proc/on_set_shell(datum/source, atom/movable/new_shell)
/datum/component/usb_port/proc/on_moved()
/datum/component/usb_port/proc/on_circuit_deleting()
/datum/component/usb_port/proc/on_circuit_component_removed(datum/source)
/datum/component/usb_port/proc/on_circuit_shell_removed()
/datum/component/usb_port/proc/detach()
