/datum/component/wet_floor
/datum/component/wet_floor/InheritComponent(datum/newcomp, orig, strength, duration_minimum, duration_add, duration_maximum, _permanent)
/datum/component/wet_floor/Initialize(strength, duration_minimum, duration_add, duration_maximum, _permanent = FALSE)
/datum/component/wet_floor/RegisterWithParent()
/datum/component/wet_floor/UnregisterFromParent()
/datum/component/wet_floor/Destroy()
/datum/component/wet_floor/proc/update_overlay()
/datum/component/wet_floor/proc/AfterSlip(mob/living/L)
/datum/component/wet_floor/proc/update_flags()
/datum/component/wet_floor/proc/dry(datum/source, strength = TURF_WET_WATER, immediate = FALSE, duration_decrease = INFINITY)
/datum/component/wet_floor/proc/max_time_left()
/datum/component/wet_floor/process()
/datum/component/wet_floor/proc/update_strength()
/datum/component/wet_floor/proc/is_wet()
/datum/component/wet_floor/PreTransfer()
/datum/component/wet_floor/PostTransfer()
/datum/component/wet_floor/proc/add_wet(type, duration_minimum = 0, duration_add = 0, duration_maximum = MAXIMUM_WET_TIME, _permanent = FALSE)
/datum/component/wet_floor/proc/_do_add_wet(type, duration_minimum, duration_add, duration_maximum)
/datum/component/wet_floor/proc/gc(on_init = FALSE)
/datum/component/wet_floor/proc/check(force_update = FALSE)
