/mob/living/simple_animal/revenant
	name = "revenant"
	desc = "A malevolent spirit."
/mob/living/simple_animal/revenant/Initialize(mapload)
/mob/living/simple_animal/revenant/canUseTopic(atom/movable/M, be_close=FALSE, no_dexterity=FALSE, no_tk=FALSE, no_hands = FALSE, floor_okay=FALSE)
/mob/living/simple_animal/revenant/proc/random_revenant_name()
	name = built_name
/mob/living/simple_animal/revenant/Login()
/mob/living/simple_animal/revenant/Life(delta_time = SSMOBS_DT, times_fired)
/mob/living/simple_animal/revenant/get_status_tab_items()
/mob/living/simple_animal/revenant/update_health_hud()
/mob/living/simple_animal/revenant/med_hud_set_health()
/mob/living/simple_animal/revenant/med_hud_set_status()
/mob/living/simple_animal/revenant/say(message, bubble_type, list/spans = list(), sanitize = TRUE, datum/language/language = null, ignore_spam = FALSE, forced = null, filterproof = null)
/mob/living/simple_animal/revenant/ex_act(severity, target)
/mob/living/simple_animal/revenant/blob_act(obj/structure/blob/B)
/mob/living/simple_animal/revenant/singularity_act()
/mob/living/simple_animal/revenant/narsie_act()
/mob/living/simple_animal/revenant/bullet_act()
/mob/living/simple_animal/revenant/proc/on_baned(obj/item/weapon, mob/living/user)
/mob/living/simple_animal/revenant/proc/reset_inhibit()
/mob/living/simple_animal/revenant/adjustHealth(amount, updating_health = TRUE, forced = FALSE)
/mob/living/simple_animal/revenant/dust(just_ash, drop_items, force)
/mob/living/simple_animal/revenant/gib()
/mob/living/simple_animal/revenant/death()
/mob/living/simple_animal/revenant/proc/reveal(time)
/mob/living/simple_animal/revenant/proc/stun(time)
/mob/living/simple_animal/revenant/proc/update_spooky_icon()
/mob/living/simple_animal/revenant/proc/castcheck(essence_cost)
/mob/living/simple_animal/revenant/proc/unlock(essence_cost)
/mob/living/simple_animal/revenant/proc/change_essence_amount(essence_amt, silent = FALSE, source = null)
/mob/living/simple_animal/revenant/proc/death_reset()
/mob/living/simple_animal/revenant/orbit(atom/target)
/mob/living/simple_animal/revenant/Moved(atom/OldLoc)
/mob/living/simple_animal/revenant/stop_orbit(datum/component/orbiter/orbits)
/mob/living/simple_animal/revenant/proc/incorporeal_move_check(atom/destination)
/obj/item/ectoplasm/revenant
	name = "glimmering residue"
	desc = "A pile of fine blue dust. Small tendrils of violet mist swirl around it."
/obj/item/ectoplasm/revenant/Initialize(mapload)
/obj/item/ectoplasm/revenant/proc/scatter()
/obj/item/ectoplasm/revenant/proc/try_reform()
/obj/item/ectoplasm/revenant/attack_self(mob/user)
/obj/item/ectoplasm/revenant/throw_impact(atom/hit_atom, datum/thrownthing/throwingdatum)
/obj/item/ectoplasm/revenant/examine(mob/user)
/obj/item/ectoplasm/revenant/proc/reform()
/obj/item/ectoplasm/revenant/suicide_act(mob/user)
/obj/item/ectoplasm/revenant/Destroy()
/datum/objective/revenant
/datum/objective/revenant/New()
/datum/objective/revenant/check_completion()
/datum/objective/revenant_fluff
/datum/objective/revenant_fluff/New()
/datum/objective/revenant_fluff/check_completion()
