/mob/living/silicon/ai/attackby(obj/item/W, mob/user, params)
/mob/living/silicon/ai/attack_alien(mob/living/carbon/alien/humanoid/user, list/modifiers)
/mob/living/silicon/ai/attack_slime(mob/living/simple_animal/slime/user)
/mob/living/silicon/ai/blob_act(obj/structure/blob/B)
/mob/living/silicon/ai/emp_act(severity)
/mob/living/silicon/ai/ex_act(severity, target)
/mob/living/silicon/ai/bullet_act(obj/projectile/Proj)
/mob/living/silicon/ai/flash_act(intensity = 1, override_blindness_check = 0, affect_silicon = 0, visual = 0, type = /atom/movable/screen/fullscreen/flash, length = 25)
