/mob/living/silicon/ai/say(message, bubble_type,list/spans = list(), sanitize = TRUE, datum/language/language = null, ignore_spam = FALSE, forced = null, filterproof = null)
/mob/living/silicon/ai/compose_track_href(atom/movable/speaker, namepart)
/mob/living/silicon/ai/compose_job(atom/movable/speaker, message_langs, raw_message, radio_freq)
/mob/living/silicon/ai/IsVocal()
/mob/living/silicon/ai/radio(message, list/message_mods = list(), list/spans, language)
/mob/living/silicon/ai/proc/holopad_talk(message, language)
/mob/living/silicon/ai/verb/announcement_help()
/mob/living/silicon/ai/proc/announcement()
/proc/play_vox_word(word, z_level, mob/only_listener)
