/mob/camera/blob/proc/can_buy(cost = 15)
/mob/camera/blob/proc/place_blob_core(placement_override = BLOB_NORMAL_PLACEMENT, pop_override = FALSE)
/mob/camera/blob/proc/transport_core()
/mob/camera/blob/proc/jump_to_node()
/mob/camera/blob/proc/createSpecial(price, blobstrain, minSeparation, needsNode, turf/T)
/mob/camera/blob/proc/toggle_node_req()
/mob/camera/blob/proc/create_shield(turf/T)
/mob/camera/blob/proc/create_blobbernaut()
/mob/camera/blob/proc/relocate_core()
/mob/camera/blob/proc/remove_blob(turf/T)
/mob/camera/blob/proc/expand_blob(turf/T)
/mob/camera/blob/proc/rally_spores(turf/T)
/mob/camera/blob/proc/strain_reroll()
/mob/camera/blob/proc/open_reroll_menu()
/mob/camera/blob/proc/blob_help()
