/datum/ui_state/notcontained_state/can_use_topic(atom/src_object, mob/user)
/mob/proc/notcontained_can_use_topic(src_object)
/mob/living/notcontained_can_use_topic(atom/src_object)
/mob/living/silicon/notcontained_can_use_topic(src_object)
/mob/living/simple_animal/drone/notcontained_can_use_topic(src_object)
