/datum/ui_state/physical/can_use_topic(src_object, mob/user)
/mob/proc/physical_can_use_topic(src_object)
/mob/living/physical_can_use_topic(src_object)
/mob/living/silicon/physical_can_use_topic(src_object)
/mob/living/silicon/ai/physical_can_use_topic(src_object)
/datum/ui_state/physical_obscured_state/can_use_topic(src_object, mob/user)
/mob/proc/physical_obscured_can_use_topic(src_object)
/mob/living/physical_obscured_can_use_topic(src_object)
/mob/living/silicon/physical_obscured_can_use_topic(src_object)
/mob/living/silicon/ai/physical_obscured_can_use_topic(src_object)
