/atom/movable
/atom/movable/attack_hand(mob/living/user, list/modifiers)
/atom/movable/attackby(obj/item/attacking_item, mob/user, params)
/atom/movable/attack_robot(mob/living/user)
/atom/movable/MouseDrop_T(mob/living/M, mob/living/user)
/atom/movable/proc/mouse_buckle_handling(mob/living/M, mob/living/user)
/atom/movable/proc/has_buckled_mobs()
/atom/movable/proc/buckle_mob(mob/living/M, force = FALSE, check_loc = TRUE, buckle_mob_flags= NONE)
/obj/buckle_mob(mob/living/M, force = FALSE, check_loc = TRUE)
/atom/movable/proc/unbuckle_mob(mob/living/buckled_mob, force = FALSE, can_fall = TRUE)
/atom/movable/proc/on_set_anchored(atom/movable/source, anchorvalue)
/atom/movable/proc/unbuckle_all_mobs(force=FALSE)
/atom/movable/proc/post_buckle_mob(mob/living/M)
/atom/movable/proc/post_unbuckle_mob(mob/living/M)
/atom/movable/proc/is_buckle_possible(mob/living/target, force = FALSE, check_loc = TRUE)
/atom/movable/proc/is_user_buckle_possible(mob/living/target, mob/user, check_loc = TRUE)
/atom/movable/proc/user_buckle_mob(mob/living/M, mob/user, check_loc = TRUE)
/atom/movable/proc/user_unbuckle_mob(mob/living/buckled_mob, mob/user)
