/datum/controller/master
	name = "Master"
/datum/controller/master/New()
/datum/controller/master/Destroy()
/datum/controller/master/Shutdown()
/proc/Recreate_MC()
/datum/controller/master/Recover()
/datum/controller/master/Initialize(delay, init_sss, tgs_prime)
/datum/controller/master/proc/SetRunLevel(new_runlevel)
/datum/controller/master/proc/StartProcessing(delay)
/datum/controller/master/proc/Loop()
/datum/controller/master/proc/CheckQueue(list/subsystemstocheck)
/datum/controller/master/proc/RunQueue()
/datum/controller/master/proc/SoftReset(list/ticker_SS, list/runlevel_SS)
/datum/controller/master/proc/laggy_byond_map_update_incoming()
/datum/controller/master/stat_entry(msg)
/datum/controller/master/StartLoadingMap()
/datum/controller/master/StopLoadingMap(bounds = null)
/datum/controller/master/proc/UpdateTickRate()
/datum/controller/master/proc/OnConfigLoad()
