/obj/item/bodypart
	name = "limb"
	desc = "Why is it detached..."
/obj/item/bodypart/Initialize(mapload)
/obj/item/bodypart/Destroy()
/obj/item/bodypart/examine(mob/user)
/obj/item/bodypart/blob_act()
/obj/item/bodypart/attack(mob/living/carbon/victim, mob/user)
/obj/item/bodypart/attackby(obj/item/weapon, mob/user, params)
/obj/item/bodypart/throw_impact(atom/hit_atom, datum/thrownthing/throwingdatum)
/obj/item/bodypart/proc/drop_organs(mob/user, violent_removal)
/obj/item/bodypart/proc/get_organs()
/obj/item/bodypart/proc/on_life(delta_time, times_fired, stam_regen)
/obj/item/bodypart/proc/receive_damage(brute = 0, burn = 0, stamina = 0, blocked = 0, updating_health = TRUE, required_status = null, wound_bonus = 0, bare_wound_bonus = 0, sharpness = NONE) // maybe separate BRUTE_SHARP and BRUTE_OTHER eventually somehow hmm
/obj/item/bodypart/proc/painless_wound_roll(wounding_type, phantom_wounding_dmg, wound_bonus, bare_wound_bonus, sharpness=NONE)
/obj/item/bodypart/proc/check_wounding(woundtype, damage, wound_bonus, bare_wound_bonus)
/obj/item/bodypart/proc/force_wound_upwards(specific_woundtype, smited = FALSE)
/obj/item/bodypart/proc/check_woundings_mods(wounding_type, damage, wound_bonus, bare_wound_bonus)
/obj/item/bodypart/proc/heal_damage(brute, burn, stamina, required_status, updating_health = TRUE)
/obj/item/bodypart/proc/set_brute_dam(new_value)
/obj/item/bodypart/proc/set_burn_dam(new_value)
/obj/item/bodypart/proc/set_stamina_dam(new_value)
/obj/item/bodypart/proc/get_damage(include_stamina = FALSE)
/obj/item/bodypart/proc/update_disabled()
/obj/item/bodypart/proc/set_disabled(new_disabled)
/obj/item/bodypart/proc/set_owner(new_owner)
/obj/item/bodypart/proc/set_can_be_disabled(new_can_be_disabled)
/obj/item/bodypart/proc/on_paralysis_trait_gain(obj/item/bodypart/source)
/obj/item/bodypart/proc/on_paralysis_trait_loss(obj/item/bodypart/source)
/obj/item/bodypart/proc/on_owner_nolimbdisable_trait_gain(mob/living/carbon/source)
/obj/item/bodypart/proc/on_owner_nolimbdisable_trait_loss(mob/living/carbon/source)
/obj/item/bodypart/proc/update_bodypart_damage_state()
/obj/item/bodypart/proc/change_bodypart_status(new_limb_status, heal_limb, change_icon_to_default)
/obj/item/bodypart/proc/is_organic_limb()
/obj/item/bodypart/proc/update_limb(dropping_limb, mob/living/carbon/source)
/obj/item/bodypart/proc/update_icon_dropped()
/obj/item/bodypart/proc/get_limb_icon(dropped)
/obj/item/bodypart/deconstruct(disassembled = TRUE)
/obj/item/bodypart/proc/get_wound_type(checking_type)
/obj/item/bodypart/proc/update_wounds(replaced = FALSE)
/obj/item/bodypart/proc/get_bleed_rate()
/obj/item/bodypart/proc/apply_gauze(obj/item/stack/gauze)
/obj/item/bodypart/proc/seep_gauze(seep_amt = 0)
/obj/item/bodypart/proc/change_bodypart(obj/item/bodypart/new_type)
