/obj/item/bodypart/proc/can_dismember(obj/item/item)
/obj/item/bodypart/proc/dismember(dam_type = BRUTE, silent=TRUE)
/obj/item/bodypart/chest/dismember()
/obj/item/bodypart/proc/drop_limb(special, dismembered)
/obj/item/bodypart/proc/get_mangled_state()
/obj/item/bodypart/proc/try_dismember(wounding_type, wounding_dmg, wound_bonus, bare_wound_bonus)
/obj/item/organ/proc/transfer_to_limb(obj/item/bodypart/bodypart, mob/living/carbon/bodypart_owner)
/obj/item/organ/brain/transfer_to_limb(obj/item/bodypart/head/head, mob/living/carbon/human/head_owner)
/obj/item/organ/eyes/transfer_to_limb(obj/item/bodypart/head/head, mob/living/carbon/human/head_owner)
/obj/item/organ/ears/transfer_to_limb(obj/item/bodypart/head/head, mob/living/carbon/human/head_owner)
/obj/item/organ/tongue/transfer_to_limb(obj/item/bodypart/head/head, mob/living/carbon/human/head_owner)
/obj/item/bodypart/chest/drop_limb(special)
/obj/item/bodypart/r_arm/drop_limb(special)
/obj/item/bodypart/l_arm/drop_limb(special)
/obj/item/bodypart/r_leg/drop_limb(special)
/obj/item/bodypart/l_leg/drop_limb(special) //copypasta
/obj/item/bodypart/head/drop_limb(special)
	name = "[owner.real_name]'s head"
/obj/item/bodypart/proc/replace_limb(mob/living/carbon/limb_owner, special)
/obj/item/bodypart/head/replace_limb(mob/living/carbon/head_owner, special)
/obj/item/bodypart/proc/attach_limb(mob/living/carbon/new_limb_owner, special)
/obj/item/bodypart/head/attach_limb(mob/living/carbon/new_head_owner, special = FALSE, abort = FALSE)
	name = initial(name)
/mob/living/proc/regenerate_limbs(noheal = FALSE, list/excluded_zones = list())
/mob/living/carbon/regenerate_limbs(noheal = FALSE, list/excluded_zones = list())
/mob/living/proc/regenerate_limb(limb_zone, noheal)
/mob/living/carbon/regenerate_limb(limb_zone, noheal)
