/mob/living/proc/get_bodypart(zone)
/mob/living/carbon/get_bodypart(zone)
/mob/living/carbon/has_hand_for_held_index(i)
/mob/proc/get_active_hand()
/mob/living/carbon/get_active_hand()
/mob/proc/has_left_hand(check_disabled = TRUE)
/mob/living/carbon/has_left_hand(check_disabled = TRUE)
/mob/living/carbon/alien/larva/has_left_hand()
/mob/proc/has_right_hand(check_disabled = TRUE)
/mob/living/carbon/has_right_hand(check_disabled = TRUE)
/mob/living/carbon/alien/larva/has_right_hand()
/mob/living/proc/get_missing_limbs()
/mob/living/carbon/get_missing_limbs()
/mob/living/carbon/alien/larva/get_missing_limbs()
/mob/living/proc/get_disabled_limbs()
/mob/living/carbon/get_disabled_limbs()
/mob/living/carbon/alien/larva/get_disabled_limbs()
/mob/living/carbon/proc/remove_embedded_object(obj/item/embedded)
/mob/living/carbon/proc/remove_all_embedded_objects()
/mob/living/carbon/proc/has_embedded_objects(include_harmless=FALSE)
/mob/living/carbon/proc/newBodyPart(zone, robotic, fixed_icon)
/mob/living/carbon/human/newBodyPart(zone, robotic, fixed_icon)
/mob/living/carbon/alien/larva/newBodyPart(zone, robotic, fixed_icon)
/mob/living/carbon/alien/humanoid/newBodyPart(zone, robotic, fixed_icon)
/proc/skintone2hex(skin_tone)
/mob/living/carbon/proc/Digitigrade_Leg_Swap(swap_back)
