/obj/vehicle/sealed/mecha/proc/get_armour_facing(relative_dir)
/obj/vehicle/sealed/mecha/take_damage(damage_amount, damage_type = BRUTE, damage_flag = 0, sound_effect = 1, attack_dir)
/obj/vehicle/sealed/mecha/run_atom_armor(damage_amount, damage_type, damage_flag = 0, attack_dir)
/obj/vehicle/sealed/mecha/attack_hand(mob/living/user, list/modifiers)
/obj/vehicle/sealed/mecha/attack_paw(mob/user, list/modifiers)
/obj/vehicle/sealed/mecha/attack_alien(mob/living/user, list/modifiers)
/obj/vehicle/sealed/mecha/attack_animal(mob/living/simple_animal/user, list/modifiers)
/obj/vehicle/sealed/mecha/hulk_damage()
/obj/vehicle/sealed/mecha/attack_hulk(mob/living/carbon/human/user)
/obj/vehicle/sealed/mecha/blob_act(obj/structure/blob/B)
/obj/vehicle/sealed/mecha/attack_tk()
/obj/vehicle/sealed/mecha/hitby(atom/movable/AM, skipcatch, hitpush, blocked, datum/thrownthing/throwingdatum) //wrapper
/obj/vehicle/sealed/mecha/bullet_act(obj/projectile/Proj) //wrapper
/obj/vehicle/sealed/mecha/ex_act(severity, target)
/obj/vehicle/sealed/mecha/contents_explosion(severity, target)
/obj/vehicle/sealed/mecha/handle_atom_del(atom/A)
/obj/vehicle/sealed/mecha/emp_act(severity)
/obj/vehicle/sealed/mecha/should_atmos_process(datum/gas_mixture/air, exposed_temperature)
/obj/vehicle/sealed/mecha/atmos_expose(datum/gas_mixture/air, exposed_temperature)
/obj/vehicle/sealed/mecha/attackby(obj/item/W, mob/user, params)
/obj/vehicle/sealed/mecha/wrench_act(mob/living/user, obj/item/I)
/obj/vehicle/sealed/mecha/crowbar_act(mob/living/user, obj/item/I)
/obj/vehicle/sealed/mecha/screwdriver_act(mob/living/user, obj/item/I)
/obj/vehicle/sealed/mecha/welder_act(mob/living/user, obj/item/W)
/obj/vehicle/sealed/mecha/proc/mech_toxin_damage(mob/living/target)
/obj/vehicle/sealed/mecha/mech_melee_attack(obj/vehicle/sealed/mecha/M, mob/living/user)
/obj/vehicle/sealed/mecha/proc/full_repair(charge_cell)
/obj/vehicle/sealed/mecha/narsie_act()
/obj/vehicle/sealed/mecha/do_attack_animation(atom/A, visual_effect_icon, obj/item/used_item, no_effect)
/obj/vehicle/sealed/mecha/atom_destruction()
