/datum/buildmode_mode
/datum/buildmode_mode/New(datum/buildmode/BM)
/datum/buildmode_mode/Destroy()
/datum/buildmode_mode/proc/enter_mode(datum/buildmode/BM)
/datum/buildmode_mode/proc/exit_mode(datum/buildmode/BM)
/datum/buildmode_mode/proc/get_button_iconstate()
/datum/buildmode_mode/proc/show_help(client/c)
/datum/buildmode_mode/proc/change_settings(client/c)
/datum/buildmode_mode/proc/Reset()
/datum/buildmode_mode/proc/select_tile(turf/T, corner_to_select)
/datum/buildmode_mode/proc/highlight_region(region)
/datum/buildmode_mode/proc/deselect_region()
/datum/buildmode_mode/proc/handle_click(client/c, params, object)
/datum/buildmode_mode/proc/handle_selected_area(client/c, params)
