/obj/effect/turf_decal/stripes/line
/obj/effect/turf_decal/stripes/end
/obj/effect/turf_decal/stripes/corner
/obj/effect/turf_decal/stripes/box
/obj/effect/turf_decal/stripes/full
/obj/effect/turf_decal/stripes/asteroid/line
/obj/effect/turf_decal/stripes/asteroid/end
/obj/effect/turf_decal/stripes/asteroid/corner
/obj/effect/turf_decal/stripes/asteroid/box
/obj/effect/turf_decal/stripes/asteroid/full
/obj/effect/turf_decal/stripes/white/line
/obj/effect/turf_decal/stripes/white/end
/obj/effect/turf_decal/stripes/white/corner
/obj/effect/turf_decal/stripes/white/box
/obj/effect/turf_decal/stripes/white/full
/obj/effect/turf_decal/stripes/red/line
/obj/effect/turf_decal/stripes/red/end
/obj/effect/turf_decal/stripes/red/corner
/obj/effect/turf_decal/stripes/red/box
/obj/effect/turf_decal/stripes/red/full
/obj/effect/turf_decal/delivery
/obj/effect/turf_decal/delivery/white
/obj/effect/turf_decal/delivery/red
/obj/effect/turf_decal/bot
/obj/effect/turf_decal/bot/right
/obj/effect/turf_decal/bot/left
/obj/effect/turf_decal/bot_white
/obj/effect/turf_decal/bot_white/right
/obj/effect/turf_decal/bot_white/left
/obj/effect/turf_decal/bot_red
/obj/effect/turf_decal/bot_red/right
/obj/effect/turf_decal/bot_red/left
/obj/effect/turf_decal/loading_area
/obj/effect/turf_decal/loading_area/white
/obj/effect/turf_decal/loading_area/red
/obj/effect/turf_decal/caution
/obj/effect/turf_decal/caution/white
/obj/effect/turf_decal/caution/red
/obj/effect/turf_decal/caution/stand_clear
/obj/effect/turf_decal/caution/stand_clear/white
/obj/effect/turf_decal/caution/stand_clear/red
/obj/effect/turf_decal/arrows
/obj/effect/turf_decal/arrows/white
/obj/effect/turf_decal/arrows/red
/obj/effect/turf_decal/box
/obj/effect/turf_decal/box/corners
/obj/effect/turf_decal/box/white
/obj/effect/turf_decal/box/white/corners
/obj/effect/turf_decal/box/red
/obj/effect/turf_decal/box/red/corners
/obj/effect/turf_decal/plaque
/obj/effect/turf_decal/raven_ship_sign
/obj/effect/turf_decal/raven/one
/obj/effect/turf_decal/raven/two
/obj/effect/turf_decal/raven/three
/obj/effect/turf_decal/raven/four
/obj/effect/turf_decal/raven/five
/obj/effect/turf_decal/raven/six
/obj/effect/turf_decal/raven/seven
/obj/effect/turf_decal/raven/eight
/obj/effect/turf_decal/raven/nine
/obj/effect/turf_decal/mining
/obj/effect/turf_decal/mining/survival
/obj/effect/turf_decal/siding
/obj/effect/turf_decal/siding/white
/obj/effect/turf_decal/siding/white/corner
/obj/effect/turf_decal/siding/white/end
/obj/effect/turf_decal/siding/red
/obj/effect/turf_decal/siding/red/corner
/obj/effect/turf_decal/siding/red/end
/obj/effect/turf_decal/siding/green
/obj/effect/turf_decal/siding/green/corner
/obj/effect/turf_decal/siding/green/end
/obj/effect/turf_decal/siding/blue
/obj/effect/turf_decal/siding/blue/corner
/obj/effect/turf_decal/siding/blue/end
/obj/effect/turf_decal/siding/yellow
/obj/effect/turf_decal/siding/yellow/corner
/obj/effect/turf_decal/siding/yellow/end
/obj/effect/turf_decal/siding/purple
/obj/effect/turf_decal/siding/purple/corner
/obj/effect/turf_decal/siding/purple/end
/obj/effect/turf_decal/siding/brown
/obj/effect/turf_decal/siding/brown/corner
/obj/effect/turf_decal/siding/brown/end
/obj/effect/turf_decal/siding/wood
/obj/effect/turf_decal/siding/wood/corner
/obj/effect/turf_decal/siding/wood/end
/obj/effect/turf_decal/siding/thinplating
/obj/effect/turf_decal/siding/thinplating/corner
/obj/effect/turf_decal/siding/thinplating/end
/obj/effect/turf_decal/siding/thinplating/light
/obj/effect/turf_decal/siding/thinplating/light/corner
/obj/effect/turf_decal/siding/thinplating/light/end
/obj/effect/turf_decal/siding/thinplating/dark
/obj/effect/turf_decal/siding/thinplating/dark/corner
/obj/effect/turf_decal/siding/thinplating/dark/end
/obj/effect/turf_decal/siding/wideplating
/obj/effect/turf_decal/siding/wideplating/corner
/obj/effect/turf_decal/siding/wideplating/end
/obj/effect/turf_decal/siding/wideplating/light
/obj/effect/turf_decal/siding/wideplating/light/corner
/obj/effect/turf_decal/siding/wideplating/light/end
/obj/effect/turf_decal/siding/wideplating/dark
/obj/effect/turf_decal/siding/wideplating/dark/corner
/obj/effect/turf_decal/siding/wideplating/dark/end
