/datum/element/light_eater
/datum/element/light_eater/Attach(datum/target)
/datum/element/light_eater/Detach(datum/source)
/datum/element/light_eater/proc/eat_lights(atom/food, datum/eater)
/datum/element/light_eater/proc/table_buffet(atom/commisary, datum/devourer)
/datum/element/light_eater/proc/devour(atom/morsel, datum/eater)
/datum/element/light_eater/proc/on_throw_impact(atom/movable/source, atom/hit_atom, datum/thrownthing/thrownthing)
/datum/element/light_eater/proc/on_afterattack(obj/item/source, atom/target, mob/living/user, proximity)
/datum/element/light_eater/proc/on_hit_reaction(obj/item/source, mob/living/carbon/human/owner, atom/movable/hitby, attack_text, final_block_chance, damage, attack_type)
/datum/element/light_eater/proc/on_projectile_hit(obj/projectile/source, atom/movable/firer, atom/target, angle)
/datum/element/light_eater/proc/on_expose_atom(datum/reagent/source, atom/target, reac_volume)
