/datum/element/strippable
/datum/element/strippable/Attach(datum/target, list/items, should_strip_proc_path)
/datum/element/strippable/Detach(datum/source)
/datum/element/strippable/proc/mouse_drop_onto(datum/source, atom/over, mob/user)
/datum/strippable_item
/datum/strippable_item/proc/get_item(atom/source)
/datum/strippable_item/proc/try_equip(atom/source, obj/item/equipping, mob/user)
/datum/strippable_item/proc/start_equip(atom/source, obj/item/equipping, mob/user)
/datum/strippable_item/proc/finish_equip(atom/source, obj/item/equipping, mob/user)
/datum/strippable_item/proc/try_unequip(atom/source, mob/user)
/datum/strippable_item/proc/start_unequip(atom/source, mob/user)
/datum/strippable_item/proc/finish_unequip(atom/source, mob/user)
/datum/strippable_item/proc/get_obscuring(atom/source)
/datum/strippable_item/proc/get_alternate_action(atom/source, mob/user)
/datum/strippable_item/proc/alternate_action(atom/source, mob/user)
/datum/strippable_item/proc/should_show(atom/source, mob/user)
/datum/strippable_item/mob_item_slot
/datum/strippable_item/mob_item_slot/get_item(atom/source)
/datum/strippable_item/mob_item_slot/try_equip(atom/source, obj/item/equipping, mob/user)
/datum/strippable_item/mob_item_slot/start_equip(atom/source, obj/item/equipping, mob/user)
/datum/strippable_item/mob_item_slot/finish_equip(atom/source, obj/item/equipping, mob/user)
/datum/strippable_item/mob_item_slot/get_obscuring(atom/source)
/datum/strippable_item/mob_item_slot/start_unequip(atom/source, mob/user)
/datum/strippable_item/mob_item_slot/finish_unequip(atom/source, mob/user)
/datum/strippable_item/mob_item_slot/proc/get_equip_delay(obj/item/equipping)
/proc/start_unequip_mob(obj/item/item, mob/source, mob/user, strip_delay)
/proc/finish_unequip_mob(obj/item/item, mob/source, mob/user)
/datum/strip_menu
/datum/strip_menu/New(atom/movable/owner, datum/element/strippable/strippable)
/datum/strip_menu/Destroy()
/datum/strip_menu/ui_interact(mob/user, datum/tgui/ui)
/datum/strip_menu/ui_assets(mob/user)
/datum/strip_menu/ui_data(mob/user)
/datum/strip_menu/ui_act(action, list/params, datum/tgui/ui, datum/ui_state/state)
/datum/strip_menu/ui_host(mob/user)
/datum/strip_menu/ui_state(mob/user)
/datum/strip_menu/ui_status(mob/user, datum/ui_state/state)
/proc/create_strippable_list(types)
