/turf/proc/return_turf_delta_p()
/turf/proc/is_nearby_planetary_atmos()
/atom/proc/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/item/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/proc/integrate_amount()
/obj/item/integrate_amount() //returns the amount of resources gained when eating this item
/obj/item/gun/swarmer_act()//Stops you from eating the entire armory
/turf/open/swarmer_act()//ex_act() on turf calls it on its contents, this is to prevent attacking mobs by DisIntegrate()'ing the floor
/obj/structure/lattice/catwalk/swarmer_catwalk/swarmer_act()
/obj/structure/swarmer/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/effect/swarmer_act()
/obj/effect/decal/cleanable/robot_debris/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/structure/swarmer_beacon/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/structure/flora/swarmer_act()
/turf/open/lava/swarmer_act()
/obj/machinery/atmospherics/swarmer_act()
/obj/structure/disposalpipe/swarmer_act()
/obj/machinery/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/light/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/door/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/camera/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/field/generator/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/gravity_generator/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/vending/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)//It's more visually interesting than dismantling the machine
/obj/machinery/turretid/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/chem_dispenser/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/nuclearbomb/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/effect/rune/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/structure/reagent_dispensers/fueltank/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/structure/cable/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/portable_atmospherics/canister/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/structure/shuttle/engine/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/telecomms/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/deepfryer/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/power/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/gateway/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/turf/closed/wall/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/structure/window/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/item/stack/cable_coil/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)//Wiring would be too effective as a resource
/obj/machinery/porta_turret/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/porta_turret_cover/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/structure/lattice/catwalk/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/hydroponics/soil/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/field/generator/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/field/containment/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/power/shieldwallgen/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
/obj/machinery/shieldwall/swarmer_act(mob/living/simple_animal/hostile/swarmer/actor)
