/mob/living/carbon/human/update_hair()
/mob/living/carbon/human/proc/update_mutant_bodyparts()
/mob/living/carbon/human/update_body()
/mob/living/carbon/human/update_fire()
/mob/living/carbon/human/regenerate_icons()
/mob/living/carbon/human/update_inv_w_uniform()
/mob/living/carbon/human/update_inv_wear_id()
/mob/living/carbon/human/update_inv_gloves()
/mob/living/carbon/human/update_inv_glasses()
/mob/living/carbon/human/update_inv_ears()
/mob/living/carbon/human/update_inv_shoes()
/mob/living/carbon/human/update_inv_s_store()
/mob/living/carbon/human/update_inv_head()
/mob/living/carbon/human/update_inv_belt()
/mob/living/carbon/human/update_inv_wear_suit()
/mob/living/carbon/human/update_inv_pockets()
/mob/living/carbon/human/update_inv_wear_mask()
/mob/living/carbon/human/update_inv_back()
/mob/living/carbon/human/update_inv_legcuffed()
/proc/wear_female_version(t_color, icon, layer, type, greyscale_colors)
/mob/living/carbon/human/proc/get_overlays_copy(list/unwantedLayers)
/mob/living/carbon/human/update_hud_head(obj/item/I)
/mob/living/carbon/human/update_hud_wear_mask(obj/item/I)
/mob/living/carbon/human/update_hud_neck(obj/item/I)
/mob/living/carbon/human/update_hud_back(obj/item/I)
/obj/item/proc/build_worn_icon(default_layer = 0, default_icon_file = null, isinhands = FALSE, femaleuniform = NO_FEMALE_UNIFORM, override_state = null)
/obj/item/proc/get_worn_offsets(isinhands)
/mob/proc/get_item_offsets_for_index(i)
/mob/living/carbon/human/generate_icon_render_key()
/mob/living/carbon/human/load_limb_from_cache()
/mob/living/carbon/human/proc/update_observer_view(obj/item/I, inventory)
/mob/living/carbon/human/proc/update_body_parts_head_only()
