/mob/living/carbon/human/canBeHandcuffed()
/mob/living/carbon/human/proc/get_assignment(if_no_id = "No id", if_no_job = "No job", hand_first = TRUE)
/mob/living/carbon/human/proc/get_authentification_name(if_no_id = "Unknown")
/mob/living/carbon/human/get_visible_name()
/mob/living/carbon/human/proc/get_face_name(if_no_face="Unknown")
/mob/living/carbon/human/proc/get_id_name(if_no_id = "Unknown")
/mob/living/carbon/human/get_idcard(hand_first = TRUE)
/mob/living/carbon/human/reagent_check(datum/reagent/R, delta_time, times_fired)
/mob/living/carbon/human/can_track(mob/living/user)
/mob/living/carbon/human/can_use_guns(obj/item/G)
/mob/living/carbon/human/get_policy_keywords()
/mob/living/carbon/human/can_see_reagents()
/mob/living/carbon/human/proc/increment_scar_slot()
/mob/living/carbon/human/proc/format_scars()
/mob/living/carbon/human/proc/load_scar(scar_line, specified_char_index)
/mob/living/carbon/human/proc/load_persistent_scars()
/mob/living/carbon/human/proc/save_persistent_scars(nuke=FALSE)
/mob/living/carbon/human/get_biological_state()
/mob/living/carbon/human/proc/generate_death_examine_text()
/mob/living/carbon/human/proc/copy_clothing_prefs(mob/living/carbon/human/destination)
/mob/living/carbon/human/proc/randomize_human_appearance(randomize_flags = ALL)
