/mob/living/carbon/human/Life(delta_time = SSMOBS_DT, times_fired)
	name = get_visible_name()
/mob/living/carbon/human/calculate_affecting_pressure(pressure)
/mob/living/carbon/human/handle_traits(delta_time, times_fired)
/mob/living/carbon/human/breathe()
/mob/living/carbon/human/check_breath(datum/gas_mixture/breath)
/mob/living/carbon/human/handle_environment(datum/gas_mixture/environment, delta_time, times_fired)
/mob/living/carbon/human/proc/adjust_coretemperature(amount, min_temp=0, max_temp=INFINITY)
/mob/living/carbon/human/proc/set_coretemperature(value)
/mob/living/carbon/human/get_body_temp_normal(apply_change=TRUE)
/mob/living/carbon/human/get_body_temp_heat_damage_limit()
/mob/living/carbon/human/get_body_temp_cold_damage_limit()
/mob/living/carbon/human/handle_fire(delta_time, times_fired)
/mob/living/carbon/human/proc/get_thermal_protection()
/mob/living/carbon/human/IgniteMob()
/mob/living/carbon/human/extinguish_mob()
/mob/living/carbon/human/proc/get_heat_protection_flags(temperature) //Temperature is the temperature you're being exposed to.
/mob/living/carbon/human/get_heat_protection(temperature)
/mob/living/carbon/human/proc/get_cold_protection_flags(temperature)
/mob/living/carbon/human/get_cold_protection(temperature)
/mob/living/carbon/human/handle_random_events(delta_time, times_fired)
/mob/living/carbon/human/has_smoke_protection()
/mob/living/carbon/human/proc/handle_heart(delta_time, times_fired)
