/datum/species
/datum/species/New()
/proc/get_selectable_species()
/proc/generate_selectable_species()
/datum/species/proc/check_roundstart_eligible()
/datum/species/proc/random_name(gender,unique,lastname)
/datum/species/proc/copy_properties_from(datum/species/old_species)
/datum/species/proc/regenerate_organs(mob/living/carbon/C, datum/species/old_species, replace_current = TRUE, list/excluded_zones, visual_only = FALSE)
/datum/species/proc/on_species_gain(mob/living/carbon/C, datum/species/old_species, pref_load)
/datum/species/proc/on_species_loss(mob/living/carbon/human/C, datum/species/new_species, pref_load)
/datum/species/proc/handle_hair(mob/living/carbon/human/H, forced_colour)
/datum/species/proc/make_gradient_overlay(file, icon, layer, datum/sprite_accessory/gradient, grad_color)
/datum/species/proc/handle_body(mob/living/carbon/human/species_human)
/datum/species/proc/handle_mutant_bodyparts(mob/living/carbon/human/source, forced_colour)
/datum/species/proc/mutant_bodyparts_layertext(layer)
/datum/species/proc/randomize_main_appearance_element(mob/living/carbon/human/human_mob)
/datum/species/proc/randomize_active_underwear(mob/living/carbon/human/human_mob)
/datum/species/proc/spec_life(mob/living/carbon/human/H, delta_time, times_fired)
/datum/species/proc/spec_death(gibbed, mob/living/carbon/human/H)
/datum/species/proc/can_equip(obj/item/I, slot, disable_warning, mob/living/carbon/human/H, bypass_equip_delay_self = FALSE)
/datum/species/proc/equip_delay_self_check(obj/item/I, mob/living/carbon/human/H, bypass_equip_delay_self)
/datum/species/proc/pre_equip_species_outfit(datum/job/job, mob/living/carbon/human/equipping, visuals_only = FALSE)
/datum/species/proc/handle_chemicals(datum/reagent/chem, mob/living/carbon/human/H, delta_time, times_fired)
/datum/species/proc/check_species_weakness(obj/item, mob/living/attacker)
/datum/species/proc/give_important_for_life(mob/living/carbon/human/human_to_equip)
/datum/species/proc/update_health_hud(mob/living/carbon/human/H)
/datum/species/proc/handle_radiation(mob/living/carbon/human/source, time_since_irradiated, delta_time)
/datum/species/proc/go_bald(mob/living/carbon/human/target)
/datum/species/proc/spec_updatehealth(mob/living/carbon/human/H)
/datum/species/proc/spec_fully_heal(mob/living/carbon/human/H)
/datum/species/proc/help(mob/living/carbon/human/user, mob/living/carbon/human/target, datum/martial_art/attacker_style)
/datum/species/proc/grab(mob/living/carbon/human/user, mob/living/carbon/human/target, datum/martial_art/attacker_style)
/datum/species/proc/harm(mob/living/carbon/human/user, mob/living/carbon/human/target, datum/martial_art/attacker_style)
/datum/species/proc/spec_unarmedattacked(mob/living/carbon/human/user, mob/living/carbon/human/target)
/datum/species/proc/disarm(mob/living/carbon/human/user, mob/living/carbon/human/target, datum/martial_art/attacker_style)
/datum/species/proc/spec_hitby(atom/movable/AM, mob/living/carbon/human/H)
/datum/species/proc/spec_attack_hand(mob/living/carbon/human/M, mob/living/carbon/human/H, datum/martial_art/attacker_style, modifiers)
/datum/species/proc/spec_attacked_by(obj/item/I, mob/living/user, obj/item/bodypart/affecting, mob/living/carbon/human/H)
/datum/species/proc/apply_damage(damage, damagetype = BRUTE, def_zone = null, blocked, mob/living/carbon/human/H, forced = FALSE, spread_damage = FALSE, wound_bonus = 0, bare_wound_bonus = 0, sharpness = NONE)
/datum/species/proc/on_hit(obj/projectile/P, mob/living/carbon/human/H)
/datum/species/proc/bullet_act(obj/projectile/P, mob/living/carbon/human/H)
/datum/species/proc/handle_environment(mob/living/carbon/human/humi, datum/gas_mixture/environment, delta_time, times_fired)
/datum/species/proc/handle_body_temperature(mob/living/carbon/human/humi, delta_time, times_fired)
/datum/species/proc/body_temperature_core(mob/living/carbon/human/humi, delta_time, times_fired)
/datum/species/proc/body_temperature_skin(mob/living/carbon/human/humi, delta_time, times_fired)
/datum/species/proc/body_temperature_alerts(mob/living/carbon/human/humi)
/datum/species/proc/body_temperature_damage(mob/living/carbon/human/humi, delta_time, times_fired)
/datum/species/proc/apply_burn_wounds(mob/living/carbon/human/humi, delta_time, times_fired)
/datum/species/proc/handle_environment_pressure(mob/living/carbon/human/H, datum/gas_mixture/environment, delta_time, times_fired)
/datum/species/proc/handle_fire(mob/living/carbon/human/H, delta_time, times_fired, no_protection = FALSE)
/datum/species/proc/CanIgniteMob(mob/living/carbon/human/H)
/datum/species/proc/extinguish_mob(mob/living/carbon/human/H)
/datum/species/proc/spec_stun(mob/living/carbon/human/H,amount)
/datum/species/proc/negates_gravity(mob/living/carbon/human/H)
/datum/species/proc/on_tail_lost(mob/living/carbon/human/tail_owner, obj/item/organ/tail/lost_tail, on_species_init = FALSE)
/datum/species/proc/on_tail_regain(mob/living/carbon/human/tail_owner, obj/item/organ/tail/found_tail, on_species_init = FALSE)
/datum/species/proc/clear_tail_moodlets(mob/living/carbon/human/former_tail_owner)
/datum/species/proc/can_wag_tail(mob/living/carbon/human/H)
/datum/species/proc/is_wagging_tail(mob/living/carbon/human/H)
/datum/species/proc/start_wagging_tail(mob/living/carbon/human/H)
/datum/species/proc/stop_wagging_tail(mob/living/carbon/human/H)
/datum/species/proc/GiveSpeciesFlight(mob/living/carbon/human/H)
/datum/species/proc/get_biological_state(mob/living/carbon/human/H)
/datum/species/proc/spec_unarmedattack(mob/living/carbon/human/user, atom/target, modifiers)
/datum/species/proc/fix_non_native_limbs(mob/living/carbon/human/H)
/datum/species/proc/get_features()
/datum/species/proc/prepare_human_for_preview(mob/living/carbon/human/human)
/datum/species/proc/get_scream_sound(mob/living/carbon/human/human)
/datum/species/proc/get_types_to_preload()
