/mob/living/carbon/human/Stun(amount, ignore_canstun = FALSE)
/mob/living/carbon/human/Knockdown(amount, ignore_canstun = FALSE)
/mob/living/carbon/human/Paralyze(amount, ignore_canstun = FALSE)
/mob/living/carbon/human/Immobilize(amount, ignore_canstun = FALSE)
/mob/living/carbon/human/Unconscious(amount, ignore_canstun = FALSE)
/mob/living/carbon/human/Sleeping(amount)
/mob/living/carbon/human/cure_husk(list/sources)
/mob/living/carbon/human/become_husk(source)
/mob/living/carbon/human/set_drugginess(amount)
/mob/living/carbon/human/adjust_drugginess(amount)
