/datum/mafia_controller
/datum/mafia_controller/New()
/datum/mafia_controller/Destroy(force, ...)
/datum/mafia_controller/proc/prepare_game(setup_list,ready_players)
/datum/mafia_controller/proc/send_message(msg,team)
/datum/mafia_controller/proc/start_game()
/datum/mafia_controller/proc/start_day()
/datum/mafia_controller/proc/start_voting_phase()
/datum/mafia_controller/proc/check_trial(verbose = TRUE)
/datum/mafia_controller/proc/lynch()
/datum/mafia_controller/proc/send_home(datum/mafia_role/role)
/datum/mafia_controller/proc/check_victory()
/datum/mafia_controller/proc/award_role(award, datum/mafia_role/rewarded)
/datum/mafia_controller/proc/start_the_end(message)
/datum/mafia_controller/proc/end_game()
/datum/mafia_controller/proc/lockdown()
/datum/mafia_controller/proc/toggle_night_curtains(close)
/datum/mafia_controller/proc/start_night()
/datum/mafia_controller/proc/resolve_night()
/datum/mafia_controller/proc/vote_for(datum/mafia_role/voter,datum/mafia_role/target,vote_type, teams)
/datum/mafia_controller/proc/reset_votes(vote_type)
/datum/mafia_controller/proc/get_vote_count(role,vote_type)
/datum/mafia_controller/proc/get_vote_winner(vote_type)
/datum/mafia_controller/proc/get_random_voter(vote_type)
/datum/mafia_controller/proc/display_votes(atom/source, list/overlay_list)
/datum/mafia_controller/proc/create_bodies()
/datum/mafia_controller/ui_data(mob/user)
/datum/mafia_controller/ui_assets(mob/user)
/datum/mafia_controller/ui_act(action, list/params, datum/tgui/ui, datum/ui_state/state)
/datum/mafia_controller/ui_state(mob/user)
/datum/mafia_controller/ui_interact(mob/user, datum/tgui/ui)
/proc/assoc_value_sum(list/L)
/datum/mafia_controller/proc/generate_random_setup()
/datum/mafia_controller/proc/add_setup_role(setup_list, banned_roles, wanted_role_type)
/datum/mafia_controller/proc/basic_setup()
/datum/mafia_controller/proc/try_autostart()
/datum/mafia_controller/proc/check_signups()
/datum/action/innate/mafia_panel
	name = "Mafia Panel"
	desc = "Use this to play."
/datum/action/innate/mafia_panel/New(Target,mf)
/datum/action/innate/mafia_panel/Activate()
/proc/create_mafia_game()
