/obj/item/proc/melee_attack_chain(mob/user, atom/target, params)
/obj/item/proc/attack_self(mob/user, modifiers)
/obj/item/proc/attack_self_secondary(mob/user, modifiers)
/obj/item/proc/pre_attack(atom/A, mob/living/user, params) //do stuff before attackby!
/obj/item/proc/pre_attack_secondary(atom/target, mob/living/user, params)
/atom/proc/attackby(obj/item/attacking_item, mob/user, params)
/atom/proc/attackby_secondary(obj/item/weapon, mob/user, params)
/obj/attackby(obj/item/I, mob/living/user, params)
/mob/living/attackby(obj/item/attacking_item, mob/living/user, params)
/mob/living/attackby_secondary(obj/item/weapon, mob/living/user, params)
/obj/item/proc/attack(mob/living/M, mob/living/user, params)
/obj/item/proc/attack_secondary(mob/living/victim, mob/living/user, params)
/obj/item/proc/attack_atom(atom/attacked_atom, mob/living/user, params)
/atom/proc/attacked_by(obj/item/attacking_item, mob/living/user)
/area/attacked_by(obj/item/attacking_item, mob/living/user)
/mob/living/attacked_by(obj/item/I, mob/living/user)
/mob/living/simple_animal/attacked_by(obj/item/I, mob/living/user)
/mob/living/basic/attacked_by(obj/item/I, mob/living/user)
/obj/item/proc/afterattack(atom/target, mob/user, proximity_flag, click_parameters)
/obj/item/proc/afterattack_secondary(atom/target, mob/user, proximity_flag, click_parameters)
/obj/item/proc/attack_qdeleted(atom/target, mob/user, proximity_flag, click_parameters)
/obj/item/proc/get_clamped_volume()
/mob/living/proc/send_item_attack_message(obj/item/I, mob/living/user, hit_area, obj/item/bodypart/hit_bodypart)
