/client/proc/cmd_admin_subtle_message(mob/M in GLOB.mob_list)
/client/proc/cmd_admin_headset_message(mob/M in GLOB.mob_list)
/client/proc/admin_headset_message(mob/M in GLOB.mob_list, sender = null)
/client/proc/cmd_admin_world_narrate()
/client/proc/cmd_admin_local_narrate(atom/A)
/client/proc/cmd_admin_direct_narrate(mob/M)
/client/proc/cmd_admin_add_freeform_ai_law()
/client/proc/admin_call_shuttle()
/client/proc/admin_cancel_shuttle()
/client/proc/admin_disable_shuttle()
/client/proc/admin_enable_shuttle()
/client/proc/toggle_nuke(obj/machinery/nuclearbomb/N in GLOB.nuke_list)
/datum/admins/proc/access_news_network() //MARKER
/client/proc/admin_change_sec_level()
/client/proc/run_weather()
