/client/proc/jumptoarea(area/A in GLOB.sortedAreas)
/client/proc/jumptoturf(turf/T in world)
/client/proc/jumptomob(mob/M in GLOB.mob_list)
/client/proc/jumptocoord(tx as num, ty as num, tz as num)
/client/proc/jumptokey()
/client/proc/Getmob(mob/M in GLOB.mob_list - GLOB.dummy_mob_list)
/atom/movable/proc/admin_teleport(atom/new_location)
/mob/admin_teleport(atom/new_location)
/client/proc/Getkey()
/client/proc/sendmob(mob/M in sort_mobs())
