/client/proc/cmd_select_equipment(mob/target in GLOB.mob_list)
/datum/select_equipment
/datum/select_equipment/New(_user, mob/target)
/datum/select_equipment/ui_interact(mob/user, datum/tgui/ui)
/datum/select_equipment/ui_state(mob/user)
/datum/select_equipment/ui_status(mob/user, datum/ui_state/state)
/datum/select_equipment/ui_close(mob/user)
/datum/select_equipment/proc/init_dummy()
/datum/select_equipment/proc/outfit_entry(category, identifier, name, priority=FALSE, custom_entry=FALSE)
/datum/select_equipment/proc/make_outfit_entries(category="General", list/outfit_list)
/datum/select_equipment/proc/make_custom_outfit_entries(list/outfit_list)
/datum/select_equipment/ui_data(mob/user)
/datum/select_equipment/ui_static_data(mob/user)
/datum/select_equipment/proc/resolve_outfit(text)
/datum/select_equipment/ui_act(action, params)
/client/proc/admin_apply_outfit(mob/target, dresscode)
