/proc/default_ui_state(mob/user, atom/source)
/proc/ui_status_user_is_adjacent(mob/user, atom/source, allow_tk = TRUE)
/proc/ui_status_only_living(mob/user, source)
/proc/ui_status_user_is_abled(mob/user, atom/source)
/proc/ui_status_user_has_free_hands(mob/user, atom/source)
/proc/ui_status_user_is_advanced_tool_user(mob/user)
/proc/ui_status_silicon_has_access(mob/user, atom/source)
/mob/living/silicon/proc/get_ui_access(atom/source)
/mob/living/silicon/robot/get_ui_access(atom/source)
/mob/living/silicon/ai/get_ui_access(atom/source)
/mob/living/silicon/pai/get_ui_access(atom/source)
/proc/ui_status_user_is_conscious_and_lying_down(mob/user)
/proc/ui_status_user_strictly_adjacent(mob/user, atom/target)
