/datum/proc/ui_status(mob/user, datum/ui_state/state)
/datum/ui_state/proc/can_use_topic(src_object, mob/user)
/mob/proc/shared_ui_interaction(src_object)
/mob/living/shared_ui_interaction(src_object)
/mob/living/silicon/ai/shared_ui_interaction(src_object)
/mob/living/silicon/robot/shared_ui_interaction(src_object)
/mob/living/proc/shared_living_ui_distance(atom/movable/src_object, viewcheck = TRUE, allow_tk = TRUE)
/mob/living/carbon/human/shared_living_ui_distance(atom/movable/src_object, viewcheck = TRUE, allow_tk = TRUE)
