/atom/movable/visual/cryo_occupant
/atom/movable/visual/cryo_occupant/Initialize(mapload, obj/machinery/atmospherics/components/unary/cryo_cell/parent)
/atom/movable/visual/cryo_occupant/proc/on_set_occupant(datum/source, mob/living/new_occupant)
/atom/movable/visual/cryo_occupant/proc/on_set_on(datum/source, on)
/obj/machinery/atmospherics/components/unary/cryo_cell
	name = "cryo cell"
/obj/machinery/atmospherics/components/unary/cryo_cell/Initialize(mapload)
/obj/machinery/atmospherics/components/unary/cryo_cell/set_occupant(atom/movable/new_occupant)
/obj/machinery/atmospherics/components/unary/cryo_cell/on_construction()
/obj/machinery/atmospherics/components/unary/cryo_cell/RefreshParts()
/obj/machinery/atmospherics/components/unary/cryo_cell/examine(mob/user) //this is leaving out everything but efficiency since they follow the same idea of "better beaker, better results"
/obj/machinery/atmospherics/components/unary/cryo_cell/Destroy()
/obj/machinery/atmospherics/components/unary/cryo_cell/contents_explosion(severity, target)
/obj/machinery/atmospherics/components/unary/cryo_cell/handle_atom_del(atom/A)
/obj/machinery/atmospherics/components/unary/cryo_cell/on_deconstruction()
/obj/machinery/atmospherics/components/unary/cryo_cell/update_icon_state()
/obj/machinery/atmospherics/components/unary/cryo_cell/update_icon()
/obj/machinery/atmospherics/components/unary/cryo_cell/update_overlays()
/obj/machinery/atmospherics/components/unary/cryo_cell/nap_violation(mob/violator)
/obj/machinery/atmospherics/components/unary/cryo_cell/proc/set_on(new_value)
/obj/machinery/atmospherics/components/unary/cryo_cell/on_set_is_operational(old_value)
/obj/machinery/atmospherics/components/unary/cryo_cell/process(delta_time)
/obj/machinery/atmospherics/components/unary/cryo_cell/process_atmos()
/obj/machinery/atmospherics/components/unary/cryo_cell/relaymove(mob/living/user, direction)
/obj/machinery/atmospherics/components/unary/cryo_cell/open_machine(drop = FALSE)
/obj/machinery/atmospherics/components/unary/cryo_cell/close_machine(mob/living/carbon/user)
/obj/machinery/atmospherics/components/unary/cryo_cell/container_resist_act(mob/living/user)
/obj/machinery/atmospherics/components/unary/cryo_cell/examine(mob/user)
/obj/machinery/atmospherics/components/unary/cryo_cell/MouseDrop_T(mob/target, mob/user)
/obj/machinery/atmospherics/components/unary/cryo_cell/attackby(obj/item/I, mob/user, params)
/obj/machinery/atmospherics/components/unary/cryo_cell/ui_state(mob/user)
/obj/machinery/atmospherics/components/unary/cryo_cell/ui_interact(mob/user, datum/tgui/ui)
/obj/machinery/atmospherics/components/unary/cryo_cell/ui_data()
/obj/machinery/atmospherics/components/unary/cryo_cell/ui_act(action, params)
/obj/machinery/atmospherics/components/unary/cryo_cell/can_interact(mob/user)
/obj/machinery/atmospherics/components/unary/cryo_cell/CtrlClick(mob/user)
/obj/machinery/atmospherics/components/unary/cryo_cell/AltClick(mob/user)
/obj/machinery/atmospherics/components/unary/cryo_cell/update_remote_sight(mob/living/user)
/obj/machinery/atmospherics/components/unary/cryo_cell/get_remote_view_fullscreens(mob/user)
/obj/machinery/atmospherics/components/unary/cryo_cell/can_see_pipes()
/obj/machinery/atmospherics/components/unary/cryo_cell/return_temperature()
/obj/machinery/atmospherics/components/unary/cryo_cell/default_change_direction_wrench(mob/user, obj/item/wrench/W)
