/datum/preferences/proc/savefile_needs_update(savefile/S)
/datum/preferences/proc/update_preferences(current_version, savefile/S)
/datum/preferences/proc/update_character(current_version, savefile/savefile)
/datum/preferences/proc/check_keybindings()
/datum/preferences/proc/announce_conflict(list/notadded)
/datum/preferences/proc/load_path(ckey,filename="preferences.sav")
/datum/preferences/proc/load_preferences()
/datum/preferences/proc/save_preferences()
/datum/preferences/proc/load_character(slot)
/datum/preferences/proc/save_character()
/datum/preferences/proc/sanitize_be_special(list/input_be_special)
/proc/sanitize_keybindings(value)
/client/verb/savefile_export(path as text)
/client/verb/savefile_import(path as text)
