/datum/preferences
/datum/preferences/Destroy(force, ...)
/datum/preferences/New(client/C)
/datum/preferences/ui_interact(mob/user, datum/tgui/ui)
/datum/preferences/ui_state(mob/user)
/datum/preferences/ui_status(mob/user, datum/ui_state/state)
/datum/preferences/ui_data(mob/user)
/datum/preferences/ui_static_data(mob/user)
/datum/preferences/ui_assets(mob/user)
/datum/preferences/ui_act(action, list/params, datum/tgui/ui, datum/ui_state/state)
/datum/preferences/ui_close(mob/user)
/datum/preferences/Topic(href, list/href_list)
/datum/preferences/proc/create_character_preview_view(mob/user)
/datum/preferences/proc/compile_character_preferences(mob/user)
/datum/preferences/proc/apply_all_client_preferences()
/atom/movable/screen/character_preview_view
	name = "character_preview"
/atom/movable/screen/character_preview_view/Initialize(mapload, datum/preferences/preferences, client/client)
/atom/movable/screen/character_preview_view/Destroy()
/atom/movable/screen/character_preview_view/proc/update_body()
/atom/movable/screen/character_preview_view/proc/create_body()
/atom/movable/screen/character_preview_view/proc/register_to_client(client/client)
/datum/preferences/proc/create_character_profiles()
/datum/preferences/proc/set_job_preference_level(datum/job/job, level)
/datum/preferences/proc/GetQuirkBalance()
/datum/preferences/proc/GetPositiveQuirkCount()
/datum/preferences/proc/validate_quirks()
/datum/preferences/proc/safe_transfer_prefs_to(mob/living/carbon/human/character, icon_updates = TRUE, is_antag = FALSE)
/datum/preferences/proc/apply_prefs_to(mob/living/carbon/human/character, icon_updates = TRUE)
/datum/preferences/proc/should_be_random_hardcore(datum/job/job, datum/mind/mind)
/datum/preferences/proc/get_key_bindings_by_key(list/key_bindings)
/datum/preferences/proc/get_default_randomization()
