/obj/structure/closet
	name = "closet"
	desc = "It's a basic storage unit."
/obj/structure/closet/Initialize(mapload)
/obj/structure/closet/proc/PopulateContents()
/obj/structure/closet/Destroy()
/obj/structure/closet/update_appearance(updates=ALL)
/obj/structure/closet/update_icon()
/obj/structure/closet/update_overlays()
/obj/structure/closet/proc/closet_update_overlays(list/new_overlays)
/obj/structure/closet/proc/animate_door(closing = FALSE)
/obj/structure/closet/proc/end_door_animation()
/obj/structure/closet/proc/get_door_transform(angle)
/obj/structure/closet/examine(mob/user)
/obj/structure/closet/CanAllowThrough(atom/movable/mover, border_dir)
/obj/structure/closet/proc/can_open(mob/living/user, force = FALSE)
/obj/structure/closet/proc/can_close(mob/living/user)
/obj/structure/closet/dump_contents()
/obj/structure/closet/proc/take_contents(mapload = FALSE)
/obj/structure/closet/proc/open(mob/living/user, force = FALSE)
/obj/structure/closet/proc/after_open(mob/living/user, force = FALSE)
/obj/structure/closet/proc/insert(atom/movable/inserted, mapload = FALSE)
/obj/structure/closet/proc/insertion_allowed(atom/movable/AM)
/obj/structure/closet/proc/close(mob/living/user)
/obj/structure/closet/proc/after_close(mob/living/user)
/obj/structure/closet/proc/toggle(mob/living/user)
/obj/structure/closet/deconstruct(disassembled = TRUE)
/obj/structure/closet/atom_break(damage_flag)
/obj/structure/closet/attackby(obj/item/W, mob/user, params)
/obj/structure/closet/proc/tool_interact(obj/item/W, mob/living/user)//returns TRUE if attackBy call shouldn't be continued (because tool was used/closet was of wrong type), FALSE if otherwise
/obj/structure/closet/proc/after_weld(weld_state)
/obj/structure/closet/MouseDrop_T(atom/movable/O, mob/living/user)
/obj/structure/closet/relaymove(mob/living/user, direction)
/obj/structure/closet/attack_hand(mob/living/user, list/modifiers)
/obj/structure/closet/attack_paw(mob/user, list/modifiers)
/obj/structure/closet/attack_robot(mob/user)
/obj/structure/closet/attack_robot_secondary(mob/user, list/modifiers)
/obj/structure/closet/attack_self_tk(mob/user)
/obj/structure/closet/verb/verb_toggleopen()
/obj/structure/closet/Exit(atom/movable/leaving, direction)
/obj/structure/closet/container_resist_act(mob/living/user)
/obj/structure/closet/relay_container_resist_act(mob/living/user, obj/container)
/obj/structure/closet/proc/bust_open()
/obj/structure/closet/attack_hand_secondary(mob/user, modifiers)
/obj/structure/closet/proc/togglelock(mob/living/user, silent)
/obj/structure/closet/emag_act(mob/user)
/obj/structure/closet/get_remote_view_fullscreens(mob/user)
/obj/structure/closet/emp_act(severity)
/obj/structure/closet/contents_explosion(severity, target)
/obj/structure/closet/singularity_act()
/obj/structure/closet/AllowDrop()
/obj/structure/closet/return_temperature()
/obj/structure/closet/proc/locker_carbon(datum/source, mob/living/carbon/shover, mob/living/carbon/target, shove_blocked)
