/datum/ai_controller
/datum/ai_controller/New(atom/new_pawn)
/datum/ai_controller/Destroy(force, ...)
/datum/ai_controller/proc/change_ai_movement_type(datum/ai_movement/new_movement)
/datum/ai_controller/proc/replace_planning_subtrees(list/typepaths_of_new_subtrees)
/datum/ai_controller/proc/init_subtrees()
/datum/ai_controller/proc/PossessPawn(atom/new_pawn)
/datum/ai_controller/proc/TryPossessPawn(atom/new_pawn)
/datum/ai_controller/proc/UnpossessPawn(destroy)
/datum/ai_controller/proc/able_to_run()
/datum/ai_controller/process(delta_time)
/datum/ai_controller/proc/SelectBehaviors(delta_time)
/datum/ai_controller/proc/set_ai_status(new_ai_status)
/datum/ai_controller/proc/PauseAi(time)
/datum/ai_controller/proc/queue_behavior(behavior_type, ...)
/datum/ai_controller/proc/ProcessBehavior(delta_time, datum/ai_behavior/behavior)
/datum/ai_controller/proc/CancelActions()
/datum/ai_controller/proc/on_sentience_gained()
/datum/ai_controller/proc/on_sentience_lost()
/datum/ai_controller/proc/get_access()
