/obj/item/slimecross/burning
	name = "burning extract"
	desc = "It's boiling over with barely-contained energy."
/obj/item/slimecross/burning/Initialize(mapload)
/obj/item/slimecross/burning/attack_self(mob/user)
/obj/item/slimecross/burning/proc/do_effect(mob/user) //If, for whatever reason, you don't want to delete the extract, don't do ..()
/obj/item/slimecross/burning/grey
/obj/item/slimecross/burning/grey/do_effect(mob/user)
/obj/item/slimecross/burning/orange
/obj/item/slimecross/burning/orange/do_effect(mob/user)
/obj/item/slimecross/burning/purple
/obj/item/slimecross/burning/purple/do_effect(mob/user)
/obj/item/slimecross/burning/blue
/obj/item/slimecross/burning/blue/do_effect(mob/user)
/obj/item/slimecross/burning/metal
/obj/item/slimecross/burning/metal/do_effect(mob/user)
/obj/item/slimecross/burning/yellow
/obj/item/slimecross/burning/yellow/do_effect(mob/user)
/obj/item/slimecross/burning/darkpurple
/obj/item/slimecross/burning/darkpurple/do_effect(mob/user)
/obj/item/slimecross/burning/darkblue
/obj/item/slimecross/burning/darkblue/do_effect(mob/user)
/obj/item/slimecross/burning/silver
/obj/item/slimecross/burning/silver/do_effect(mob/user)
/obj/item/slimecross/burning/bluespace
/obj/item/slimecross/burning/bluespace/do_effect(mob/user)
/obj/item/slimecross/burning/sepia
/obj/item/slimecross/burning/sepia/do_effect(mob/user)
/obj/item/slimecross/burning/cerulean
/obj/item/slimecross/burning/cerulean/do_effect(mob/user)
/obj/item/slimecross/burning/pyrite
/obj/item/slimecross/burning/pyrite/do_effect(mob/user)
/obj/item/slimecross/burning/red
/obj/item/slimecross/burning/red/do_effect(mob/user)
/obj/item/slimecross/burning/green
/obj/item/slimecross/burning/green/do_effect(mob/user)
/obj/item/slimecross/burning/pink
/obj/item/slimecross/burning/pink/do_effect(mob/user)
/obj/item/slimecross/burning/gold
/obj/item/slimecross/burning/gold/do_effect(mob/user)
/obj/item/slimecross/burning/oil
/obj/item/slimecross/burning/oil/do_effect(mob/user)
/obj/item/slimecross/burning/oil/proc/boom()
/obj/item/slimecross/burning/black
/obj/item/slimecross/burning/black/do_effect(mob/user)
/obj/item/slimecross/burning/lightpink
/obj/item/slimecross/burning/lightpink/do_effect(mob/user)
/obj/item/slimecross/burning/adamantine
/obj/item/slimecross/burning/adamantine/do_effect(mob/user)
/obj/item/slimecross/burning/rainbow
/obj/item/slimecross/burning/rainbow/do_effect(mob/user)
