/obj/item/slimecross/charged
	name = "charged extract"
	desc = "It sparks with electric power."
/obj/item/slimecross/charged/Initialize(mapload)
/obj/item/slimecross/charged/attack_self(mob/user)
/obj/item/slimecross/charged/proc/do_effect(mob/user) //If, for whatever reason, you don't want to delete the extract, don't do ..()
/obj/item/slimecross/charged/grey
/obj/item/slimecross/charged/grey/do_effect(mob/user)
/obj/item/slimecross/charged/orange
/obj/item/slimecross/charged/orange/do_effect(mob/user)
/obj/item/slimecross/charged/purple
/obj/item/slimecross/charged/purple/do_effect(mob/user)
/obj/item/slimecross/charged/blue
/obj/item/slimecross/charged/blue/do_effect(mob/user)
/obj/item/slimecross/charged/metal
/obj/item/slimecross/charged/metal/do_effect(mob/user)
/obj/item/slimecross/charged/yellow
/obj/item/slimecross/charged/yellow/do_effect(mob/user)
/obj/item/slimecross/charged/darkpurple
/obj/item/slimecross/charged/darkpurple/do_effect(mob/user)
/obj/item/slimecross/charged/darkblue
/obj/item/slimecross/charged/darkblue/do_effect(mob/user)
/obj/item/slimecross/charged/silver
/obj/item/slimecross/charged/silver/do_effect(mob/user)
/obj/item/slimecross/charged/bluespace
/obj/item/slimecross/charged/bluespace/do_effect(mob/user)
/obj/item/slimecross/charged/sepia
/obj/item/slimecross/charged/sepia/do_effect(mob/user)
/obj/item/slimecross/charged/cerulean
/obj/item/slimecross/charged/cerulean/do_effect(mob/user)
/obj/item/slimecross/charged/pyrite
/obj/item/slimecross/charged/pyrite/do_effect(mob/user)
/obj/item/slimecross/charged/red
/obj/item/slimecross/charged/red/do_effect(mob/user)
/obj/item/slimecross/charged/green
/obj/item/slimecross/charged/green/do_effect(mob/user)
/obj/item/slimecross/charged/pink
/obj/item/slimecross/charged/pink/do_effect(mob/user)
/obj/item/slimecross/charged/gold
/obj/item/slimecross/charged/gold/do_effect(mob/user)
/obj/item/slimecross/charged/gold/proc/startTimer()
/obj/item/slimecross/charged/gold/process()
/obj/item/slimecross/charged/gold/Destroy()
/obj/item/slimecross/charged/oil
/obj/item/slimecross/charged/oil/do_effect(mob/user)
/obj/item/slimecross/charged/oil/proc/boom()
/obj/item/slimecross/charged/black
/obj/item/slimecross/charged/black/do_effect(mob/user)
/obj/item/slimecross/charged/lightpink
/obj/item/slimecross/charged/lightpink/do_effect(mob/user)
/obj/item/slimecross/charged/adamantine
/obj/item/slimecross/charged/adamantine/do_effect(mob/user)
/obj/item/slimecross/charged/rainbow
/obj/item/slimecross/charged/rainbow/do_effect(mob/user)
