/obj/item/modular_computer/proc/can_install_component(obj/item/computer_hardware/try_install, mob/living/user = null)
/obj/item/modular_computer/proc/install_component(obj/item/computer_hardware/install, mob/living/user = null)
/obj/item/modular_computer/proc/uninstall_component(obj/item/computer_hardware/yeet, mob/living/user = null)
/obj/item/modular_computer/proc/forget_component(obj/item/computer_hardware/wipe_memory)
/obj/item/modular_computer/proc/find_hardware_by_name(name)
