/proc/init_preference_entries()
/proc/init_preference_entries_by_key()
/proc/get_preferences_in_priority_order()
/datum/preference
/datum/preference/proc/deserialize(input, datum/preferences/preferences)
/datum/preference/proc/serialize(input)
/datum/preference/proc/create_default_value()
/datum/preference/proc/create_informed_default_value(datum/preferences/preferences)
/datum/preference/proc/create_random_value(datum/preferences/preferences)
/datum/preference/proc/is_randomizable()
/datum/preference/proc/read(savefile/savefile, datum/preferences/preferences)
/datum/preference/proc/write(savefile/savefile, value)
/datum/preference/proc/apply_to_client(client/client, value)
/datum/preference/proc/apply_to_client_updated(client/client, value)
/datum/preference/proc/apply_to_human(mob/living/carbon/human/target, value, datum/preferences/preferences) //SKYRAT EDIT CHANGE
/datum/preferences/proc/get_savefile_for_savefile_identifier(savefile_identifier)
/datum/preferences/proc/read_preference(preference_type)
/datum/preferences/proc/write_preference(datum/preference/preference, preference_value)
/datum/preferences/proc/update_preference(datum/preference/preference, preference_value)
/datum/preference/proc/is_valid(value)
/datum/preference/proc/compile_ui_data(mob/user, value)
/datum/preference/proc/compile_constant_data()
/datum/preference/proc/is_accessible(datum/preferences/preferences)
/datum/preference/proc/should_show_on_page(preference_tab)
/datum/preference/choiced
/datum/preference/choiced/proc/get_choices()
/datum/preference/choiced/proc/get_choices_serialized()
/datum/preference/choiced/proc/init_possible_values()
/datum/preference/choiced/is_valid(value)
/datum/preference/choiced/deserialize(input, datum/preferences/preferences)
/datum/preference/choiced/create_default_value()
/datum/preference/choiced/compile_constant_data()
/datum/preference/color
/datum/preference/color/deserialize(input, datum/preferences/preferences)
/datum/preference/color/create_default_value()
/datum/preference/color/serialize(input)
/datum/preference/color/is_valid(value)
/proc/possible_values_for_sprite_accessory_list(list/datum/sprite_accessory/sprite_accessories)
/proc/possible_values_for_sprite_accessory_list_for_body_part(
/datum/preference/numeric
/datum/preference/numeric/deserialize(input, datum/preferences/preferences)
/datum/preference/numeric/serialize(input)
/datum/preference/numeric/create_default_value()
/datum/preference/numeric/is_valid(value)
/datum/preference/numeric/compile_constant_data()
/datum/preference/toggle
/datum/preference/toggle/create_default_value()
/datum/preference/toggle/deserialize(input, datum/preferences/preferences)
/datum/preference/toggle/is_valid(value)
/datum/preference/text
/datum/preference/text/deserialize(input, datum/preferences/preferences)
/datum/preference/text/create_default_value()
/datum/preference/text/is_valid(value)
/datum/preference/tri_color
/datum/preference/tri_color/deserialize(input, datum/preferences/preferences)
/datum/preference/tri_color/create_default_value()
/datum/preference/tri_color/is_valid(list/value)
/datum/preference/tri_color/is_accessible(datum/preferences/preferences)
/datum/preference/tri_color/apply_to_human(mob/living/carbon/human/target, value)
/datum/preference/tri_bool
/datum/preference/tri_bool/deserialize(input, datum/preferences/preferences)
/datum/preference/tri_bool/create_default_value()
/datum/preference/tri_bool/is_valid(list/value)
/datum/preference/tri_bool/is_accessible(datum/preferences/preferences)
/datum/preference/tri_bool/apply_to_human(mob/living/carbon/human/target, value)
