/obj/machinery/washing_machine
	name = "washing machine"
	desc = "Gets rid of those pesky bloodstains, or your money back!"
/obj/machinery/washing_machine/examine(mob/user)
/obj/machinery/washing_machine/process(delta_time)
/obj/machinery/washing_machine/wash(clean_types)
/obj/machinery/washing_machine/proc/wash_cycle()
/obj/item/proc/dye_item(dye_color, dye_key_override)
	name = initial(target_type.name)
	desc = "[initial(target_type.desc)] The colors look a little dodgy."
/atom/movable/proc/machine_wash(obj/machinery/washing_machine/washer)
/obj/item/stack/sheet/hairlesshide/machine_wash(obj/machinery/washing_machine/washer)
/obj/item/clothing/suit/hooded/ian_costume/machine_wash(obj/machinery/washing_machine/washer)
/mob/living/simple_animal/pet/machine_wash(obj/machinery/washing_machine/washer)
/obj/item/machine_wash(obj/machinery/washing_machine/washer)
/obj/item/clothing/under/dye_item(dye_color, dye_key)
/obj/item/clothing/under/machine_wash(obj/machinery/washing_machine/washer)
/obj/item/clothing/head/mob_holder/machine_wash(obj/machinery/washing_machine/washer)
/obj/item/clothing/shoes/sneakers/machine_wash(obj/machinery/washing_machine/washer)
/obj/machinery/washing_machine/relaymove(mob/living/user, direction)
/obj/machinery/washing_machine/container_resist_act(mob/living/user)
/obj/machinery/washing_machine/update_icon_state()
/obj/machinery/washing_machine/update_overlays()
/obj/machinery/washing_machine/attackby(obj/item/W, mob/living/user, params)
/obj/machinery/washing_machine/attack_hand(mob/living/user, list/modifiers)
/obj/machinery/washing_machine/attack_hand_secondary(mob/user, modifiers)
/obj/machinery/washing_machine/attack_ai_secondary(mob/user, modifiers)
/obj/machinery/washing_machine/deconstruct(disassembled = TRUE)
/obj/machinery/washing_machine/open_machine(drop = 1)
