/mob/living/carbon/alien/get_eye_protection()
/mob/living/carbon/alien/get_ear_protection()
/mob/living/carbon/alien/hitby(atom/movable/AM, skipcatch, hitpush, blocked, datum/thrownthing/throwingdatum)
/mob/living/carbon/alien/attack_alien(mob/living/carbon/alien/user, list/modifiers)
/mob/living/carbon/alien/attack_larva(mob/living/carbon/alien/larva/L)
/mob/living/carbon/alien/attack_hand(mob/living/carbon/human/user, list/modifiers)
/mob/living/carbon/alien/attack_paw(mob/living/carbon/human/user, list/modifiers)
/mob/living/carbon/alien/attack_animal(mob/living/simple_animal/user, list/modifiers)
/mob/living/carbon/alien/attack_slime(mob/living/simple_animal/slime/M)
/mob/living/carbon/alien/ex_act(severity, target, origin)
/mob/living/carbon/alien/soundbang_act(intensity = 1, stun_pwr = 20, damage_pwr = 5, deafen_pwr = 15)
/mob/living/carbon/alien/acid_act(acidpwr, acid_volume)
