/world/New()
/world/proc/InitTgs()
/world/proc/HandleTestRun()
/world/proc/SetupLogs()
/world/Topic(T, addr, master, key)
/world/proc/AnnouncePR(announcement, list/payload)
/world/proc/FinishTestRun()
/world/Reboot(reason = 0, fast_track = FALSE)
/world/proc/update_status()
/world/proc/update_hub_visibility(new_visibility)
/world/proc/incrementMaxZ()
/world/proc/change_fps(new_value = 20)
/world/proc/change_tick_lag(new_value = 0.5)
/world/proc/on_tickrate_change()
