/datum/sparring_match
/datum/sparring_match/New(weapons_condition, arena_condition, stakes_condition, mob/living/carbon/human/chaplain, mob/living/carbon/human/opponent)
/datum/sparring_match/proc/hook_signals(mob/living/carbon/human/sparring)
/datum/sparring_match/proc/unhook_signals(mob/living/carbon/human/sparring)
/datum/sparring_match/proc/check_for_victory(datum/participant, new_stat)
/datum/sparring_match/proc/outsider_interference(datum/source, obj/item/I, mob/attacker)
/datum/sparring_match/proc/hulk_interference(datum/source, mob/attacker)
/datum/sparring_match/proc/hand_interference(datum/source, mob/living/attacker)
/datum/sparring_match/proc/paw_interference(datum/source, mob/living/attacker)
/datum/sparring_match/proc/thrown_interference(datum/source, atom/movable/thrown_movable, skipcatch = FALSE, hitpush = TRUE, blocked = FALSE, datum/thrownthing/throwingdatum)
/datum/sparring_match/proc/projectile_interference(datum/participant, obj/projectile/proj)
/datum/sparring_match/proc/death_flub(datum/deceased)
/datum/sparring_match/proc/deletion_flub(datum/qdeleting)
/datum/sparring_match/proc/gun_violation(datum/offender)
/datum/sparring_match/proc/grenade_violation(datum/offender)
/datum/sparring_match/proc/melee_violation(datum/offender, obj/item/thing, mob/user, params)
/datum/sparring_match/proc/teleport_violation(datum/offender)
/datum/sparring_match/proc/arena_violation(atom/movable/mover, atom/oldloc, direction)
/datum/sparring_match/proc/violation(mob/living/carbon/human/offender, reason)
/datum/sparring_match/proc/flub(mob/living/interfering)
/datum/sparring_match/proc/flubbed_match()
/datum/sparring_match/proc/cleanup_sparring_match()
/datum/sparring_match/proc/end_match(mob/living/carbon/human/winner, mob/living/carbon/human/loser, violation_victory = FALSE)
/datum/sparring_match/proc/win(mob/living/carbon/human/winner, mob/living/carbon/human/loser, violation_victory)
/datum/sparring_match/proc/lose(mob/living/carbon/human/loser, mob/living/carbon/human/winner)
