/obj/item/organ/heart/gland/heal
/obj/item/organ/heart/gland/heal/activate()
/obj/item/organ/heart/gland/heal/proc/reject_implant(obj/item/implant/implant)
/obj/item/organ/heart/gland/heal/proc/reject_cyberimp(obj/item/organ/cyberimp/implant)
/obj/item/organ/heart/gland/heal/proc/replace_appendix(obj/item/organ/appendix/appendix)
/obj/item/organ/heart/gland/heal/proc/replace_liver(obj/item/organ/liver/liver)
/obj/item/organ/heart/gland/heal/proc/replace_lungs(obj/item/organ/lungs/lungs)
/obj/item/organ/heart/gland/heal/proc/replace_stomach(obj/item/organ/stomach/stomach)
/obj/item/organ/heart/gland/heal/proc/replace_eyes(obj/item/organ/eyes/eyes)
/obj/item/organ/heart/gland/heal/proc/finish_replace_eyes()
/obj/item/organ/heart/gland/heal/proc/replace_limb(body_zone, obj/item/bodypart/limb)
/obj/item/organ/heart/gland/heal/proc/finish_replace_limb(body_zone)
/obj/item/organ/heart/gland/heal/proc/replace_blood()
/obj/item/organ/heart/gland/heal/proc/keep_replacing_blood()
/obj/item/organ/heart/gland/heal/proc/replace_chest(obj/item/bodypart/chest/chest)
