/proc/build_name2reagent()
/datum/reagent
/datum/reagent/New()
/datum/reagent/Destroy() // This should only be called by the holder, so it's already handled clearing its references
/datum/reagent/proc/expose_atom(atom/exposed_atom, reac_volume)
/datum/reagent/proc/expose_mob(mob/living/exposed_mob, methods=TOUCH, reac_volume, show_message = TRUE, touch_protection = 0)
/datum/reagent/proc/expose_obj(obj/exposed_obj, reac_volume)
/datum/reagent/proc/expose_turf(turf/exposed_turf, reac_volume)
/datum/reagent/proc/burn(datum/reagents/holder)
/datum/reagent/proc/on_mob_life(mob/living/carbon/M, delta_time, times_fired)
/datum/reagent/proc/intercept_reagents_transfer(datum/reagents/target)
/datum/reagent/proc/on_transfer(atom/A, methods=TOUCH, trans_volume)
/datum/reagent/proc/on_mob_add(mob/living/L, amount)
/datum/reagent/proc/on_mob_delete(mob/living/L)
/datum/reagent/proc/on_mob_metabolize(mob/living/L)
/datum/reagent/proc/on_mob_end_metabolize(mob/living/L)
/datum/reagent/proc/on_mob_dead(mob/living/carbon/C, delta_time)
/datum/reagent/proc/on_move(mob/M)
/datum/reagent/proc/on_new(data)
/datum/reagent/proc/on_merge(data, amount)
/datum/reagent/proc/on_update(atom/A)
/datum/reagent/proc/on_ex_act(severity)
/datum/reagent/proc/overdose_process(mob/living/M, delta_time, times_fired)
/datum/reagent/proc/overdose_start(mob/living/M)
/datum/reagent/proc/on_hydroponics_apply(obj/item/seeds/myseed, datum/reagents/chems, obj/machinery/hydroponics/mytray, mob/user)
/datum/reagent/proc/get_taste_description(mob/living/taster)
/datum/reagent/proc/normalise_creation_purity(normalise_num_to, creation_purity)
/proc/pretty_string_from_reagent_list(list/reagent_list)
