/turf/proc/reconsider_lights()
/turf/proc/lighting_clear_overlay()
/turf/proc/lighting_build_overlay()
/turf/proc/get_lumcount(minlum = 0, maxlum = 1)
/turf/proc/is_softly_lit()
/turf/proc/add_opacity_source(atom/movable/new_source)
/turf/proc/remove_opacity_source(atom/movable/old_source)
/turf/proc/recalculate_directional_opacity()
/turf/proc/change_area(area/old_area, area/new_area)
/turf/proc/generate_missing_corners()
