	name = "Blackbox"
/datum/controller/subsystem/blackbox/Initialize()
/datum/controller/subsystem/blackbox/fire()
/datum/controller/subsystem/blackbox/proc/CheckPlayerCount()
/datum/controller/subsystem/blackbox/Recover()
/datum/controller/subsystem/blackbox/vv_get_var(var_name)
/datum/controller/subsystem/blackbox/vv_edit_var(var_name, var_value)
/datum/controller/subsystem/blackbox/proc/FinalFeedback()
/datum/controller/subsystem/blackbox/Shutdown()
/datum/controller/subsystem/blackbox/proc/Seal()
/datum/controller/subsystem/blackbox/proc/LogBroadcast(freq)
/datum/controller/subsystem/blackbox/proc/find_feedback_datum(key, key_type)
/datum/controller/subsystem/blackbox/proc/record_feedback(key_type, key, increment, data, overwrite)
/datum/controller/subsystem/blackbox/proc/record_feedback_recurse_list(list/L, list/key_list, increment, depth = 1)
/datum/feedback_variable
/datum/feedback_variable/New(new_key, new_key_type)
/datum/controller/subsystem/blackbox/proc/LogAhelp(ticket, action, message, recipient, sender, urgent = FALSE)
/datum/controller/subsystem/blackbox/proc/ReportDeath(mob/living/L)
/datum/controller/subsystem/blackbox/proc/ReportCitation(citation, sender, sender_ic, recipient, message, fine = 0, paid = 0)
