	name = "Mapping"
/datum/controller/subsystem/mapping/New()
/datum/controller/subsystem/mapping/Initialize(timeofday)
/datum/controller/subsystem/mapping/proc/wipe_reservations(wipe_safety_delay = 100)
/datum/controller/subsystem/mapping/proc/safety_clear_transit_dock(obj/docking_port/stationary/transit/T, obj/docking_port/mobile/M, list/returning)
/datum/controller/subsystem/mapping/proc/add_nuke_threat(datum/nuke)
/datum/controller/subsystem/mapping/proc/remove_nuke_threat(datum/nuke)
/datum/controller/subsystem/mapping/proc/check_nuke_threats()
/datum/controller/subsystem/mapping/Recover()
/datum/controller/subsystem/mapping/proc/LoadGroup(list/errorList, name, path, files, list/traits, list/default_traits, silent = FALSE)
/datum/controller/subsystem/mapping/proc/loadWorld()
/datum/controller/subsystem/mapping/proc/generate_station_area_list()
/datum/controller/subsystem/mapping/proc/run_map_generation()
/datum/controller/subsystem/mapping/proc/maprotate()
/datum/controller/subsystem/mapping/proc/mapvote()
/datum/controller/subsystem/mapping/proc/changemap(datum/map_config/VM)
/datum/controller/subsystem/mapping/proc/preloadTemplates(path = "_maps/templates/") //see master controller setup
/datum/controller/subsystem/mapping/proc/preloadRuinTemplates()
/datum/controller/subsystem/mapping/proc/preloadShuttleTemplates()
/datum/controller/subsystem/mapping/proc/preloadShelterTemplates()
/datum/controller/subsystem/mapping/proc/preloadHolodeckTemplates()
/client/proc/admin_away()
/datum/controller/subsystem/mapping/proc/RequestBlockReservation(width, height, z, type = /datum/turf_reservation, turf_type_override)
/datum/controller/subsystem/mapping/proc/initialize_reserved_level(z)
/datum/controller/subsystem/mapping/proc/reserve_turfs(list/turfs)
/datum/controller/subsystem/mapping/proc/do_wipe_turf_reservations()
/datum/controller/subsystem/mapping/proc/initialize_biomes()
/datum/controller/subsystem/mapping/proc/reg_in_areas_in_z(list/areas)
/datum/controller/subsystem/mapping/proc/get_isolated_ruin_z()
/datum/controller/subsystem/mapping/proc/spawn_maintenance_loot()
