	name = "Research"
/obj/item/assembly/signaler/anomaly = list(TECHWEB_POINT_TYPE_GENERIC = 10000)
/datum/controller/subsystem/research/Initialize()
/datum/controller/subsystem/research/fire()
/datum/controller/subsystem/research/proc/calculate_server_coefficient() //Diminishing returns.
/datum/controller/subsystem/research/proc/autosort_categories()
/datum/controller/subsystem/research/proc/techweb_node_by_id(id)
/datum/controller/subsystem/research/proc/techweb_design_by_id(id)
/datum/controller/subsystem/research/proc/on_design_deletion(datum/design/D)
/datum/controller/subsystem/research/proc/on_node_deletion(datum/techweb_node/TN)
/datum/controller/subsystem/research/proc/initialize_all_techweb_nodes(clearall = FALSE)
/datum/controller/subsystem/research/proc/initialize_all_techweb_designs(clearall = FALSE)
/datum/controller/subsystem/research/proc/verify_techweb_nodes()
/datum/controller/subsystem/research/proc/verify_techweb_designs()
/datum/controller/subsystem/research/proc/research_node_id_error(id)
/datum/controller/subsystem/research/proc/design_id_error(id)
/datum/controller/subsystem/research/proc/calculate_techweb_nodes()
/datum/controller/subsystem/research/proc/generate_techweb_unlock_linking()
/datum/controller/subsystem/research/proc/calculate_techweb_boost_list(clearall = FALSE)
