	name = "Shuttle"
/datum/controller/subsystem/shuttle/Initialize(timeofday)
/datum/controller/subsystem/shuttle/proc/initial_load()
/datum/controller/subsystem/shuttle/fire()
/datum/controller/subsystem/shuttle/proc/CheckAutoEvac()
/datum/controller/subsystem/shuttle/proc/block_recall(lockout_timer)
/datum/controller/subsystem/shuttle/proc/unblock_recall()
/datum/controller/subsystem/shuttle/proc/getShuttle(id)
/datum/controller/subsystem/shuttle/proc/getDock(id)
/datum/controller/subsystem/shuttle/proc/canEvac(mob/user)
/datum/controller/subsystem/shuttle/proc/requestEvac(mob/user, call_reason)
/datum/controller/subsystem/shuttle/proc/centcom_recall(old_timer, admiral_message)
/datum/controller/subsystem/shuttle/proc/emergencyDeregister()
/datum/controller/subsystem/shuttle/proc/cancelEvac(mob/user)
/datum/controller/subsystem/shuttle/proc/canRecall()
/datum/controller/subsystem/shuttle/proc/autoEvac()
/datum/controller/subsystem/shuttle/proc/registerHostileEnvironment(datum/bad)
/datum/controller/subsystem/shuttle/proc/clearHostileEnvironment(datum/bad)
/datum/controller/subsystem/shuttle/proc/registerTradeBlockade(datum/bad)
/datum/controller/subsystem/shuttle/proc/clearTradeBlockade(datum/bad)
/datum/controller/subsystem/shuttle/proc/checkTradeBlockade()
/datum/controller/subsystem/shuttle/proc/checkHostileEnvironment()
/datum/controller/subsystem/shuttle/proc/toggleShuttle(shuttleId, dockHome, dockAway, timed)
/datum/controller/subsystem/shuttle/proc/moveShuttle(shuttleId, dockId, timed)
/datum/controller/subsystem/shuttle/proc/request_transit_dock(obj/docking_port/mobile/M)
/datum/controller/subsystem/shuttle/proc/generate_transit_dock(obj/docking_port/mobile/M)
/datum/controller/subsystem/shuttle/Recover()
/datum/controller/subsystem/shuttle/proc/is_in_shuttle_bounds(atom/A)
/datum/controller/subsystem/shuttle/proc/get_containing_shuttle(atom/A)
/datum/controller/subsystem/shuttle/proc/get_containing_dock(atom/A)
/datum/controller/subsystem/shuttle/proc/get_dock_overlap(x0, y0, x1, y1, z)
/datum/controller/subsystem/shuttle/proc/update_hidden_docking_ports(list/remove_turfs, list/add_turfs)
/datum/controller/subsystem/shuttle/proc/action_load(datum/map_template/shuttle/loading_template, obj/docking_port/stationary/destination_port, replace = FALSE)
/datum/controller/subsystem/shuttle/proc/load_template(datum/map_template/shuttle/S)
/datum/controller/subsystem/shuttle/proc/unload_preview()
/datum/controller/subsystem/shuttle/ui_state(mob/user)
/datum/controller/subsystem/shuttle/ui_interact(mob/user, datum/tgui/ui)
/datum/controller/subsystem/shuttle/ui_data(mob/user)
/datum/controller/subsystem/shuttle/ui_act(action, params)
/datum/controller/subsystem/shuttle/proc/init_has_purchase_shuttle_access()
