	name = "tgui"
/datum/controller/subsystem/tgui/PreInit()
/datum/controller/subsystem/tgui/Shutdown()
/datum/controller/subsystem/tgui/stat_entry(msg)
/datum/controller/subsystem/tgui/fire(resumed = FALSE)
/datum/controller/subsystem/tgui/proc/request_pooled_window(mob/user)
/datum/controller/subsystem/tgui/proc/force_close_all_windows(mob/user)
/datum/controller/subsystem/tgui/proc/force_close_window(mob/user, window_id)
/datum/controller/subsystem/tgui/proc/try_update_ui(
/datum/controller/subsystem/tgui/proc/get_open_ui(mob/user, datum/src_object)
/datum/controller/subsystem/tgui/proc/update_uis(datum/src_object)
/datum/controller/subsystem/tgui/proc/close_uis(datum/src_object)
/datum/controller/subsystem/tgui/proc/close_all_uis()
/datum/controller/subsystem/tgui/proc/update_user_uis(mob/user, datum/src_object)
/datum/controller/subsystem/tgui/proc/close_user_uis(mob/user, datum/src_object)
/datum/controller/subsystem/tgui/proc/on_open(datum/tgui/ui)
/datum/controller/subsystem/tgui/proc/on_close(datum/tgui/ui)
/datum/controller/subsystem/tgui/proc/on_logout(mob/user)
/datum/controller/subsystem/tgui/proc/on_transfer(mob/source, mob/target)
