	name = "Ticker"
/datum/controller/subsystem/ticker/Initialize(timeofday)
/datum/controller/subsystem/ticker/fire()
/datum/controller/subsystem/ticker/proc/setup()
/datum/controller/subsystem/ticker/proc/PostSetup()
/datum/controller/subsystem/ticker/proc/OnRoundstart(datum/callback/cb)
/datum/controller/subsystem/ticker/proc/OnRoundend(datum/callback/cb)
/datum/controller/subsystem/ticker/proc/station_explosion_detonation(atom/bomb)
/datum/controller/subsystem/ticker/proc/create_characters()
/datum/controller/subsystem/ticker/proc/collect_minds()
/datum/controller/subsystem/ticker/proc/equip_characters()
/datum/controller/subsystem/ticker/proc/decide_security_officer_departments(
/datum/controller/subsystem/ticker/proc/transfer_characters()
/datum/controller/subsystem/ticker/proc/release_characters(list/livings)
/datum/controller/subsystem/ticker/proc/check_queue()
/datum/controller/subsystem/ticker/proc/check_maprotate()
/datum/controller/subsystem/ticker/proc/HasRoundStarted()
/datum/controller/subsystem/ticker/proc/IsRoundInProgress()
/datum/controller/subsystem/ticker/Recover()
/datum/controller/subsystem/ticker/proc/send_news_report()
/datum/controller/subsystem/ticker/proc/GetTimeLeft()
/datum/controller/subsystem/ticker/proc/SetTimeLeft(newtime)
/datum/controller/subsystem/ticker/proc/SetRoundEndSound(the_sound)
/datum/controller/subsystem/ticker/proc/Reboot(reason, end_string, delay)
/datum/controller/subsystem/ticker/Shutdown()
/datum/controller/subsystem/ticker/proc/choose_round_end_song()
