/datum/ai_controller/dog
/datum/ai_controller/dog/process(delta_time)
/datum/ai_controller/dog/TryPossessPawn(atom/new_pawn)
/datum/ai_controller/dog/UnpossessPawn(destroy)
/datum/ai_controller/dog/able_to_run()
/datum/ai_controller/dog/get_access()
/datum/ai_controller/dog/proc/listened_throw(datum/source, mob/living/carbon/carbon_thrower)
/datum/ai_controller/dog/proc/listen_throw_land(obj/item/thrown_thing, datum/thrownthing/throwing_datum)
/datum/ai_controller/dog/proc/on_attack_hand(datum/source, mob/living/user)
/datum/ai_controller/dog/proc/befriend(mob/living/new_friend)
/datum/ai_controller/dog/proc/unfriend(mob/living/ex_friend)
/datum/ai_controller/dog/proc/on_examined(datum/source, mob/user, list/examine_text)
/datum/ai_controller/dog/proc/on_death(mob/living/ol_yeller)
/datum/ai_controller/dog/proc/check_altclicked(datum/source, mob/living/clicker)
/datum/ai_controller/dog/proc/command_radial(mob/living/clicker)
/datum/ai_controller/dog/proc/check_menu(mob/user)
/datum/ai_controller/dog/proc/check_verbal_command(mob/speaker, speech_args)
/datum/ai_controller/dog/proc/set_command_mode(mob/commander, command)
/datum/ai_controller/dog/proc/check_point(mob/pointing_friend, atom/movable/pointed_movable)
