/datum/game_mode/dynamic
/datum/game_mode/dynamic/admin_panel()
/datum/game_mode/dynamic/Topic(href, href_list)
/datum/game_mode/dynamic/set_round_result()
/datum/game_mode/dynamic/proc/send_intercept()
/datum/game_mode/dynamic/proc/show_threatlog(mob/admin)
/datum/game_mode/dynamic/proc/generate_threat()
/datum/game_mode/dynamic/proc/generate_budgets()
/datum/game_mode/dynamic/proc/setup_parameters()
/datum/game_mode/dynamic/proc/setup_shown_threat()
/datum/game_mode/dynamic/proc/set_cooldowns()
/datum/game_mode/dynamic/pre_setup()
/datum/game_mode/dynamic/post_setup(report)
/datum/game_mode/dynamic/proc/setup_rulesets()
/datum/game_mode/dynamic/proc/init_rulesets(ruleset_subtype)
/datum/game_mode/dynamic/proc/rigged_roundstart()
/datum/game_mode/dynamic/proc/roundstart(list/roundstart_rules)
/datum/game_mode/dynamic/proc/picking_roundstart_rule(datum/dynamic_ruleset/roundstart/ruleset, scaled_times = 0, forced = FALSE)
/datum/game_mode/dynamic/proc/execute_roundstart_rule(sent_rule)
/datum/game_mode/dynamic/proc/picking_specific_rule(ruletype, forced = FALSE)
/datum/game_mode/dynamic/process()
/datum/game_mode/dynamic/proc/get_injection_chance(dry_run = FALSE)
/datum/game_mode/dynamic/proc/get_midround_injection_chance(dry_run)
/datum/game_mode/dynamic/proc/remove_from_list(list/type_list, type)
/datum/game_mode/dynamic/proc/check_blocking(list/blocking_list, list/rule_list)
/datum/game_mode/dynamic/make_antag_chance(mob/living/carbon/human/newPlayer)
/datum/game_mode/dynamic/proc/configure_ruleset(datum/dynamic_ruleset/ruleset)
/datum/game_mode/dynamic/proc/refund_threat(regain)
/datum/game_mode/dynamic/proc/create_threat(gain)
/datum/game_mode/dynamic/proc/spend_roundstart_budget(cost)
/datum/game_mode/dynamic/proc/spend_midround_budget(cost)
/datum/game_mode/dynamic/proc/lorentz_to_amount(x)
/datum/game_mode/dynamic/proc/dynamic_log(text)
