/mob/living/proc/HasDisease(datum/disease/D)
/mob/living/proc/CanContractDisease(datum/disease/D)
/mob/living/proc/ContactContractDisease(datum/disease/D)
/mob/living/carbon/ContactContractDisease(datum/disease/D, target_zone)
/mob/living/proc/AirborneContractDisease(datum/disease/D, force_spread)
/mob/living/carbon/AirborneContractDisease(datum/disease/D, force_spread)
/mob/living/proc/ForceContractDisease(datum/disease/D, make_copy = TRUE, del_on_fail = FALSE)
/mob/living/carbon/human/CanContractDisease(datum/disease/D)
/mob/living/proc/CanSpreadAirborneDisease()
/mob/living/carbon/CanSpreadAirborneDisease()
